@startuml Templates For Use In Other Diagrams
title Templates For Use In Other Diagrams

!startsub COMMON_INCLUDES
    !includesub common-header.iuml!MAIN
    !includesub functions.iuml!MAIN
!endsub

' Not sending the $rootPath here since it should be defined in the diagram including this one.
!startsub COMMON_PARTICIPANTS
    !if %not(%variable_exists("$NO_ACTORS"))
        !includesub participants.yourDomainHere/common.participants.actors.iuml!MAIN
    !endif
    !if %not(%variable_exists("$NO_INFRA"))
        !includesub participants.yourDomainHere/common.participants.infrastructure.iuml!MAIN
    !endif
    !if %not(%variable_exists("$NO_SEEME"))
        participant seeme [
            <color:LightGray><size:8>(""seeme"")
            <color:DarkGray><$person*.5>
            Look Away
            <size:8><color:Gray>(Should not see
            <size:8><color:Gray>this participant)
        ]
    !endif
    
    !if %not(%variable_exists("$NO_CLUSTER"))
        !includesub participants.yourDomainHere/common.participants.cluster.iuml!MAIN
    !endif
!endsub

!startsub COMMON_TEST
user -> api: If you can see this, you didn't include ONLY the sub-template.
!endsub
@enduml