@startuml
!define ip /Volumes/SRC/plantuml-stdlib/logos
!include ip/100tb.puml
!include ip/500px.puml
!include ip/6px.puml
!include ip/active-campaign-icon.puml
!include ip/active-campaign.puml
!include ip/admob.puml
!include ip/adobe-after-effects.puml
!include ip/adobe-animate.puml
!include ip/adobe-dreamweaver.puml
!include ip/adobe-illustrator.puml
!include ip/adobe-incopy.puml
!include ip/adobe-indesign.puml
!include ip/adobe-lightroom.puml
!include ip/adobe-photoshop.puml
!include ip/adobe-premiere.puml
!include ip/adobe-xd.puml
!include ip/adonisjs-icon.puml
!include ip/adonisjs.puml
!include ip/adroll.puml
!include ip/adyen.puml
!include ip/aerogear.puml
!include ip/aerospike-icon.puml
!include ip/aerospike.puml
!include ip/aha.puml
!include ip/airbnb-icon.puml
!include ip/airbnb.puml
!include ip/airbrake.puml
!include ip/airflow-icon.puml
!include ip/airflow.puml
!include ip/airtable.puml
!include ip/aix.puml
!include ip/akamai.puml
!include ip/akka.puml
!include ip/alfresco.puml
!include ip/algolia.puml
!include ip/alma.puml
!include ip/alpinejs-icon.puml
!include ip/alpinejs.puml
!include ip/altair.puml
!include ip/amazon-chime.puml
!include ip/amazon-connect.puml
!include ip/amd.puml
!include ip/amex-digital.puml
!include ip/amex.puml
!include ip/amp-icon.puml
!include ip/amp.puml
!include ip/ampersand.puml
!include ip/amplication-icon.puml
!include ip/amplication.puml
!include ip/amplitude-icon.puml
!include ip/amplitude.puml
!include ip/android-icon.puml
!include ip/android-vertical.puml
!include ip/android.puml
!include ip/angellist.puml
!include ip/angular-icon.puml
!include ip/angular.puml
!include ip/ansible.puml
!include ip/ant-design.puml
!include ip/apache-camel.puml
!include ip/apache.puml
!include ip/apache_cloudstack.puml
!include ip/api-ai.puml
!include ip/apiary.puml
!include ip/apigee.puml
!include ip/apitools.puml
!include ip/apollostack.puml
!include ip/apostrophe.puml
!include ip/appbase.puml
!include ip/appbaseio-icon.puml
!include ip/appbaseio.puml
!include ip/appcelerator.puml
!include ip/appcenter-icon.puml
!include ip/appcenter.puml
!include ip/appcircle-icon.puml
!include ip/appcircle.puml
!include ip/appcode.puml
!include ip/appdynamics-icon.puml
!include ip/appdynamics.puml
!include ip/appfog.puml
!include ip/apphub.puml
!include ip/appium.puml
!include ip/apple-app-store.puml
!include ip/apple-pay.puml
!include ip/apple.puml
!include ip/applitools-icon.puml
!include ip/applitools.puml
!include ip/appmaker.puml
!include ip/apportable.puml
!include ip/appsignal-icon.puml
!include ip/appsignal.puml
!include ip/apptentive.puml
!include ip/appveyor.puml
!include ip/appwrite-icon.puml
!include ip/appwrite.puml
!include ip/arangodb-icon.puml
!include ip/arangodb.puml
!include ip/arc.puml
!include ip/architect-icon.puml
!include ip/architect.puml
!include ip/archlinux.puml
!include ip/arduino.puml
!include ip/argo-icon.puml
!include ip/argo.puml
!include ip/arm.puml
!include ip/armory-icon.puml
!include ip/armory.puml
!include ip/asana-icon.puml
!include ip/asana.puml
!include ip/asciidoctor.puml
!include ip/assembla-icon.puml
!include ip/assembla.puml
!include ip/astro-icon.puml
!include ip/astro.puml
!include ip/astronomer.puml
!include ip/async-api-icon.puml
!include ip/async-api.puml
!include ip/atlassian.puml
!include ip/atom-icon.puml
!include ip/atom.puml
!include ip/atomic-icon.puml
!include ip/atomic.puml
!include ip/atomicojs-icon.puml
!include ip/atomicojs.puml
!include ip/aurelia.puml
!include ip/aurora.puml
!include ip/aurous.puml
!include ip/auth0-icon.puml
!include ip/auth0.puml
!include ip/authy.puml
!include ip/autocode.puml
!include ip/autoit.puml
!include ip/autoprefixer.puml
!include ip/ava.puml
!include ip/awesome.puml
!include ip/aws-amplify.puml
!include ip/aws-api-gateway.puml
!include ip/aws-app-mesh.puml
!include ip/aws-appflow.puml
!include ip/aws-appsync.puml
!include ip/aws-athena.puml
!include ip/aws-aurora.puml
!include ip/aws-backup.puml
!include ip/aws-batch.puml
!include ip/aws-certificate-manager.puml
!include ip/aws-cloudformation.puml
!include ip/aws-cloudfront.puml
!include ip/aws-cloudsearch.puml
!include ip/aws-cloudtrail.puml
!include ip/aws-cloudwatch.puml
!include ip/aws-codebuild.puml
!include ip/aws-codecommit.puml
!include ip/aws-codedeploy.puml
!include ip/aws-codepipeline.puml
!include ip/aws-codestar.puml
!include ip/aws-cognito.puml
!include ip/aws-config.puml
!include ip/aws-documentdb.puml
!include ip/aws-dynamodb.puml
!include ip/aws-ec2.puml
!include ip/aws-ecs.puml
!include ip/aws-eks.puml
!include ip/aws-elastic-beanstalk.puml
!include ip/aws-elastic-cache.puml
!include ip/aws-elasticache.puml
!include ip/aws-elb.puml
!include ip/aws-eventbridge.puml
!include ip/aws-fargate.puml
!include ip/aws-glacier.puml
!include ip/aws-glue.puml
!include ip/aws-iam.puml
!include ip/aws-keyspaces.puml
!include ip/aws-kinesis.puml
!include ip/aws-kms.puml
!include ip/aws-lake-formation.puml
!include ip/aws-lambda.puml
!include ip/aws-lightsail.puml
!include ip/aws-mobilehub.puml
!include ip/aws-mq.puml
!include ip/aws-msk.puml
!include ip/aws-neptune.puml
!include ip/aws-open-search.puml
!include ip/aws-opsworks.puml
!include ip/aws-quicksight.puml
!include ip/aws-rds.puml
!include ip/aws-redshift.puml
!include ip/aws-route53.puml
!include ip/aws-s3.puml
!include ip/aws-secrets-manager.puml
!include ip/aws-ses.puml
!include ip/aws-shield.puml
!include ip/aws-sns.puml
!include ip/aws-sqs.puml
!include ip/aws-step-functions.puml
!include ip/aws-systems-manager.puml
!include ip/aws-timestream.puml
!include ip/aws-vpc.puml
!include ip/aws-waf.puml
!include ip/aws-xray.puml
!include ip/aws.puml
!include ip/axios.puml
!include ip/azure.puml
!include ip/babel.puml
!include ip/backbone-icon.puml
!include ip/backbone.puml
!include ip/backerkit.puml
!include ip/baker-street.puml
!include ip/balena.puml
!include ip/bamboo.puml
!include ip/basecamp-icon.puml
!include ip/basecamp.puml
!include ip/basekit.puml
!include ip/bash-icon.puml
!include ip/bash.puml
!include ip/batch.puml
!include ip/beats.puml
!include ip/behance.puml
!include ip/bem-2.puml
!include ip/bem.puml
!include ip/bigpanda.puml
!include ip/bing.puml
!include ip/bitballoon.puml
!include ip/bitbar.puml
!include ip/bitbucket.puml
!include ip/bitcoin.puml
!include ip/bitnami.puml
!include ip/bitrise-icon.puml
!include ip/bitrise.puml
!include ip/blender.puml
!include ip/blitzjs-icon.puml
!include ip/blitzjs.puml
!include ip/blocs.puml
!include ip/blogger.puml
!include ip/blossom.puml
!include ip/bluemix.puml
!include ip/blueprint.puml
!include ip/bluetooth.puml
!include ip/booqable-icon.puml
!include ip/booqable.puml
!include ip/bootstrap.puml
!include ip/bosun.puml
!include ip/botanalytics.puml
!include ip/bourbon.puml
!include ip/bower.puml
!include ip/bowtie.puml
!include ip/box.puml
!include ip/brackets.puml
!include ip/brainjs.puml
!include ip/branch-icon.puml
!include ip/branch.puml
!include ip/brandfolder-icon.puml
!include ip/brandfolder.puml
!include ip/brave.puml
!include ip/braze-icon.puml
!include ip/braze.puml
!include ip/broadcom-icon.puml
!include ip/broadcom.puml
!include ip/broccoli.puml
!include ip/brotli.puml
!include ip/browserify-icon.puml
!include ip/browserify.puml
!include ip/browserling.puml
!include ip/browserslist.puml
!include ip/browserstack.puml
!include ip/browsersync.puml
!include ip/brunch.puml
!include ip/bubble-icon.puml
!include ip/bubble.puml
!include ip/buck.puml
!include ip/buddy.puml
!include ip/buffer.puml
!include ip/bugherd-icon.puml
!include ip/bugherd.puml
!include ip/bugsee.puml
!include ip/bugsnag-icon.puml
!include ip/bugsnag.puml
!include ip/builder-io-icon.puml
!include ip/builder-io.puml
!include ip/buildkite-icon.puml
!include ip/buildkite.puml
!include ip/bulma.puml
!include ip/bun.puml
!include ip/bunny-net-icon.puml
!include ip/bunny-net.puml
!include ip/c-plusplus.puml
!include ip/c-sharp.puml
!include ip/c.puml
!include ip/cachet.puml
!include ip/caffe2.puml
!include ip/cakephp-icon.puml
!include ip/cakephp.puml
!include ip/calibre-icon.puml
!include ip/calibre.puml
!include ip/campaignmonitor-icon.puml
!include ip/campaignmonitor.puml
!include ip/campfire.puml
!include ip/canjs.puml
!include ip/capacitorjs-icon.puml
!include ip/capacitorjs.puml
!include ip/capistrano.puml
!include ip/carbide.puml
!include ip/cardano-icon.puml
!include ip/cardano.puml
!include ip/cassandra.puml
!include ip/celluloid.puml
!include ip/centos-icon.puml
!include ip/centos.puml
!include ip/certbot.puml
!include ip/ceylon.puml
!include ip/chai.puml
!include ip/chalk.puml
!include ip/changetip.puml
!include ip/chargebee-icon.puml
!include ip/chargebee.puml
!include ip/chartblocks.puml
!include ip/chef.puml
!include ip/chevereto.puml
!include ip/chroma.puml
!include ip/chromatic-icon.puml
!include ip/chromatic.puml
!include ip/chrome-web-store.puml
!include ip/chrome.puml
!include ip/cinder.puml
!include ip/circleci.puml
!include ip/cirrus-ci.puml
!include ip/cirrus.puml
!include ip/clickdeploy.puml
!include ip/clio-lang.puml
!include ip/clion.puml
!include ip/cljs.puml
!include ip/clojure.puml
!include ip/close.puml
!include ip/cloud9.puml
!include ip/cloudacademy-icon.puml
!include ip/cloudacademy.puml
!include ip/cloudant.puml
!include ip/cloudcraft.puml
!include ip/cloudera.puml
!include ip/cloudflare-workers-icon.puml
!include ip/cloudflare-workers.puml
!include ip/cloudflare.puml
!include ip/cloudinary-icon.puml
!include ip/cloudinary.puml
!include ip/cloudlinux.puml
!include ip/clusterhq.puml
!include ip/cobalt.puml
!include ip/cockpit.puml
!include ip/cocoapods.puml
!include ip/coda-icon.puml
!include ip/coda.puml
!include ip/codacy.puml
!include ip/codebase.puml
!include ip/codebeat.puml
!include ip/codecademy.puml
!include ip/codeception.puml
!include ip/codeclimate-icon.puml
!include ip/codeclimate.puml
!include ip/codecov-icon.puml
!include ip/codecov.puml
!include ip/codefactor-icon.puml
!include ip/codefactor.puml
!include ip/codefund-icon.puml
!include ip/codefund.puml
!include ip/codeigniter-icon.puml
!include ip/codeigniter.puml
!include ip/codepen-icon.puml
!include ip/codepen.puml
!include ip/codepicnic.puml
!include ip/codepush.puml
!include ip/codersrank-icon.puml
!include ip/codersrank.puml
!include ip/coderwall.puml
!include ip/codesandbox-icon.puml
!include ip/codesandbox.puml
!include ip/codeschool.puml
!include ip/codesee-icon.puml
!include ip/codesee.puml
!include ip/codeship.puml
!include ip/codio.puml
!include ip/codrops.puml
!include ip/coffeescript.puml
!include ip/commitizen.puml
!include ip/compass.puml
!include ip/component.puml
!include ip/componentkit.puml
!include ip/compose-multiplatform.puml
!include ip/compose.puml
!include ip/composer.puml
!include ip/conan-io.puml
!include ip/concourse.puml
!include ip/concrete5.puml
!include ip/concretecms-icon.puml
!include ip/concretecms.puml
!include ip/conda.puml
!include ip/confluence.puml
!include ip/consul.puml
!include ip/containership.puml
!include ip/contentful.puml
!include ip/convox-icon.puml
!include ip/convox.puml
!include ip/copyleft-pirate.puml
!include ip/copyleft.puml
!include ip/corda.puml
!include ip/cordova.puml
!include ip/coreos-icon.puml
!include ip/coreos.puml
!include ip/couchbase.puml
!include ip/couchdb-icon.puml
!include ip/couchdb.puml
!include ip/coursera.puml
!include ip/coveralls.puml
!include ip/cpanel.puml
!include ip/craftcms.puml
!include ip/crashlytics.puml
!include ip/crateio.puml
!include ip/create-react-app.puml
!include ip/createjs.puml
!include ip/cross-browser-testing.puml
!include ip/crucible.puml
!include ip/crystal.puml
!include ip/css-3.puml
!include ip/css-3_official.puml
!include ip/cssnext.puml
!include ip/cube-icon.puml
!include ip/cube.puml
!include ip/cucumber.puml
!include ip/curl.puml
!include ip/customerio-icon.puml
!include ip/customerio.puml
!include ip/cyclejs.puml
!include ip/cypress-icon.puml
!include ip/cypress.puml
!include ip/d3.puml
!include ip/dailydev-icon.puml
!include ip/dailydev.puml
!include ip/daisyUI.puml
!include ip/danfo.puml
!include ip/dapulse.puml
!include ip/dart.puml
!include ip/dashlane-icon.puml
!include ip/dashlane.puml
!include ip/dat.puml
!include ip/data-station.puml
!include ip/database-labs.puml
!include ip/datadog.puml
!include ip/datagrip.puml
!include ip/dataspell.puml
!include ip/datocms-icon.puml
!include ip/datocms.puml
!include ip/dbt-icon.puml
!include ip/dbt.puml
!include ip/dcos-icon.puml
!include ip/dcos.puml
!include ip/debian.puml
!include ip/delicious.puml
!include ip/delighted-icon.puml
!include ip/delighted.puml
!include ip/deno.puml
!include ip/dependabot.puml
!include ip/dependencyci.puml
!include ip/deploy.puml
!include ip/deployhq-icon.puml
!include ip/deployhq.puml
!include ip/deppbot.puml
!include ip/derby.puml
!include ip/descript-icon.puml
!include ip/descript.puml
!include ip/designernews.puml
!include ip/desk.puml
!include ip/deviantart-icon.puml
!include ip/deviantart.puml
!include ip/dgraph-icon.puml
!include ip/dgraph.puml
!include ip/dialogflow.puml
!include ip/digital-ocean.puml
!include ip/dimer.puml
!include ip/dinersclub.puml
!include ip/discord-icon.puml
!include ip/discord.puml
!include ip/discourse-icon.puml
!include ip/discourse.puml
!include ip/discover.puml
!include ip/disqus.puml
!include ip/django-icon.puml
!include ip/django.puml
!include ip/dockbit.puml
!include ip/docker-icon.puml
!include ip/docker.puml
!include ip/doctrine.puml
!include ip/docusaurus.puml
!include ip/dojo-icon.puml
!include ip/dojo-toolkit.puml
!include ip/dojo.puml
!include ip/dolt.puml
!include ip/dotnet.puml
!include ip/doubleclick.puml
!include ip/dovetail-icon.puml
!include ip/dovetail.puml
!include ip/dreamfactory.puml
!include ip/dreamhost.puml
!include ip/dribbble-icon.puml
!include ip/dribbble.puml
!include ip/drift.puml
!include ip/drip.puml
!include ip/drizzle-icon.puml
!include ip/drizzle.puml
!include ip/drone-icon.puml
!include ip/drone.puml
!include ip/drools-icon.puml
!include ip/drools.puml
!include ip/dropbox.puml
!include ip/dropmark.puml
!include ip/dropzone.puml
!include ip/drupal-icon.puml
!include ip/drupal.puml
!include ip/duckduckgo.puml
!include ip/dynatrace-icon.puml
!include ip/dynatrace.puml
!include ip/dyndns.puml
!include ip/eager.puml
!include ip/ebanx.puml
!include ip/eclipse-icon.puml
!include ip/eclipse.puml
!include ip/ecma.puml
!include ip/edgedb.puml
!include ip/edgio-icon.puml
!include ip/edgio.puml
!include ip/editorconfig.puml
!include ip/egghead.puml
!include ip/elasticbox.puml
!include ip/elasticpath-icon.puml
!include ip/elasticpath.puml
!include ip/elasticsearch.puml
!include ip/electron.puml
!include ip/element.puml
!include ip/elemental-ui.puml
!include ip/elementary.puml
!include ip/eleventy.puml
!include ip/ello.puml
!include ip/elm-classic.puml
!include ip/elm.puml
!include ip/elo.puml
!include ip/emacs-classic.puml
!include ip/emacs.puml
!include ip/embedly.puml
!include ip/ember-tomster.puml
!include ip/ember.puml
!include ip/emmet.puml
!include ip/enact.puml
!include ip/engine-yard-icon.puml
!include ip/engine-yard.puml
!include ip/envato.puml
!include ip/envoy-icon.puml
!include ip/envoy.puml
!include ip/envoyer.puml
!include ip/enyo.puml
!include ip/epsagon-icon.puml
!include ip/epsagon.puml
!include ip/eraser-icon.puml
!include ip/eraser.puml
!include ip/erlang.puml
!include ip/es6.puml
!include ip/esbuild.puml
!include ip/esdoc.puml
!include ip/eslint-old.puml
!include ip/eslint.puml
!include ip/eta-icon.puml
!include ip/eta-lang.puml
!include ip/eta.puml
!include ip/etcd.puml
!include ip/ethereum-color.puml
!include ip/ethereum.puml
!include ip/ethers.puml
!include ip/ethnio.puml
!include ip/eventbrite-icon.puml
!include ip/eventbrite.puml
!include ip/eventsentry.puml
!include ip/evergreen-icon.puml
!include ip/evergreen.puml
!include ip/expo-icon.puml
!include ip/expo.puml
!include ip/exponent.puml
!include ip/express.puml
!include ip/fabric.puml
!include ip/fabric_io.puml
!include ip/facebook.puml
!include ip/falcor.puml
!include ip/fastify-icon.puml
!include ip/fastify.puml
!include ip/fastlane.puml
!include ip/fastly.puml
!include ip/fauna-icon.puml
!include ip/fauna.puml
!include ip/feathersjs.puml
!include ip/fedora.puml
!include ip/fetch.puml
!include ip/ffmpeg-icon.puml
!include ip/ffmpeg.puml
!include ip/figma.puml
!include ip/firebase.puml
!include ip/firefox.puml
!include ip/flannel.puml
!include ip/flarum.puml
!include ip/flask.puml
!include ip/flat-ui.puml
!include ip/flattr-icon.puml
!include ip/flattr.puml
!include ip/fleep.puml
!include ip/flexible-gs.puml
!include ip/flickr-icon.puml
!include ip/flickr.puml
!include ip/flight.puml
!include ip/flocker.puml
!include ip/floodio.puml
!include ip/flow.puml
!include ip/flowxo.puml
!include ip/floydhub.puml
!include ip/flutter.puml
!include ip/flux.puml
!include ip/fluxxor.puml
!include ip/fly-icon.puml
!include ip/fly.puml
!include ip/flyjs.puml
!include ip/fogbugz-icon.puml
!include ip/fogbugz.puml
!include ip/fomo-icon.puml
!include ip/fomo.puml
!include ip/font-awesome.puml
!include ip/forest.puml
!include ip/forestadmin-icon.puml
!include ip/forestadmin.puml
!include ip/forever.puml
!include ip/formkeep.puml
!include ip/fortran.puml
!include ip/foundation.puml
!include ip/foundationdb-icon.puml
!include ip/foundationdb.puml
!include ip/framer.puml
!include ip/framework7-icon.puml
!include ip/framework7.puml
!include ip/freebsd.puml
!include ip/freedcamp-icon.puml
!include ip/freedcamp.puml
!include ip/freedomdefined.puml
!include ip/fresh.puml
!include ip/frontapp.puml
!include ip/fsharp.puml
!include ip/fuchsia.puml
!include ip/galliumos.puml
!include ip/game-analytics-icon.puml
!include ip/game-analytics.puml
!include ip/ganache-icon.puml
!include ip/ganache.puml
!include ip/gatsby.puml
!include ip/gaugeio.puml
!include ip/geekbot.puml
!include ip/geetest-icon.puml
!include ip/geetest.puml
!include ip/gentoo.puml
!include ip/get-satisfaction.puml
!include ip/getyourguide.puml
!include ip/ghost.puml
!include ip/giantswarm.puml
!include ip/gin.puml
!include ip/git-icon.puml
!include ip/git.puml
!include ip/gitboard.puml
!include ip/github-actions.puml
!include ip/github-copilot.puml
!include ip/github-icon.puml
!include ip/github-octocat.puml
!include ip/github.puml
!include ip/gitkraken.puml
!include ip/gitlab.puml
!include ip/gitter.puml
!include ip/gitup.puml
!include ip/glamorous-icon.puml
!include ip/glamorous.puml
!include ip/gleam.puml
!include ip/glimmerjs.puml
!include ip/glint.puml
!include ip/glitch-icon.puml
!include ip/glitch.puml
!include ip/gnome-icon.puml
!include ip/gnome.puml
!include ip/gnu-net.puml
!include ip/gnu.puml
!include ip/gnupg-icon.puml
!include ip/gnupg.puml
!include ip/go.puml
!include ip/gocd.puml
!include ip/godot-icon.puml
!include ip/godot.puml
!include ip/gohorse.puml
!include ip/goland.puml
!include ip/gomix.puml
!include ip/google-2014.puml
!include ip/google-360suite.puml
!include ip/google-admob.puml
!include ip/google-ads.puml
!include ip/google-adsense.puml
!include ip/google-adwords.puml
!include ip/google-analytics.puml
!include ip/google-calendar.puml
!include ip/google-cloud-functions.puml
!include ip/google-cloud-platform.puml
!include ip/google-cloud-run.puml
!include ip/google-cloud.puml
!include ip/google-currents.puml
!include ip/google-data-studio.puml
!include ip/google-developers-icon.puml
!include ip/google-developers.puml
!include ip/google-domains-icon.puml
!include ip/google-domains.puml
!include ip/google-drive.puml
!include ip/google-fit.puml
!include ip/google-gmail.puml
!include ip/google-gsuite.puml
!include ip/google-home.puml
!include ip/google-icon.puml
!include ip/google-inbox.puml
!include ip/google-keep.puml
!include ip/google-maps.puml
!include ip/google-marketing-platform.puml
!include ip/google-meet.puml
!include ip/google-one.puml
!include ip/google-optimize.puml
!include ip/google-pay-icon.puml
!include ip/google-pay.puml
!include ip/google-photos.puml
!include ip/google-play-icon.puml
!include ip/google-play.puml
!include ip/google-plus.puml
!include ip/google-search-console.puml
!include ip/google-tag-manager.puml
!include ip/google-wallet.puml
!include ip/google-workspace.puml
!include ip/google.puml
!include ip/gopher.puml
!include ip/gordon.puml
!include ip/gradle.puml
!include ip/grafana.puml
!include ip/grails.puml
!include ip/grammarly-icon.puml
!include ip/grammarly.puml
!include ip/grape.puml
!include ip/graphcool.puml
!include ip/graphene.puml
!include ip/graphql.puml
!include ip/gratipay.puml
!include ip/grav.puml
!include ip/gravatar-icon.puml
!include ip/gravatar.puml
!include ip/graylog-icon.puml
!include ip/graylog.puml
!include ip/greensock-icon.puml
!include ip/greensock.puml
!include ip/gridsome-icon.puml
!include ip/gridsome.puml
!include ip/grommet.puml
!include ip/groovehq.puml
!include ip/grove.puml
!include ip/growth-book-icon.puml
!include ip/growth-book.puml
!include ip/grpc.puml
!include ip/grunt.puml
!include ip/gulp.puml
!include ip/gunicorn.puml
!include ip/gunjs.puml
!include ip/gusto.puml
!include ip/gwt.puml
!include ip/hack.puml
!include ip/hacker-one.puml
!include ip/hadoop.puml
!include ip/haiku-icon.puml
!include ip/haiku.puml
!include ip/haml.puml
!include ip/hanami.puml
!include ip/handlebars.puml
!include ip/hapi.puml
!include ip/hardhat-icon.puml
!include ip/hardhat.puml
!include ip/harness-icon.puml
!include ip/harness.puml
!include ip/harrow.puml
!include ip/hashicorp-icon.puml
!include ip/hashicorp.puml
!include ip/hashnode-icon.puml
!include ip/hashnode.puml
!include ip/haskell-icon.puml
!include ip/haskell.puml
!include ip/hasura-icon.puml
!include ip/hasura.puml
!include ip/haxe.puml
!include ip/haxl.puml
!include ip/hbase.puml
!include ip/hcaptcha-icon.puml
!include ip/hcaptcha.puml
!include ip/headlessui-icon.puml
!include ip/headlessui.puml
!include ip/heap-icon.puml
!include ip/heap.puml
!include ip/helm.puml
!include ip/helpscout-icon.puml
!include ip/helpscout.puml
!include ip/hermes.puml
!include ip/heroku-icon.puml
!include ip/heroku-redis.puml
!include ip/heroku.puml
!include ip/heron.puml
!include ip/hexo.puml
!include ip/hhvm.puml
!include ip/hibernate.puml
!include ip/highcharts.puml
!include ip/hipercard.puml
!include ip/hoa.puml
!include ip/homebrew.puml
!include ip/hoodie.puml
!include ip/hookstate.puml
!include ip/hootsuite-icon.puml
!include ip/hootsuite.puml
!include ip/horizon.puml
!include ip/hosted-graphite.puml
!include ip/hostgator-icon.puml
!include ip/hostgator.puml
!include ip/hotjar-icon.puml
!include ip/hotjar.puml
!include ip/houndci.puml
!include ip/html-5.puml
!include ip/html5-boilerplate.puml
!include ip/httpie-icon.puml
!include ip/httpie.puml
!include ip/hubspot.puml
!include ip/huggy.puml
!include ip/hugo.puml
!include ip/humongous.puml
!include ip/hyper.puml
!include ip/hyperapp.puml
!include ip/ibm.puml
!include ip/ieee.puml
!include ip/ietf.puml
!include ip/ifttt.puml
!include ip/imagemin.puml
!include ip/imba-icon.puml
!include ip/imba.puml
!include ip/immer-icon.puml
!include ip/immer.puml
!include ip/immutable.puml
!include ip/impala.puml
!include ip/importio.puml
!include ip/incident-icon.puml
!include ip/incident.puml
!include ip/infer.puml
!include ip/inferno.puml
!include ip/influxdb-icon.puml
!include ip/influxdb.puml
!include ip/ink.puml
!include ip/insomnia.puml
!include ip/instagram-icon.puml
!include ip/instagram.puml
!include ip/intel.puml
!include ip/intellij-idea.puml
!include ip/intercom-icon.puml
!include ip/intercom.puml
!include ip/internetexplorer.puml
!include ip/invision-icon.puml
!include ip/invision.puml
!include ip/io.puml
!include ip/ionic-icon.puml
!include ip/ionic.puml
!include ip/ios.puml
!include ip/iron-icon.puml
!include ip/iron.puml
!include ip/itsalive-icon.puml
!include ip/itsalive.puml
!include ip/jade.puml
!include ip/jaeger.puml
!include ip/jamstack-icon.puml
!include ip/jamstack.puml
!include ip/jasmine.puml
!include ip/java.puml
!include ip/javascript.puml
!include ip/jcb.puml
!include ip/jekyll.puml
!include ip/jelastic-icon.puml
!include ip/jelastic.puml
!include ip/jenkins.puml
!include ip/jest.puml
!include ip/jetbrains-icon.puml
!include ip/jetbrains-space-icon.puml
!include ip/jetbrains-space.puml
!include ip/jetbrains.puml
!include ip/jfrog.puml
!include ip/jhipster-icon.puml
!include ip/jhipster.puml
!include ip/jira.puml
!include ip/joomla.puml
!include ip/jotai.puml
!include ip/jquery-mobile.puml
!include ip/jquery.puml
!include ip/jruby.puml
!include ip/jsbin.puml
!include ip/jsdelivr.puml
!include ip/jsdom.puml
!include ip/jsfiddle.puml
!include ip/json-ld.puml
!include ip/json.puml
!include ip/jspm.puml
!include ip/jss.puml
!include ip/juju.puml
!include ip/julia.puml
!include ip/jupyter.puml
!include ip/jwt-icon.puml
!include ip/jwt.puml
!include ip/kafka-icon.puml
!include ip/kafka.puml
!include ip/kaios.puml
!include ip/kali.puml
!include ip/kallithea.puml
!include ip/karma.puml
!include ip/katalon-icon.puml
!include ip/katalon.puml
!include ip/kde.puml
!include ip/keen.puml
!include ip/kemal.puml
!include ip/keycdn-icon.puml
!include ip/keycdn.puml
!include ip/keydb-icon.puml
!include ip/keydb.puml
!include ip/keystonejs.puml
!include ip/khan_academy-icon.puml
!include ip/khan_academy.puml
!include ip/kibana.puml
!include ip/kickstarter-icon.puml
!include ip/kickstarter.puml
!include ip/kinto-icon.puml
!include ip/kinto.puml
!include ip/kinvey.puml
!include ip/kirby-icon.puml
!include ip/kirby.puml
!include ip/kissmetrics.puml
!include ip/kitematic.puml
!include ip/kloudless.puml
!include ip/knex.puml
!include ip/knockout.puml
!include ip/koa.puml
!include ip/kong-icon.puml
!include ip/kong.puml
!include ip/kontena.puml
!include ip/kops.puml
!include ip/kore.puml
!include ip/koreio.puml
!include ip/kotlin-icon.puml
!include ip/kotlin.puml
!include ip/kraken.puml
!include ip/krakenjs.puml
!include ip/ktor-icon.puml
!include ip/ktor.puml
!include ip/kubernetes.puml
!include ip/kustomer.puml
!include ip/languagetool.puml
!include ip/laravel.puml
!include ip/lastfm.puml
!include ip/lateral-icon.puml
!include ip/lateral.puml
!include ip/launchdarkly-icon.puml
!include ip/launchdarkly.puml
!include ip/launchkit.puml
!include ip/launchrock.puml
!include ip/leafjet.puml
!include ip/leaflet.puml
!include ip/leankit-icon.puml
!include ip/leankit.puml
!include ip/lerna.puml
!include ip/less.puml
!include ip/lets-cloud.puml
!include ip/letsencrypt.puml
!include ip/leveldb.puml
!include ip/lexical-icon.puml
!include ip/lexical.puml
!include ip/librato.puml
!include ip/liftweb.puml
!include ip/lighthouse.puml
!include ip/lightstep-icon.puml
!include ip/lightstep.puml
!include ip/lighttpd.puml
!include ip/linear-icon.puml
!include ip/linear.puml
!include ip/linkedin-icon.puml
!include ip/linkedin.puml
!include ip/linkerd.puml
!include ip/linode.puml
!include ip/linux-mint.puml
!include ip/linux-tux.puml
!include ip/lit-icon.puml
!include ip/lit.puml
!include ip/litmus.puml
!include ip/loader.puml
!include ip/locent.puml
!include ip/lodash.puml
!include ip/logentries.puml
!include ip/loggly.puml
!include ip/logmatic.puml
!include ip/logstash.puml
!include ip/lookback.puml
!include ip/looker-icon.puml
!include ip/looker.puml
!include ip/loom-icon.puml
!include ip/loom.puml
!include ip/loopback-icon.puml
!include ip/loopback.puml
!include ip/losant.puml
!include ip/lua.puml
!include ip/lucene.net.puml
!include ip/lucene.puml
!include ip/lumen.puml
!include ip/lynda.puml
!include ip/macOS.puml
!include ip/madge.puml
!include ip/maestro.puml
!include ip/mageia.puml
!include ip/magento.puml
!include ip/magneto.puml
!include ip/mailchimp-freddie.puml
!include ip/mailchimp.puml
!include ip/maildeveloper.puml
!include ip/mailgun-icon.puml
!include ip/mailgun.puml
!include ip/mailjet-icon.puml
!include ip/mailjet.puml
!include ip/malinajs.puml
!include ip/mandrill-shield.puml
!include ip/mandrill.puml
!include ip/manifoldjs.puml
!include ip/manjaro.puml
!include ip/mantine-icon.puml
!include ip/mantine.puml
!include ip/mantl.puml
!include ip/manuscript.puml
!include ip/mapbox-icon.puml
!include ip/mapbox.puml
!include ip/maps-me.puml
!include ip/mapzen-icon.puml
!include ip/mapzen.puml
!include ip/mariadb-icon.puml
!include ip/mariadb.puml
!include ip/marionette.puml
!include ip/markdown.puml
!include ip/marko.puml
!include ip/marvel.puml
!include ip/mastercard.puml
!include ip/mastodon-icon.puml
!include ip/mastodon.puml
!include ip/material-ui.puml
!include ip/materializecss.puml
!include ip/matomo-icon.puml
!include ip/matomo.puml
!include ip/matplotlib-icon.puml
!include ip/matplotlib.puml
!include ip/matter-icon.puml
!include ip/matter.puml
!include ip/mattermost-icon.puml
!include ip/mattermost.puml
!include ip/mautic-icon.puml
!include ip/mautic.puml
!include ip/maven.puml
!include ip/maxcdn.puml
!include ip/mdn.puml
!include ip/mdx.puml
!include ip/medium-icon.puml
!include ip/medium.puml
!include ip/medusa-icon.puml
!include ip/medusa.puml
!include ip/meilisearch.puml
!include ip/memcached.puml
!include ip/memgraph.puml
!include ip/memsql-icon.puml
!include ip/memsql.puml
!include ip/mention.puml
!include ip/mercurial.puml
!include ip/mern.puml
!include ip/mesos.puml
!include ip/mesosphere.puml
!include ip/messenger.puml
!include ip/metabase.puml
!include ip/metamask-icon.puml
!include ip/metamask.puml
!include ip/meteor-icon.puml
!include ip/meteor.puml
!include ip/micro-icon.puml
!include ip/micro-python.puml
!include ip/micro.puml
!include ip/microcosm.puml
!include ip/micron-icon.puml
!include ip/micron.puml
!include ip/microsoft-azure.puml
!include ip/microsoft-edge.puml
!include ip/microsoft-icon.puml
!include ip/microsoft-onedrive.puml
!include ip/microsoft-power-bi.puml
!include ip/microsoft-teams.puml
!include ip/microsoft-windows-icon.puml
!include ip/microsoft-windows.puml
!include ip/microsoft.puml
!include ip/mida-icon.puml
!include ip/mida.puml
!include ip/middleman.puml
!include ip/mikrotik.puml
!include ip/milligram.puml
!include ip/mindsdb-icon.puml
!include ip/mindsdb.puml
!include ip/mint-lang.puml
!include ip/mint.puml
!include ip/mio.puml
!include ip/mist.puml
!include ip/mithril.puml
!include ip/mixmax.puml
!include ip/mixpanel.puml
!include ip/mlab.puml
!include ip/mobx.puml
!include ip/mocha.puml
!include ip/mock-server.puml
!include ip/mockflow-icon.puml
!include ip/mockflow.puml
!include ip/modernizr.puml
!include ip/modx-icon.puml
!include ip/modx.puml
!include ip/moltin-icon.puml
!include ip/moltin.puml
!include ip/momentjs.puml
!include ip/monday-icon.puml
!include ip/monday.puml
!include ip/monero.puml
!include ip/mongodb-icon.puml
!include ip/mongodb.puml
!include ip/mono.puml
!include ip/moon.puml
!include ip/mootools.puml
!include ip/morpheus-icon.puml
!include ip/morpheus.puml
!include ip/mozilla.puml
!include ip/mparticle-icon.puml
!include ip/mparticle.puml
!include ip/mps-icon.puml
!include ip/mps.puml
!include ip/msw-icon.puml
!include ip/msw.puml
!include ip/multipass.puml
!include ip/mysql-icon.puml
!include ip/mysql.puml
!include ip/myth.puml
!include ip/naiveui.puml
!include ip/namecheap.puml
!include ip/nanonets.puml
!include ip/nasm.puml
!include ip/nativescript.puml
!include ip/nats-icon.puml
!include ip/nats.puml
!include ip/neat.puml
!include ip/neo4j.puml
!include ip/neon-icon.puml
!include ip/neon.puml
!include ip/neonmetrics.puml
!include ip/neovim.puml
!include ip/nestjs.puml
!include ip/netbeans.puml
!include ip/netflix-icon.puml
!include ip/netflix.puml
!include ip/netlify-icon.puml
!include ip/netlify.puml
!include ip/netuitive.puml
!include ip/neverinstall-icon.puml
!include ip/neverinstall.puml
!include ip/new-relic-icon.puml
!include ip/new-relic.puml
!include ip/nextcloud.puml
!include ip/nextjs-icon.puml
!include ip/nextjs.puml
!include ip/nginx.puml
!include ip/nhost-icon.puml
!include ip/nhost.puml
!include ip/nightwatch.puml
!include ip/nim-lang.puml
!include ip/nocodb.puml
!include ip/nodal.puml
!include ip/node-sass.puml
!include ip/nodebots.puml
!include ip/nodejitsu.puml
!include ip/nodejs-icon-alt.puml
!include ip/nodejs-icon.puml
!include ip/nodejs.puml
!include ip/nodemon.puml
!include ip/nodeos.puml
!include ip/nodewebkit.puml
!include ip/nomad-icon.puml
!include ip/nomad.puml
!include ip/notion-icon.puml
!include ip/notion.puml
!include ip/now.puml
!include ip/noysi.puml
!include ip/npm-2.puml
!include ip/npm-icon.puml
!include ip/npm.puml
!include ip/nuclide.puml
!include ip/numpy.puml
!include ip/nuodb.puml
!include ip/nuxt-icon.puml
!include ip/nuxt.puml
!include ip/nvidia.puml
!include ip/nvm.puml
!include ip/nx.puml
!include ip/oauth.puml
!include ip/observablehq.puml
!include ip/ocaml.puml
!include ip/octodns.puml
!include ip/octopus-deploy.puml
!include ip/okta-icon.puml
!include ip/okta.puml
!include ip/olapic.puml
!include ip/olark.puml
!include ip/onesignal.puml
!include ip/opbeat.puml
!include ip/open-graph.puml
!include ip/open-zeppelin-icon.puml
!include ip/open-zeppelin.puml
!include ip/openai-icon.puml
!include ip/openai.puml
!include ip/openapi-icon.puml
!include ip/openapi.puml
!include ip/opencart.puml
!include ip/opencollective.puml
!include ip/opencv.puml
!include ip/openframeworks.puml
!include ip/opengl.puml
!include ip/openjs-foundation-icon.puml
!include ip/openjs-foundation.puml
!include ip/openlayers.puml
!include ip/openshift.puml
!include ip/opensource.puml
!include ip/openstack-icon.puml
!include ip/openstack.puml
!include ip/opentelemetry-icon.puml
!include ip/opentelemetry.puml
!include ip/opera.puml
!include ip/opsee.puml
!include ip/opsgenie.puml
!include ip/optimizely-icon.puml
!include ip/optimizely.puml
!include ip/oracle.puml
!include ip/oreilly.puml
!include ip/origami.puml
!include ip/origin.puml
!include ip/oshw.puml
!include ip/osquery.puml
!include ip/otto.puml
!include ip/overloop-icon.puml
!include ip/overloop.puml
!include ip/p5js.puml
!include ip/packer.puml
!include ip/pagekit.puml
!include ip/pagekite.puml
!include ip/pagerduty-icon.puml
!include ip/pagerduty.puml
!include ip/panda.puml
!include ip/pandas-icon.puml
!include ip/pandas.puml
!include ip/parcel-icon.puml
!include ip/parcel.puml
!include ip/parse.puml
!include ip/parsehub.puml
!include ip/partytown-icon.puml
!include ip/partytown.puml
!include ip/passbolt-icon.puml
!include ip/passbolt.puml
!include ip/passport.puml
!include ip/patreon.puml
!include ip/payload.puml
!include ip/paypal.puml
!include ip/peer5.puml
!include ip/pepperoni.puml
!include ip/percona.puml
!include ip/percy-icon.puml
!include ip/percy.puml
!include ip/perf-rocks.puml
!include ip/periscope.puml
!include ip/perl.puml
!include ip/phalcon.puml
!include ip/phoenix.puml
!include ip/phonegap-bot.puml
!include ip/phonegap.puml
!include ip/php-alt.puml
!include ip/php.puml
!include ip/phpstorm.puml
!include ip/picasa.puml
!include ip/pinecone-icon.puml
!include ip/pinecone.puml
!include ip/pingdom.puml
!include ip/pingy.puml
!include ip/pinia.puml
!include ip/pinterest.puml
!include ip/pipedream.puml
!include ip/pipedrive.puml
!include ip/pipefy.puml
!include ip/pivotal_tracker.puml
!include ip/pixate.puml
!include ip/pixijs.puml
!include ip/pkg.puml
!include ip/planetscale.puml
!include ip/planless-icon.puml
!include ip/planless.puml
!include ip/plasmic.puml
!include ip/plastic-scm.puml
!include ip/platformio.puml
!include ip/play.puml
!include ip/playwright.puml
!include ip/pluralsight-icon.puml
!include ip/pluralsight.puml
!include ip/pm2-icon.puml
!include ip/pm2.puml
!include ip/pnpm.puml
!include ip/pocket-base.puml
!include ip/podio.puml
!include ip/poeditor.puml
!include ip/polymer.puml
!include ip/positionly.puml
!include ip/postcss.puml
!include ip/postgraphile.puml
!include ip/postgresql.puml
!include ip/posthog-icon.puml
!include ip/posthog.puml
!include ip/postman-icon.puml
!include ip/postman.puml
!include ip/pouchdb.puml
!include ip/preact.puml
!include ip/precursor.puml
!include ip/prerender-icon.puml
!include ip/prerender.puml
!include ip/prestashop.puml
!include ip/presto.puml
!include ip/prettier.puml
!include ip/prisma.puml
!include ip/prismic-icon.puml
!include ip/prismic.puml
!include ip/processing.puml
!include ip/processwire-icon.puml
!include ip/processwire.puml
!include ip/productboard-icon.puml
!include ip/productboard.puml
!include ip/producthunt.puml
!include ip/progress.puml
!include ip/prometheus.puml
!include ip/promises.puml
!include ip/proofy.puml
!include ip/prospect.puml
!include ip/protactor.puml
!include ip/protoio.puml
!include ip/protonet.puml
!include ip/protractor.puml
!include ip/prott.puml
!include ip/pug.puml
!include ip/pumpkindb.puml
!include ip/puppet-icon.puml
!include ip/puppet.puml
!include ip/puppeteer.puml
!include ip/puppy-linux.puml
!include ip/purescript-icon.puml
!include ip/purescript.puml
!include ip/pushbullet.puml
!include ip/pusher-icon.puml
!include ip/pusher.puml
!include ip/pwa.puml
!include ip/pycharm.puml
!include ip/pypi.puml
!include ip/pyscript.puml
!include ip/python.puml
!include ip/pytorch-icon.puml
!include ip/pytorch.puml
!include ip/pyup.puml
!include ip/q.puml
!include ip/qlik.puml
!include ip/qordoba.puml
!include ip/qt.puml
!include ip/qualcomm.puml
!include ip/quarkus-icon.puml
!include ip/quarkus.puml
!include ip/quay.puml
!include ip/quobyte.puml
!include ip/quora.puml
!include ip/qwik-icon.puml
!include ip/qwik.puml
!include ip/r-lang.puml
!include ip/rabbitmq-icon.puml
!include ip/rabbitmq.puml
!include ip/rackspace-icon.puml
!include ip/rackspace.puml
!include ip/rails.puml
!include ip/ramda.puml
!include ip/raml.puml
!include ip/rancher-icon.puml
!include ip/rancher.puml
!include ip/raphael.puml
!include ip/raspberry-pi.puml
!include ip/rax.puml
!include ip/react-query-icon.puml
!include ip/react-query.puml
!include ip/react-router.puml
!include ip/react-spring.puml
!include ip/react-styleguidist.puml
!include ip/react.puml
!include ip/reactivex.puml
!include ip/realm.puml
!include ip/reapp.puml
!include ip/reasonml-icon.puml
!include ip/reasonml.puml
!include ip/recaptcha.puml
!include ip/recast.ai.puml
!include ip/recoil-icon.puml
!include ip/recoil.puml
!include ip/reddit-icon.puml
!include ip/reddit.puml
!include ip/redhat-icon.puml
!include ip/redhat.puml
!include ip/redis.puml
!include ip/redsmin.puml
!include ip/redspread.puml
!include ip/redux-observable.puml
!include ip/redux-saga.puml
!include ip/redux.puml
!include ip/redwoodjs.puml
!include ip/refactor.puml
!include ip/reindex.puml
!include ip/relay.puml
!include ip/release.puml
!include ip/remergr.puml
!include ip/remix-icon.puml
!include ip/remix.puml
!include ip/renovatebot.puml
!include ip/replit-icon.puml
!include ip/replit.puml
!include ip/require.puml
!include ip/rescript-icon.puml
!include ip/rescript.puml
!include ip/rest-li.puml
!include ip/rest.puml
!include ip/rethinkdb.puml
!include ip/retool-icon.puml
!include ip/retool.puml
!include ip/riak.puml
!include ip/rider.puml
!include ip/riot.puml
!include ip/risingwave-icon.puml
!include ip/risingwave.puml
!include ip/rkt.puml
!include ip/rocket-chat-icon.puml
!include ip/rocket-chat.puml
!include ip/rocksdb.puml
!include ip/rocky-linux-icon.puml
!include ip/rocky-linux.puml
!include ip/rocky.puml
!include ip/rollbar-icon.puml
!include ip/rollbar.puml
!include ip/rollup.puml
!include ip/rollupjs.puml
!include ip/rome-icon.puml
!include ip/rome.puml
!include ip/ros.puml
!include ip/rsa.puml
!include ip/rsmq.puml
!include ip/rubocop.puml
!include ip/ruby.puml
!include ip/rubygems.puml
!include ip/rubymine.puml
!include ip/rum.puml
!include ip/run-above.puml
!include ip/runnable.puml
!include ip/runscope.puml
!include ip/rush-icon.puml
!include ip/rush.puml
!include ip/rust.puml
!include ip/rxdb.puml
!include ip/safari.puml
!include ip/sagui.puml
!include ip/sails.puml
!include ip/salesforce.puml
!include ip/saltstack.puml
!include ip/sameroom.puml
!include ip/samsung.puml
!include ip/sanity.puml
!include ip/sap.puml
!include ip/sass-doc.puml
!include ip/sass.puml
!include ip/saucelabs.puml
!include ip/scala.puml
!include ip/scaledrone.puml
!include ip/scaphold.puml
!include ip/scribd-icon.puml
!include ip/scribd.puml
!include ip/seaborn-icon.puml
!include ip/seaborn.puml
!include ip/section-icon.puml
!include ip/section.puml
!include ip/sectionio.puml
!include ip/segment-icon.puml
!include ip/segment.puml
!include ip/selenium.puml
!include ip/semantic-release.puml
!include ip/semantic-ui.puml
!include ip/semantic-web.puml
!include ip/semaphore.puml
!include ip/semaphoreci.puml
!include ip/sencha.puml
!include ip/sendgrid-icon.puml
!include ip/sendgrid.puml
!include ip/seneca.puml
!include ip/sensu-icon.puml
!include ip/sensu.puml
!include ip/sentry-icon.puml
!include ip/sentry.puml
!include ip/sequelize.puml
!include ip/serveless.puml
!include ip/serverless.puml
!include ip/sherlock-icon.puml
!include ip/sherlock.puml
!include ip/shields.puml
!include ip/shipit.puml
!include ip/shippable.puml
!include ip/shogun.puml
!include ip/shopify.puml
!include ip/sidekick.puml
!include ip/sidekiq-icon.puml
!include ip/sidekiq.puml
!include ip/signal.puml
!include ip/sigstore-icon.puml
!include ip/sigstore.puml
!include ip/sinatra.puml
!include ip/singlestore-icon.puml
!include ip/singlestore.puml
!include ip/siphon.puml
!include ip/sitepoint.puml
!include ip/sk-hynix.puml
!include ip/skaffolder.puml
!include ip/sketch.puml
!include ip/sketchapp.puml
!include ip/skylight.puml
!include ip/skype.puml
!include ip/slack-icon.puml
!include ip/slack.puml
!include ip/slides.puml
!include ip/slim.puml
!include ip/smartling.puml
!include ip/smashingmagazine.puml
!include ip/snap-svg.puml
!include ip/snaplet-icon.puml
!include ip/snaplet.puml
!include ip/sninnaker.puml
!include ip/snowflake-icon.puml
!include ip/snowflake.puml
!include ip/snowpack.puml
!include ip/snupps.puml
!include ip/snyk.puml
!include ip/socket.io.puml
!include ip/solarwinds.puml
!include ip/solid.puml
!include ip/solidity.puml
!include ip/solidjs-icon.puml
!include ip/solidjs.puml
!include ip/solr.puml
!include ip/sonarcloud-icon.puml
!include ip/sonarcloud.puml
!include ip/sonarlint-icon.puml
!include ip/sonarlint.puml
!include ip/sonarqube.puml
!include ip/soundcloud.puml
!include ip/sourcegraph.puml
!include ip/sourcetrail.puml
!include ip/sourcetree.puml
!include ip/spark.puml
!include ip/sparkcentral.puml
!include ip/sparkpost.puml
!include ip/speakerdeck.puml
!include ip/speedcurve.puml
!include ip/spidermonkey-icon.puml
!include ip/spidermonkey.puml
!include ip/spinnaker.puml
!include ip/splunk.puml
!include ip/spotify-icon.puml
!include ip/spotify.puml
!include ip/spree.puml
!include ip/spring-icon.puml
!include ip/spring.puml
!include ip/sqldep.puml
!include ip/sqlite.puml
!include ip/square.puml
!include ip/squarespace.puml
!include ip/stackbit-icon.puml
!include ip/stackbit.puml
!include ip/stackblitz-icon.puml
!include ip/stackblitz.puml
!include ip/stackoverflow-icon.puml
!include ip/stackoverflow.puml
!include ip/stackshare.puml
!include ip/stacksmith.puml
!include ip/stately-icon.puml
!include ip/stately.puml
!include ip/statuspage.puml
!include ip/stdlib-icon.puml
!include ip/stdlib.puml
!include ip/steam.puml
!include ip/stenciljs-icon.puml
!include ip/stenciljs.puml
!include ip/stepsize-icon.puml
!include ip/stepsize.puml
!include ip/steroids.puml
!include ip/stetho.puml
!include ip/stickermule.puml
!include ip/stigg-icon.puml
!include ip/stigg.puml
!include ip/stimulus-icon.puml
!include ip/stimulus.puml
!include ip/stitch.puml
!include ip/stoplight.puml
!include ip/stormpath.puml
!include ip/storyblocks-icon.puml
!include ip/storyblocks.puml
!include ip/storyblok-icon.puml
!include ip/storyblok.puml
!include ip/storybook-icon.puml
!include ip/storybook.puml
!include ip/strapi-icon.puml
!include ip/strapi.puml
!include ip/streamlit.puml
!include ip/strider.puml
!include ip/stripe.puml
!include ip/struts.puml
!include ip/styleci.puml
!include ip/stylefmt.puml
!include ip/stylelint.puml
!include ip/stylis.puml
!include ip/stylus.puml
!include ip/stytch.puml
!include ip/sublimetext-icon.puml
!include ip/sublimetext.puml
!include ip/subversion.puml
!include ip/sugarss.puml
!include ip/supabase-icon.puml
!include ip/supabase.puml
!include ip/supergiant.puml
!include ip/supersonic.puml
!include ip/supertokens-icon.puml
!include ip/supertokens.puml
!include ip/supportkit.puml
!include ip/surge.puml
!include ip/surrealdb-icon.puml
!include ip/surrealdb.puml
!include ip/survicate-icon.puml
!include ip/survicate.puml
!include ip/suse.puml
!include ip/susy.puml
!include ip/svelte-icon.puml
!include ip/svelte-kit.puml
!include ip/svelte.puml
!include ip/svg.puml
!include ip/svgator.puml
!include ip/swagger.puml
!include ip/swc.puml
!include ip/swift.puml
!include ip/swiftype.puml
!include ip/swimm.puml
!include ip/swr.puml
!include ip/symfony.puml
!include ip/sysdig-icon.puml
!include ip/sysdig.puml
!include ip/t3.puml
!include ip/tableau-icon.puml
!include ip/tableau.puml
!include ip/taiga.puml
!include ip/tailwindcss-icon.puml
!include ip/tailwindcss.puml
!include ip/tapcart-icon.puml
!include ip/tapcart.puml
!include ip/targetprocess.puml
!include ip/taskade-icon.puml
!include ip/taskade.puml
!include ip/tastejs.puml
!include ip/tauri.puml
!include ip/tealium.puml
!include ip/teamcity.puml
!include ip/teamgrid.puml
!include ip/teamwork-icon.puml
!include ip/teamwork.puml
!include ip/tectonic.puml
!include ip/telegram.puml
!include ip/tensorflow.puml
!include ip/terminal.puml
!include ip/terraform-icon.puml
!include ip/terraform.puml
!include ip/terser-icon.puml
!include ip/terser.puml
!include ip/testcafe.puml
!include ip/testing-library.puml
!include ip/testlodge.puml
!include ip/testmunk.puml
!include ip/thimble.puml
!include ip/threejs.puml
!include ip/thymeleaf-icon.puml
!include ip/thymeleaf.puml
!include ip/tidal-icon.puml
!include ip/tidal.puml
!include ip/tiktok-icon.puml
!include ip/tiktok.puml
!include ip/titon.puml
!include ip/tnw.puml
!include ip/todoist-icon.puml
!include ip/todoist.puml
!include ip/todomvc.puml
!include ip/tomcat.puml
!include ip/toml.puml
!include ip/tor-browser.puml
!include ip/tor.puml
!include ip/torus.puml
!include ip/traackr.puml
!include ip/trac.puml
!include ip/travis-ci-monochrome.puml
!include ip/travis-ci.puml
!include ip/treasuredata-icon.puml
!include ip/treasuredata.puml
!include ip/treehouse.puml
!include ip/trello.puml
!include ip/trpc.puml
!include ip/truffle-icon.puml
!include ip/truffle.puml
!include ip/tsmc.puml
!include ip/tsnode.puml
!include ip/tsu.puml
!include ip/tsuru.puml
!include ip/tumblr-icon.puml
!include ip/tumblr.puml
!include ip/tunein.puml
!include ip/tuple.puml
!include ip/turbopack-icon.puml
!include ip/turbopack.puml
!include ip/turborepo-icon.puml
!include ip/turborepo.puml
!include ip/turret.puml
!include ip/tutsplus.puml
!include ip/tutum.puml
!include ip/tux.puml
!include ip/twilio-icon.puml
!include ip/twilio.puml
!include ip/twitch.puml
!include ip/twitter.puml
!include ip/typeform-icon.puml
!include ip/typeform.puml
!include ip/typeorm.puml
!include ip/typescript-icon-round.puml
!include ip/typescript-icon.puml
!include ip/typescript.puml
!include ip/typo3-icon.puml
!include ip/typo3.puml
!include ip/ubuntu.puml
!include ip/udacity-icon.puml
!include ip/udacity.puml
!include ip/udemy-icon.puml
!include ip/udemy.puml
!include ip/uikit.puml
!include ip/umu.puml
!include ip/unbounce-icon.puml
!include ip/unbounce.puml
!include ip/undertow.puml
!include ip/unionpay.puml
!include ip/unitjs.puml
!include ip/unito-icon.puml
!include ip/unito.puml
!include ip/unity.puml
!include ip/unocss.puml
!include ip/unrealengine-icon.puml
!include ip/unrealengine.puml
!include ip/upcase.puml
!include ip/upstash-icon.puml
!include ip/upstash.puml
!include ip/upwork.puml
!include ip/user-testing-icon.puml
!include ip/user-testing.puml
!include ip/uservoice-icon.puml
!include ip/uservoice.puml
!include ip/uwsgi.puml
!include ip/v8-ignition.puml
!include ip/v8-turbofan.puml
!include ip/v8.puml
!include ip/vaadin.puml
!include ip/vaddy.puml
!include ip/vagrant-icon.puml
!include ip/vagrant.puml
!include ip/vault-icon.puml
!include ip/vault.puml
!include ip/vector-timber.puml
!include ip/vector.puml
!include ip/vercel-icon.puml
!include ip/vercel.puml
!include ip/verdaccio-icon.puml
!include ip/verdaccio.puml
!include ip/vernemq.puml
!include ip/victorops.puml
!include ip/vim.puml
!include ip/vimeo-icon.puml
!include ip/vimeo.puml
!include ip/vine.puml
!include ip/visa.puml
!include ip/visaelectron.puml
!include ip/visual-studio-code.puml
!include ip/visual-studio.puml
!include ip/visual_website_optimizer.puml
!include ip/vitejs.puml
!include ip/vitess.puml
!include ip/vitest.puml
!include ip/vivaldi-icon.puml
!include ip/vivaldi.puml
!include ip/vlang.puml
!include ip/void.puml
!include ip/vue.puml
!include ip/vuetifyjs.puml
!include ip/vueuse.puml
!include ip/vulkan.puml
!include ip/vultr-icon.puml
!include ip/vultr.puml
!include ip/vwo.puml
!include ip/w3c.puml
!include ip/waffle-icon.puml
!include ip/waffle.puml
!include ip/wagtail.puml
!include ip/wakatime.puml
!include ip/walkme.puml
!include ip/watchman.puml
!include ip/waypoint-icon.puml
!include ip/waypoint.puml
!include ip/wayscript-icon.puml
!include ip/wayscript.puml
!include ip/wearos.puml
!include ip/weave.puml
!include ip/web-fundamentals.puml
!include ip/web.dev-icon.puml
!include ip/web.dev.puml
!include ip/web3js.puml
!include ip/webassembly.puml
!include ip/webcomponents.puml
!include ip/webdriverio.puml
!include ip/webflow.puml
!include ip/webhint-icon.puml
!include ip/webhint.puml
!include ip/webhooks.puml
!include ip/webix-icon.puml
!include ip/webix.puml
!include ip/webkit.puml
!include ip/webmin.puml
!include ip/webpack.puml
!include ip/webplatform.puml
!include ip/webrtc.puml
!include ip/websocket.puml
!include ip/webstorm.puml
!include ip/webtask.puml
!include ip/webtorrent.puml
!include ip/weebly.puml
!include ip/wercker.puml
!include ip/whalar-icon.puml
!include ip/whalar.puml
!include ip/whatsapp-icon.puml
!include ip/whatsapp-monochrome-icon.puml
!include ip/whatsapp.puml
!include ip/whatwg.puml
!include ip/wicket-icon.puml
!include ip/wicket.puml
!include ip/wifi.puml
!include ip/wildfly.puml
!include ip/windi-css.puml
!include ip/windows.puml
!include ip/wire.puml
!include ip/wiredtree.puml
!include ip/wix.puml
!include ip/wmr.puml
!include ip/woocommerce-icon.puml
!include ip/woocommerce.puml
!include ip/woopra.puml
!include ip/wordpress-icon-alt.puml
!include ip/wordpress-icon.puml
!include ip/wordpress.puml
!include ip/workboard.puml
!include ip/workos-icon.puml
!include ip/workos.puml
!include ip/workplace-icon.puml
!include ip/workplace.puml
!include ip/wpengine.puml
!include ip/wufoo.puml
!include ip/x-ray-goggles.puml
!include ip/xamarin.puml
!include ip/xampp.puml
!include ip/xata-icon.puml
!include ip/xata.puml
!include ip/xcart.puml
!include ip/xero.puml
!include ip/xplenty.puml
!include ip/xray-for-jira.puml
!include ip/xstate.puml
!include ip/xtend.puml
!include ip/xwiki-icon.puml
!include ip/xwiki.puml
!include ip/yahoo.puml
!include ip/yaml.puml
!include ip/yammer.puml
!include ip/yandex-ru.puml
!include ip/yarn.puml
!include ip/ycombinator.puml
!include ip/yeoman.puml
!include ip/yii.puml
!include ip/youtrack.puml
!include ip/youtube-icon.puml
!include ip/youtube.puml
!include ip/yugabyte-icon.puml
!include ip/yugabyte.puml
!include ip/zabbix.puml
!include ip/zapier-icon.puml
!include ip/zapier.puml
!include ip/zeit-icon.puml
!include ip/zeit.puml
!include ip/zend-framework.puml
!include ip/zendesk-icon.puml
!include ip/zendesk.puml
!include ip/zenhub-icon.puml
!include ip/zenhub.puml
!include ip/zeplin.puml
!include ip/zeroheight-icon.puml
!include ip/zeroheight.puml
!include ip/zest.puml
!include ip/zig.puml
!include ip/zigbee.puml
!include ip/zoho.puml
!include ip/zoom-icon.puml
!include ip/zoom.puml
!include ip/zorin-os.puml
!include ip/zube.puml
!include ip/zulip-icon.puml
!include ip/zulip.puml
!include ip/zwave.puml

listsprites

@enduml
