@startuml
!$rootPath = ..
!define ip $rootPath/plantuml-stdlib/material

!include ip/access_point.puml
!include ip/access_point_network.puml
!include ip/account.puml
!include ip/account_alert.puml
!include ip/account_box.puml
!include ip/account_box_outline.puml
!include ip/account_card_details.puml
!include ip/account_check.puml
!include ip/account_circle.puml
!include ip/account_convert.puml
!include ip/account_edit.puml
!include ip/account_key.puml
!include ip/account_location.puml
!include ip/account_minus.puml
!include ip/account_multiple.puml
!include ip/account_multiple_minus.puml
!include ip/account_multiple_outline.puml
!include ip/account_multiple_plus.puml
!include ip/account_multiple_plus_outline.puml
!include ip/account_network.puml
!include ip/account_off.puml
!include ip/account_outline.puml
!include ip/account_plus.puml
!include ip/account_plus_outline.puml
!include ip/account_remove.puml
!include ip/account_search.puml
!include ip/account_settings.puml
!include ip/account_settings_variant.puml
!include ip/account_switch.puml
!include ip/adjust.puml
!include ip/air_conditioner.puml
!include ip/airballoon.puml
!include ip/airplane.puml
!include ip/airplane_landing.puml
!include ip/airplane_off.puml
!include ip/airplane_takeoff.puml
!include ip/airplay.puml
!include ip/alarm.puml
!include ip/alarm_bell.puml
!include ip/alarm_check.puml
!include ip/alarm_light.puml
!include ip/alarm_multiple.puml
!include ip/alarm_off.puml
!include ip/alarm_plus.puml
!include ip/alarm_snooze.puml
!include ip/album.puml
!include ip/alert.puml
!include ip/alert_box.puml
!include ip/alert_circle.puml
!include ip/alert_circle_outline.puml
!include ip/alert_decagram.puml
!include ip/alert_octagon.puml
!include ip/alert_octagram.puml
!include ip/alert_outline.puml
!include ip/all_inclusive.puml
!include ip/allo.puml
!include ip/alpha.puml
!include ip/alphabetical.puml
!include ip/altimeter.puml
!include ip/amazon.puml
!include ip/amazon_clouddrive.puml
!include ip/ambulance.puml
!include ip/amplifier.puml
!include ip/anchor.puml
!include ip/android.puml
!include ip/android_debug_bridge.puml
!include ip/android_head.puml
!include ip/android_studio.puml
!include ip/angular.puml
!include ip/angularjs.puml
!include ip/animation.puml
!include ip/apple.puml
!include ip/apple_finder.puml
!include ip/apple_ios.puml
!include ip/apple_keyboard_caps.puml
!include ip/apple_keyboard_command.puml
!include ip/apple_keyboard_control.puml
!include ip/apple_keyboard_option.puml
!include ip/apple_keyboard_shift.puml
!include ip/apple_mobileme.puml
!include ip/apple_safari.puml
!include ip/application.puml
!include ip/appnet.puml
!include ip/approval.puml
!include ip/apps.puml
!include ip/archive.puml
!include ip/arrange_bring_forward.puml
!include ip/arrange_bring_to_front.puml
!include ip/arrange_send_backward.puml
!include ip/arrange_send_to_back.puml
!include ip/arrow_all.puml
!include ip/arrow_bottom_left.puml
!include ip/arrow_bottom_right.puml
!include ip/arrow_collapse.puml
!include ip/arrow_collapse_all.puml
!include ip/arrow_collapse_down.puml
!include ip/arrow_collapse_left.puml
!include ip/arrow_collapse_right.puml
!include ip/arrow_collapse_up.puml
!include ip/arrow_down.puml
!include ip/arrow_down_bold.puml
!include ip/arrow_down_bold_box.puml
!include ip/arrow_down_bold_box_outline.puml
!include ip/arrow_down_bold_circle.puml
!include ip/arrow_down_bold_circle_outline.puml
!include ip/arrow_down_bold_hexagon_outline.puml
!include ip/arrow_down_box.puml
!include ip/arrow_down_drop.puml
!include ip/arrow_down_drop_circle.puml
!include ip/arrow_down_drop_circle_outline.puml
!include ip/arrow_down_thick.puml
!include ip/arrow_expand.puml
!include ip/arrow_expand_all.puml
!include ip/arrow_expand_down.puml
!include ip/arrow_expand_left.puml
!include ip/arrow_expand_right.puml
!include ip/arrow_expand_up.puml
!include ip/arrow_left.puml
!include ip/arrow_left_bold.puml
!include ip/arrow_left_bold_box.puml
!include ip/arrow_left_bold_box_outline.puml
!include ip/arrow_left_bold_circle.puml
!include ip/arrow_left_bold_circle_outline.puml
!include ip/arrow_left_bold_hexagon_outline.puml
!include ip/arrow_left_box.puml
!include ip/arrow_left_drop_circle.puml
!include ip/arrow_left_drop_circle_outline.puml
!include ip/arrow_left_thick.puml
!include ip/arrow_right.puml
!include ip/arrow_right_bold.puml
!include ip/arrow_right_bold_box.puml
!include ip/arrow_right_bold_box_outline.puml
!include ip/arrow_right_bold_circle.puml
!include ip/arrow_right_bold_circle_outline.puml
!include ip/arrow_right_bold_hexagon_outline.puml
!include ip/arrow_right_box.puml
!include ip/arrow_right_drop_circle.puml
!include ip/arrow_right_drop_circle_outline.puml
!include ip/arrow_right_thick.puml
!include ip/arrow_top_left.puml
!include ip/arrow_top_right.puml
!include ip/arrow_up.puml
!include ip/arrow_up_bold.puml
!include ip/arrow_up_bold_box.puml
!include ip/arrow_up_bold_box_outline.puml
!include ip/arrow_up_bold_circle.puml
!include ip/arrow_up_bold_circle_outline.puml
!include ip/arrow_up_bold_hexagon_outline.puml
!include ip/arrow_up_box.puml
!include ip/arrow_up_drop_circle.puml
!include ip/arrow_up_drop_circle_outline.puml
!include ip/arrow_up_thick.puml
!include ip/artist.puml
!include ip/assistant.puml
!include ip/asterisk.puml
!include ip/at.puml
!include ip/atlassian.puml
!include ip/atom.puml
!include ip/attachment.puml
!include ip/audiobook.puml
!include ip/auto_fix.puml
!include ip/auto_upload.puml
!include ip/autorenew.puml
!include ip/av_timer.puml
!include ip/azure.puml
!include ip/baby.puml
!include ip/baby_buggy.puml
!include ip/backburger.puml
!include ip/backspace.puml
!include ip/backup_restore.puml
!include ip/bandcamp.puml
!include ip/bank.puml
!include ip/barcode.puml
!include ip/barcode_scan.puml
!include ip/barley.puml
!include ip/barrel.puml
!include ip/basecamp.puml
!include ip/basket.puml
!include ip/basket_fill.puml
!include ip/basket_unfill.puml
!include ip/basketball.puml
!include ip/battery.puml
!include ip/battery_10.puml
!include ip/battery_20.puml
!include ip/battery_30.puml
!include ip/battery_40.puml
!include ip/battery_50.puml
!include ip/battery_60.puml
!include ip/battery_70.puml
!include ip/battery_80.puml
!include ip/battery_90.puml
!include ip/battery_alert.puml
!include ip/battery_charging.puml
!include ip/battery_charging_100.puml
!include ip/battery_charging_20.puml
!include ip/battery_charging_30.puml
!include ip/battery_charging_40.puml
!include ip/battery_charging_60.puml
!include ip/battery_charging_80.puml
!include ip/battery_charging_90.puml
!include ip/battery_charging_wireless.puml
!include ip/battery_charging_wireless_10.puml
!include ip/battery_charging_wireless_20.puml
!include ip/battery_charging_wireless_30.puml
!include ip/battery_charging_wireless_40.puml
!include ip/battery_charging_wireless_50.puml
!include ip/battery_charging_wireless_60.puml
!include ip/battery_charging_wireless_70.puml
!include ip/battery_charging_wireless_80.puml
!include ip/battery_charging_wireless_90.puml
!include ip/battery_charging_wireless_alert.puml
!include ip/battery_charging_wireless_outline.puml
!include ip/battery_minus.puml
!include ip/battery_negative.puml
!include ip/battery_outline.puml
!include ip/battery_plus.puml
!include ip/battery_positive.puml
!include ip/battery_standard.puml
!include ip/battery_unknown.puml
!include ip/beach.puml
!include ip/beaker.puml
!include ip/beam.puml
!include ip/beats.puml
!include ip/beer.puml
!include ip/behance.puml
!include ip/bell.puml
!include ip/bell_off.puml
!include ip/bell_outline.puml
!include ip/bell_plus.puml
!include ip/bell_ring.puml
!include ip/bell_ring_outline.puml
!include ip/bell_sleep.puml
!include ip/beta.puml
!include ip/bible.puml
!include ip/bike.puml
!include ip/bing.puml
!include ip/binoculars.puml
!include ip/bio.puml
!include ip/bitbucket.puml
!include ip/black_mesa.puml
!include ip/blackberry.puml
!include ip/blender.puml
!include ip/blinds.puml
!include ip/block_helper.puml
!include ip/blogger.puml
!include ip/bluetooth.puml
!include ip/bluetooth_audio.puml
!include ip/bluetooth_connect.puml
!include ip/bluetooth_off.puml
!include ip/bluetooth_settings.puml
!include ip/bluetooth_transfer.puml
!include ip/blur.puml
!include ip/blur_linear.puml
!include ip/blur_off.puml
!include ip/blur_radial.puml
!include ip/bomb.puml
!include ip/bomb_off.puml
!include ip/bone.puml
!include ip/book.puml
!include ip/book_minus.puml
!include ip/book_multiple.puml
!include ip/book_multiple_variant.puml
!include ip/book_open.puml
!include ip/book_open_page_variant.puml
!include ip/book_open_variant.puml
!include ip/book_plus.puml
!include ip/book_secure.puml
!include ip/book_unsecure.puml
!include ip/book_variant.puml
!include ip/bookmark.puml
!include ip/bookmark_check.puml
!include ip/bookmark_music.puml
!include ip/bookmark_outline.puml
!include ip/bookmark_plus.puml
!include ip/bookmark_plus_outline.puml
!include ip/bookmark_remove.puml
!include ip/boombox.puml
!include ip/bootstrap.puml
!include ip/border_all.puml
!include ip/border_bottom.puml
!include ip/border_color.puml
!include ip/border_horizontal.puml
!include ip/border_inside.puml
!include ip/border_left.puml
!include ip/border_none.puml
!include ip/border_outside.puml
!include ip/border_right.puml
!include ip/border_style.puml
!include ip/border_top.puml
!include ip/border_vertical.puml
!include ip/bow_tie.puml
!include ip/bowl.puml
!include ip/bowling.puml
!include ip/box.puml
!include ip/box_cutter.puml
!include ip/box_download.puml
!include ip/box_shadow.puml
!include ip/box_upload.puml
!include ip/bridge.puml
!include ip/briefcase.puml
!include ip/briefcase_check.puml
!include ip/briefcase_download.puml
!include ip/briefcase_outline.puml
!include ip/briefcase_upload.puml
!include ip/brightness.puml
!include ip/brightness_1.puml
!include ip/brightness_2.puml
!include ip/brightness_3.puml
!include ip/brightness_4.puml
!include ip/brightness_5.puml
!include ip/brightness_6.puml
!include ip/brightness_7.puml
!include ip/brightness_auto.puml
!include ip/broom.puml
!include ip/brush.puml
!include ip/buffer.puml
!include ip/bug.puml
!include ip/bulletin_board.puml
!include ip/bullhorn.puml
!include ip/bullseye.puml
!include ip/burst_mode.puml
!include ip/bus.puml
!include ip/bus_articulated_end.puml
!include ip/bus_articulated_front.puml
!include ip/bus_double_decker.puml
!include ip/bus_school.puml
!include ip/bus_side.puml
!include ip/cached.puml
!include ip/cake.puml
!include ip/cake_layered.puml
!include ip/cake_variant.puml
!include ip/calculator.puml
!include ip/calculator_off.puml
!include ip/calendar.puml
!include ip/calendar_blank.puml
!include ip/calendar_check.puml
!include ip/calendar_clock.puml
!include ip/calendar_multiple.puml
!include ip/calendar_multiple_check.puml
!include ip/calendar_plus.puml
!include ip/calendar_question.puml
!include ip/calendar_range.puml
!include ip/calendar_remove.puml
!include ip/calendar_select.puml
!include ip/calendar_text.puml
!include ip/calendar_today.puml
!include ip/call_made.puml
!include ip/call_merge.puml
!include ip/call_missed.puml
!include ip/call_received.puml
!include ip/call_split.puml
!include ip/camcorder.puml
!include ip/camcorder_box.puml
!include ip/camcorder_box_off.puml
!include ip/camcorder_off.puml
!include ip/camera.puml
!include ip/camera_burst.puml
!include ip/camera_enhance.puml
!include ip/camera_front.puml
!include ip/camera_front_variant.puml
!include ip/camera_gopro.puml
!include ip/camera_iris.puml
!include ip/camera_metering_center.puml
!include ip/camera_metering_matrix.puml
!include ip/camera_metering_partial.puml
!include ip/camera_metering_spot.puml
!include ip/camera_off.puml
!include ip/camera_party_mode.puml
!include ip/camera_rear.puml
!include ip/camera_rear_variant.puml
!include ip/camera_switch.puml
!include ip/camera_timer.puml
!include ip/cancel.puml
!include ip/candle.puml
!include ip/candycane.puml
!include ip/cannabis.puml
!include ip/car.puml
!include ip/car_battery.puml
!include ip/car_connected.puml
!include ip/car_convertable.puml
!include ip/car_estate.puml
!include ip/car_hatchback.puml
!include ip/car_pickup.puml
!include ip/car_side.puml
!include ip/car_sports.puml
!include ip/car_wash.puml
!include ip/caravan.puml
!include ip/cards.puml
!include ip/cards_outline.puml
!include ip/cards_playing_outline.puml
!include ip/cards_variant.puml
!include ip/carrot.puml
!include ip/cart.puml
!include ip/cart_off.puml
!include ip/cart_outline.puml
!include ip/cart_plus.puml
!include ip/cash.puml
!include ip/cash_100.puml
!include ip/cash_multiple.puml
!include ip/cash_usd.puml
!include ip/cast.puml
!include ip/cast_connected.puml
!include ip/cast_off.puml
!include ip/castle.puml
!include ip/cat.puml
!include ip/cctv.puml
!include ip/ceiling_light.puml
!include ip/cellphone.puml
!include ip/cellphone_android.puml
!include ip/cellphone_basic.puml
!include ip/cellphone_dock.puml
!include ip/cellphone_iphone.puml
!include ip/cellphone_link.puml
!include ip/cellphone_link_off.puml
!include ip/cellphone_settings.puml
!include ip/cellphone_wireless.puml
!include ip/certificate.puml
!include ip/chair_school.puml
!include ip/chart_arc.puml
!include ip/chart_areaspline.puml
!include ip/chart_bar.puml
!include ip/chart_bar_stacked.puml
!include ip/chart_bubble.puml
!include ip/chart_donut.puml
!include ip/chart_donut_variant.puml
!include ip/chart_gantt.puml
!include ip/chart_histogram.puml
!include ip/chart_line.puml
!include ip/chart_line_stacked.puml
!include ip/chart_line_variant.puml
!include ip/chart_pie.puml
!include ip/chart_scatterplot_hexbin.puml
!include ip/chart_timeline.puml
!include ip/check.puml
!include ip/check_all.puml
!include ip/check_bookmark.puml
!include ip/check_circle.puml
!include ip/check_circle_outline.puml
!include ip/checkbox_blank.puml
!include ip/checkbox_blank_circle.puml
!include ip/checkbox_blank_circle_outline.puml
!include ip/checkbox_blank_outline.puml
!include ip/checkbox_marked.puml
!include ip/checkbox_marked_circle.puml
!include ip/checkbox_marked_circle_outline.puml
!include ip/checkbox_marked_outline.puml
!include ip/checkbox_multiple_blank.puml
!include ip/checkbox_multiple_blank_circle.puml
!include ip/checkbox_multiple_blank_circle_outline.puml
!include ip/checkbox_multiple_blank_outline.puml
!include ip/checkbox_multiple_marked.puml
!include ip/checkbox_multiple_marked_circle.puml
!include ip/checkbox_multiple_marked_circle_outline.puml
!include ip/checkbox_multiple_marked_outline.puml
!include ip/checkerboard.puml
!include ip/chemical_weapon.puml
!include ip/chevron_double_down.puml
!include ip/chevron_double_left.puml
!include ip/chevron_double_right.puml
!include ip/chevron_double_up.puml
!include ip/chevron_down.puml
!include ip/chevron_left.puml
!include ip/chevron_right.puml
!include ip/chevron_up.puml
!include ip/chili_hot.puml
!include ip/chili_medium.puml
!include ip/chili_mild.puml
!include ip/chip.puml
!include ip/church.puml
!include ip/circle.puml
!include ip/circle_outline.puml
!include ip/cisco_webex.puml
!include ip/city.puml
!include ip/clapperboard.puml
!include ip/clipboard.puml
!include ip/clipboard_account.puml
!include ip/clipboard_alert.puml
!include ip/clipboard_arrow_down.puml
!include ip/clipboard_arrow_left.puml
!include ip/clipboard_check.puml
!include ip/clipboard_flow.puml
!include ip/clipboard_outline.puml
!include ip/clipboard_plus.puml
!include ip/clipboard_text.puml
!include ip/clippy.puml
!include ip/clock.puml
!include ip/clock_alert.puml
!include ip/clock_end.puml
!include ip/clock_fast.puml
!include ip/clock_in.puml
!include ip/clock_out.puml
!include ip/clock_start.puml
!include ip/close.puml
!include ip/close_circle.puml
!include ip/close_circle_outline.puml
!include ip/close_network.puml
!include ip/close_octagon.puml
!include ip/close_octagon_outline.puml
!include ip/close_outline.puml
!include ip/closed_caption.puml
!include ip/cloud.puml
!include ip/cloud_braces.puml
!include ip/cloud_check.puml
!include ip/cloud_circle.puml
!include ip/cloud_download.puml
!include ip/cloud_off_outline.puml
!include ip/cloud_outline.puml
!include ip/cloud_print.puml
!include ip/cloud_print_outline.puml
!include ip/cloud_sync.puml
!include ip/cloud_tags.puml
!include ip/cloud_upload.puml
!include ip/clover.puml
!include ip/code_array.puml
!include ip/code_braces.puml
!include ip/code_brackets.puml
!include ip/code_equal.puml
!include ip/code_greater_than.puml
!include ip/code_greater_than_or_equal.puml
!include ip/code_less_than.puml
!include ip/code_less_than_or_equal.puml
!include ip/code_not_equal.puml
!include ip/code_not_equal_variant.puml
!include ip/code_parentheses.puml
!include ip/code_string.puml
!include ip/code_tags.puml
!include ip/code_tags_check.puml
!include ip/codepen.puml
!include ip/coffee.puml
!include ip/coffee_outline.puml
!include ip/coffee_to_go.puml
!include ip/coin.puml
!include ip/coins.puml
!include ip/collage.puml
!include ip/color_helper.puml
!include ip/comment.puml
!include ip/comment_account.puml
!include ip/comment_account_outline.puml
!include ip/comment_alert.puml
!include ip/comment_alert_outline.puml
!include ip/comment_check.puml
!include ip/comment_check_outline.puml
!include ip/comment_multiple_outline.puml
!include ip/comment_outline.puml
!include ip/comment_plus_outline.puml
!include ip/comment_processing.puml
!include ip/comment_processing_outline.puml
!include ip/comment_question.puml
!include ip/comment_question_outline.puml
!include ip/comment_remove.puml
!include ip/comment_remove_outline.puml
!include ip/comment_text.puml
!include ip/comment_text_outline.puml
!include ip/common.puml
!include ip/compare.puml
!include ip/compass.puml
!include ip/compass_outline.puml
!include ip/console.puml
!include ip/console_line.puml
!include ip/contact_mail.puml
!include ip/contacts.puml
!include ip/content_copy.puml
!include ip/content_cut.puml
!include ip/content_duplicate.puml
!include ip/content_paste.puml
!include ip/content_save.puml
!include ip/content_save_all.puml
!include ip/content_save_outline.puml
!include ip/content_save_settings.puml
!include ip/contrast.puml
!include ip/contrast_box.puml
!include ip/contrast_circle.puml
!include ip/controller_xbox.puml
!include ip/cookie.puml
!include ip/copyright.puml
!include ip/corn.puml
!include ip/counter.puml
!include ip/cow.puml
!include ip/creation.puml
!include ip/credit_card.puml
!include ip/credit_card_multiple.puml
!include ip/credit_card_off.puml
!include ip/credit_card_plus.puml
!include ip/credit_card_scan.puml
!include ip/crop.puml
!include ip/crop_free.puml
!include ip/crop_landscape.puml
!include ip/crop_portrait.puml
!include ip/crop_rotate.puml
!include ip/crop_square.puml
!include ip/crosshairs.puml
!include ip/crosshairs_gps.puml
!include ip/crown.puml
!include ip/cube.puml
!include ip/cube_outline.puml
!include ip/cube_send.puml
!include ip/cube_unfolded.puml
!include ip/cup.puml
!include ip/cup_off.puml
!include ip/cup_water.puml
!include ip/currency_btc.puml
!include ip/currency_chf.puml
!include ip/currency_cny.puml
!include ip/currency_eth.puml
!include ip/currency_eur.puml
!include ip/currency_gbp.puml
!include ip/currency_inr.puml
!include ip/currency_jpy.puml
!include ip/currency_krw.puml
!include ip/currency_ngn.puml
!include ip/currency_rub.puml
!include ip/currency_sign.puml
!include ip/currency_try.puml
!include ip/currency_twd.puml
!include ip/currency_usd.puml
!include ip/currency_usd_off.puml
!include ip/cursor_default.puml
!include ip/cursor_default_outline.puml
!include ip/cursor_move.puml
!include ip/cursor_pointer.puml
!include ip/cursor_text.puml
!include ip/data.puml
!include ip/database.puml
!include ip/database_minus.puml
!include ip/database_plus.puml
!include ip/debug_step_into.puml
!include ip/debug_step_out.puml
!include ip/debug_step_over.puml
!include ip/decagram.puml
!include ip/decagram_outline.puml
!include ip/decimal_decrease.puml
!include ip/decimal_increase.puml
!include ip/delete.puml
!include ip/delete_circle.puml
!include ip/delete_empty.puml
!include ip/delete_forever.puml
!include ip/delete_restore.puml
!include ip/delete_sweep.puml
!include ip/delete_variant.puml
!include ip/delta.puml
!include ip/deskphone.puml
!include ip/desktop_classic.puml
!include ip/desktop_mac.puml
!include ip/desktop_tower.puml
!include ip/details.puml
!include ip/developer_board.puml
!include ip/deviantart.puml
!include ip/dialpad.puml
!include ip/diamond.puml
!include ip/dice.puml
!include ip/dice_1.puml
!include ip/dice_2.puml
!include ip/dice_3.puml
!include ip/dice_4.puml
!include ip/dice_5.puml
!include ip/dice_6.puml
!include ip/dice_d10.puml
!include ip/dice_d20.puml
!include ip/dice_d4.puml
!include ip/dice_d6.puml
!include ip/dice_d8.puml
!include ip/dice_multiple.puml
!include ip/dictionary.puml
!include ip/dip_switch.puml
!include ip/directions.puml
!include ip/directions_fork.puml
!include ip/discord.puml
!include ip/disk.puml
!include ip/disk_alert.puml
!include ip/disqus.puml
!include ip/disqus_outline.puml
!include ip/division.puml
!include ip/division_box.puml
!include ip/dna.puml
!include ip/dns.puml
!include ip/do_not_disturb.puml
!include ip/do_not_disturb_off.puml
!include ip/document.puml
!include ip/dolby.puml
!include ip/domain.puml
!include ip/donkey.puml
!include ip/door.puml
!include ip/door_closed.puml
!include ip/door_open.puml
!include ip/dots_horizontal.puml
!include ip/dots_horizontal_circle.puml
!include ip/dots_vertical.puml
!include ip/dots_vertical_circle.puml
!include ip/douban.puml
!include ip/download.puml
!include ip/download_network.puml
!include ip/drag.puml
!include ip/drag_horizontal.puml
!include ip/drag_vertical.puml
!include ip/drawing.puml
!include ip/drawing_box.puml
!include ip/dribbble.puml
!include ip/dribbble_box.puml
!include ip/drone.puml
!include ip/dropbox.puml
!include ip/drupal.puml
!include ip/duck.puml
!include ip/dumbbell.puml
!include ip/ear_hearing.puml
!include ip/earth.puml
!include ip/earth_box.puml
!include ip/earth_box_off.puml
!include ip/earth_off.puml
!include ip/ebay.puml
!include ip/edge.puml
!include ip/eject.puml
!include ip/elephant.puml
!include ip/elevation_decline.puml
!include ip/elevation_rise.puml
!include ip/elevator.puml
!include ip/email.puml
!include ip/email_alert.puml
!include ip/email_open.puml
!include ip/email_open_outline.puml
!include ip/email_outline.puml
!include ip/email_secure.puml
!include ip/email_variant.puml
!include ip/emby.puml
!include ip/emoticon.puml
!include ip/emoticon_cool.puml
!include ip/emoticon_dead.puml
!include ip/emoticon_devil.puml
!include ip/emoticon_excited.puml
!include ip/emoticon_happy.puml
!include ip/emoticon_neutral.puml
!include ip/emoticon_poop.puml
!include ip/emoticon_sad.puml
!include ip/emoticon_tongue.puml
!include ip/engine.puml
!include ip/engine_outline.puml
!include ip/equal.puml
!include ip/equal_box.puml
!include ip/eraser.puml
!include ip/eraser_variant.puml
!include ip/escalator.puml
!include ip/ethernet.puml
!include ip/ethernet_cable.puml
!include ip/ethernet_cable_off.puml
!include ip/etsy.puml
!include ip/ev_station.puml
!include ip/eventbrite.puml
!include ip/evernote.puml
!include ip/exclamation.puml
!include ip/exit_to_app.puml
!include ip/export.puml
!include ip/eye.puml
!include ip/eye_off.puml
!include ip/eye_off_outline.puml
!include ip/eye_outline.puml
!include ip/eyedropper.puml
!include ip/eyedropper_variant.puml
!include ip/face.puml
!include ip/face_profile.puml
!include ip/facebook.puml
!include ip/facebook_box.puml
!include ip/facebook_messenger.puml
!include ip/factory.puml
!include ip/fan.puml
!include ip/fan_off.puml
!include ip/fast_forward.puml
!include ip/fast_forward_outline.puml
!include ip/fax.puml
!include ip/feather.puml
!include ip/ferry.puml
!include ip/file.puml
!include ip/file_account.puml
!include ip/file_chart.puml
!include ip/file_check.puml
!include ip/file_cloud.puml
!include ip/file_delimited.puml
!include ip/file_document.puml
!include ip/file_document_box.puml
!include ip/file_excel.puml
!include ip/file_excel_box.puml
!include ip/file_export.puml
!include ip/file_find.puml
!include ip/file_hidden.puml
!include ip/file_image.puml
!include ip/file_image_box.puml
!include ip/file_import.puml
!include ip/file_lock.puml
!include ip/file_move.puml
!include ip/file_multiple.puml
!include ip/file_music.puml
!include ip/file_outline.puml
!include ip/file_pdf.puml
!include ip/file_pdf_box.puml
!include ip/file_percent.puml
!include ip/file_plus.puml
!include ip/file_powerpoint.puml
!include ip/file_powerpoint_box.puml
!include ip/file_presentation_box.puml
!include ip/file_restore.puml
!include ip/file_send.puml
!include ip/file_tree.puml
!include ip/file_video.puml
!include ip/file_word.puml
!include ip/file_word_box.puml
!include ip/file_xml.puml
!include ip/fill.puml
!include ip/film.puml
!include ip/filmstrip.puml
!include ip/filmstrip_off.puml
!include ip/filter.puml
!include ip/filter_outline.puml
!include ip/filter_remove.puml
!include ip/filter_remove_outline.puml
!include ip/filter_variant.puml
!include ip/find_replace.puml
!include ip/fingerprint.puml
!include ip/fire.puml
!include ip/fish.puml
!include ip/flag.puml
!include ip/flag_checkered.puml
!include ip/flag_checkered_variant.puml
!include ip/flag_outline.puml
!include ip/flag_outline_variant.puml
!include ip/flag_triangle.puml
!include ip/flag_variant.puml
!include ip/flash.puml
!include ip/flash_auto.puml
!include ip/flash_circle.puml
!include ip/flash_off.puml
!include ip/flash_outline.puml
!include ip/flash_red_eye.puml
!include ip/flashlight.puml
!include ip/flashlight_off.puml
!include ip/flask.puml
!include ip/flask_empty.puml
!include ip/flask_empty_outline.puml
!include ip/flask_outline.puml
!include ip/flattr.puml
!include ip/flickr_after.puml
!include ip/flickr_before.puml
!include ip/flip_to_back.puml
!include ip/flip_to_front.puml
!include ip/floor_plan.puml
!include ip/floppy.puml
!include ip/flower.puml
!include ip/folder.puml
!include ip/folder_account.puml
!include ip/folder_download.puml
!include ip/folder_google_drive.puml
!include ip/folder_image.puml
!include ip/folder_lock.puml
!include ip/folder_lock_open.puml
!include ip/folder_move.puml
!include ip/folder_multiple.puml
!include ip/folder_multiple_image.puml
!include ip/folder_multiple_outline.puml
!include ip/folder_open.puml
!include ip/folder_outline.puml
!include ip/folder_outline_lock.puml
!include ip/folder_plus.puml
!include ip/folder_remove.puml
!include ip/folder_star.puml
!include ip/folder_upload.puml
!include ip/font_awesome.puml
!include ip/food.puml
!include ip/food_apple.puml
!include ip/food_croissant.puml
!include ip/food_fork_drink.puml
!include ip/food_off.puml
!include ip/food_variant.puml
!include ip/football.puml
!include ip/football_australian.puml
!include ip/football_helmet.puml
!include ip/footer.puml
!include ip/forklift.puml
!include ip/format_align_bottom.puml
!include ip/format_align_center.puml
!include ip/format_align_justify.puml
!include ip/format_align_left.puml
!include ip/format_align_middle.puml
!include ip/format_align_right.puml
!include ip/format_align_top.puml
!include ip/format_annotation_plus.puml
!include ip/format_bold.puml
!include ip/format_clear.puml
!include ip/format_color.puml
!include ip/format_color_fill.puml
!include ip/format_color_text.puml
!include ip/format_float_center.puml
!include ip/format_float_left.puml
!include ip/format_float_none.puml
!include ip/format_float_right.puml
!include ip/format_font.puml
!include ip/format_header_1.puml
!include ip/format_header_2.puml
!include ip/format_header_3.puml
!include ip/format_header_4.puml
!include ip/format_header_5.puml
!include ip/format_header_6.puml
!include ip/format_header_decrease.puml
!include ip/format_header_down.puml
!include ip/format_header_equal.puml
!include ip/format_header_increase.puml
!include ip/format_header_pound.puml
!include ip/format_header_up.puml
!include ip/format_horizontal_align_center.puml
!include ip/format_horizontal_align_left.puml
!include ip/format_horizontal_align_right.puml
!include ip/format_indent_decrease.puml
!include ip/format_indent_increase.puml
!include ip/format_italic.puml
!include ip/format_line_spacing.puml
!include ip/format_line_style.puml
!include ip/format_line_weight.puml
!include ip/format_list_bulleted.puml
!include ip/format_list_bulleted_type.puml
!include ip/format_list_checks.puml
!include ip/format_list_numbers.puml
!include ip/format_page_break.puml
!include ip/format_paint.puml
!include ip/format_paragraph.puml
!include ip/format_pilcrow.puml
!include ip/format_quote_close.puml
!include ip/format_quote_open.puml
!include ip/format_rotate_90.puml
!include ip/format_section.puml
!include ip/format_size.puml
!include ip/format_strikethrough.puml
!include ip/format_strikethrough_variant.puml
!include ip/format_subscript.puml
!include ip/format_superscript.puml
!include ip/format_text.puml
!include ip/format_textdirection_l_to_r.puml
!include ip/format_textdirection_r_to_l.puml
!include ip/format_title.puml
!include ip/format_underline.puml
!include ip/format_vertical_align_bottom.puml
!include ip/format_vertical_align_center.puml
!include ip/format_vertical_align_top.puml
!include ip/format_wrap_inline.puml
!include ip/format_wrap_square.puml
!include ip/format_wrap_tight.puml
!include ip/format_wrap_top_bottom.puml
!include ip/forum.puml
!include ip/forum_outline.puml
!include ip/forward.puml
!include ip/foursquare.puml
!include ip/fridge.puml
!include ip/fridge_filled.puml
!include ip/fridge_filled_bottom.puml
!include ip/fridge_filled_top.puml
!include ip/fuel.puml
!include ip/fullscreen.puml
!include ip/fullscreen_exit.puml
!include ip/function.puml
!include ip/gamepad.puml
!include ip/gamepad_variant.puml
!include ip/garage.puml
!include ip/garage_open.puml
!include ip/gas_cylinder.puml
!include ip/gas_station.puml
!include ip/gate.puml
!include ip/gauge.puml
!include ip/gavel.puml
!include ip/gender_female.puml
!include ip/gender_male.puml
!include ip/gender_male_female.puml
!include ip/gender_transgender.puml
!include ip/gesture.puml
!include ip/gesture_double_tap.puml
!include ip/gesture_swipe_down.puml
!include ip/gesture_swipe_left.puml
!include ip/gesture_swipe_right.puml
!include ip/gesture_swipe_up.puml
!include ip/gesture_tap.puml
!include ip/gesture_two_double_tap.puml
!include ip/gesture_two_tap.puml
!include ip/ghost.puml
!include ip/gift.puml
!include ip/git.puml
!include ip/github_box.puml
!include ip/github_circle.puml
!include ip/github_face.puml
!include ip/glass_flute.puml
!include ip/glass_mug.puml
!include ip/glass_stange.puml
!include ip/glass_tulip.puml
!include ip/glassdoor.puml
!include ip/glasses.puml
!include ip/gmail.puml
!include ip/gnome.puml
!include ip/golf.puml
!include ip/gondola.puml
!include ip/google.puml
!include ip/google_analytics.puml
!include ip/google_assistant.puml
!include ip/google_cardboard.puml
!include ip/google_chrome.puml
!include ip/google_circles.puml
!include ip/google_circles_communities.puml
!include ip/google_circles_extended.puml
!include ip/google_circles_group.puml
!include ip/google_controller.puml
!include ip/google_controller_off.puml
!include ip/google_drive.puml
!include ip/google_earth.puml
!include ip/google_glass.puml
!include ip/google_home.puml
!include ip/google_keep.puml
!include ip/google_maps.puml
!include ip/google_nearby.puml
!include ip/google_pages.puml
!include ip/google_photos.puml
!include ip/google_physical_web.puml
!include ip/google_play.puml
!include ip/google_plus.puml
!include ip/google_plus_box.puml
!include ip/google_translate.puml
!include ip/google_wallet.puml
!include ip/gradient.puml
!include ip/grease_pencil.puml
!include ip/grid.puml
!include ip/grid_large.puml
!include ip/grid_off.puml
!include ip/group.puml
!include ip/guitar_acoustic.puml
!include ip/guitar_electric.puml
!include ip/guy_fawkes_mask.puml
!include ip/hackernews.puml
!include ip/hamburger.puml
!include ip/hand_pointing_right.puml
!include ip/hanger.puml
!include ip/hangouts.puml
!include ip/harddisk.puml
!include ip/headphones.puml
!include ip/headphones_box.puml
!include ip/headphones_off.puml
!include ip/headphones_settings.puml
!include ip/headset.puml
!include ip/headset_dock.puml
!include ip/headset_off.puml
!include ip/heart.puml
!include ip/heart_box.puml
!include ip/heart_box_outline.puml
!include ip/heart_broken.puml
!include ip/heart_half.puml
!include ip/heart_half_full.puml
!include ip/heart_half_outline.puml
!include ip/heart_off.puml
!include ip/heart_outline.puml
!include ip/heart_pulse.puml
!include ip/help.puml
!include ip/help_box.puml
!include ip/help_circle.puml
!include ip/help_circle_outline.puml
!include ip/help_network.puml
!include ip/hexagon.puml
!include ip/hexagon_multiple.puml
!include ip/hexagon_outline.puml
!include ip/high_definition.puml
!include ip/highway.puml
!include ip/history.puml
!include ip/hololens.puml
!include ip/home.puml
!include ip/home_account.puml
!include ip/home_assistant.puml
!include ip/home_automation.puml
!include ip/home_circle.puml
!include ip/home_heart.puml
!include ip/home_map_marker.puml
!include ip/home_modern.puml
!include ip/home_outline.puml
!include ip/home_variant.puml
!include ip/hook.puml
!include ip/hook_off.puml
!include ip/hops.puml
!include ip/hospital.puml
!include ip/hospital_building.puml
!include ip/hospital_marker.puml
!include ip/hot_tub.puml
!include ip/hotel.puml
!include ip/houzz_box.puml
!include ip/hulu.puml
!include ip/human.puml
!include ip/human_child.puml
!include ip/human_female.puml
!include ip/human_greeting.puml
!include ip/human_handsdown.puml
!include ip/human_handsup.puml
!include ip/human_male.puml
!include ip/human_male_female.puml
!include ip/human_pregnant.puml
!include ip/humble_bundle.puml
!include ip/ice_cream.puml
!include ip/image.puml
!include ip/image_album.puml
!include ip/image_area.puml
!include ip/image_area_close.puml
!include ip/image_broken.puml
!include ip/image_broken_variant.puml
!include ip/image_filter.puml
!include ip/image_filter_black_white.puml
!include ip/image_filter_center_focus.puml
!include ip/image_filter_center_focus_weak.puml
!include ip/image_filter_drama.puml
!include ip/image_filter_frames.puml
!include ip/image_filter_hdr.puml
!include ip/image_filter_none.puml
!include ip/image_filter_tilt_shift.puml
!include ip/image_filter_vintage.puml
!include ip/image_multiple.puml
!include ip/image_off.puml
!include ip/import.puml
!include ip/inbox.puml
!include ip/inbox_arrow_down.puml
!include ip/inbox_arrow_up.puml
!include ip/incognito.puml
!include ip/indent.puml
!include ip/infinity.puml
!include ip/information.puml
!include ip/information_outline.puml
!include ip/information_variant.puml
!include ip/instagram.puml
!include ip/instapaper.puml
!include ip/internet_explorer.puml
!include ip/invert_colors.puml
!include ip/itunes.puml
!include ip/jeepney.puml
!include ip/jira.puml
!include ip/jsfiddle.puml
!include ip/json.puml
!include ip/karate.puml
!include ip/keg.puml
!include ip/kettle.puml
!include ip/key.puml
!include ip/key_change.puml
!include ip/key_minus.puml
!include ip/key_plus.puml
!include ip/key_remove.puml
!include ip/key_variant.puml
!include ip/keyboard.puml
!include ip/keyboard_backspace.puml
!include ip/keyboard_caps.puml
!include ip/keyboard_close.puml
!include ip/keyboard_off.puml
!include ip/keyboard_return.puml
!include ip/keyboard_tab.puml
!include ip/keyboard_variant.puml
!include ip/kickstarter.puml
!include ip/kodi.puml
!include ip/label.puml
!include ip/label_outline.puml
!include ip/ladybug.puml
!include ip/lambda.puml
!include ip/lamp.puml
!include ip/lan.puml
!include ip/lan_connect.puml
!include ip/lan_disconnect.puml
!include ip/lan_pending.puml
!include ip/language_c.puml
!include ip/language_cpp.puml
!include ip/language_csharp.puml
!include ip/language_css3.puml
!include ip/language_go.puml
!include ip/language_html5.puml
!include ip/language_javascript.puml
!include ip/language_php.puml
!include ip/language_python.puml
!include ip/language_python_text.puml
!include ip/language_r.puml
!include ip/language_swift.puml
!include ip/language_typescript.puml
!include ip/laptop.puml
!include ip/laptop_chromebook.puml
!include ip/laptop_mac.puml
!include ip/laptop_off.puml
!include ip/laptop_windows.puml
!include ip/lastfm.puml
!include ip/lastpass.puml
!include ip/launch.puml
!include ip/lava_lamp.puml
!include ip/layers.puml
!include ip/layers_off.puml
!include ip/lead_pencil.puml
!include ip/leaf.puml
!include ip/led_off.puml
!include ip/led_on.puml
!include ip/led_outline.puml
!include ip/led_strip.puml
!include ip/led_variant_off.puml
!include ip/led_variant_on.puml
!include ip/led_variant_outline.puml
!include ip/library.puml
!include ip/library_books.puml
!include ip/library_music.puml
!include ip/library_plus.puml
!include ip/lightbulb.puml
!include ip/lightbulb_on.puml
!include ip/lightbulb_on_outline.puml
!include ip/lightbulb_outline.puml
!include ip/link.puml
!include ip/link_off.puml
!include ip/link_variant.puml
!include ip/link_variant_off.puml
!include ip/linkedin.puml
!include ip/linkedin_box.puml
!include ip/linode.puml
!include ip/linux.puml
!include ip/loading.puml
!include ip/lock.puml
!include ip/lock_open.puml
!include ip/lock_open_outline.puml
!include ip/lock_outline.puml
!include ip/lock_pattern.puml
!include ip/lock_plus.puml
!include ip/lock_reset.puml
!include ip/locker.puml
!include ip/locker_multiple.puml
!include ip/login.puml
!include ip/login_variant.puml
!include ip/logout.puml
!include ip/logout_variant.puml
!include ip/looks.puml
!include ip/loop.puml
!include ip/loupe.puml
!include ip/lumx.puml
!include ip/magnet.puml
!include ip/magnet_on.puml
!include ip/magnify.puml
!include ip/magnify_minus.puml
!include ip/magnify_minus_outline.puml
!include ip/magnify_plus.puml
!include ip/magnify_plus_outline.puml
!include ip/mail_ru.puml
!include ip/mailbox.puml
!include ip/map.puml
!include ip/map_marker.puml
!include ip/map_marker_circle.puml
!include ip/map_marker_minus.puml
!include ip/map_marker_multiple.puml
!include ip/map_marker_off.puml
!include ip/map_marker_outline.puml
!include ip/map_marker_plus.puml
!include ip/map_marker_radius.puml
!include ip/margin.puml
!include ip/markdown.puml
!include ip/marker.puml
!include ip/marker_check.puml
!include ip/martini.puml
!include ip/material_ui.puml
!include ip/matrix.puml
!include ip/maxcdn.puml
!include ip/medical_bag.puml
!include ip/medium.puml
!include ip/memory.puml
!include ip/menu.puml
!include ip/menu_down.puml
!include ip/menu_down_outline.puml
!include ip/menu_left.puml
!include ip/menu_right.puml
!include ip/menu_up.puml
!include ip/menu_up_outline.puml
!include ip/message.puml
!include ip/message_alert.puml
!include ip/message_bulleted.puml
!include ip/message_bulleted_off.puml
!include ip/message_draw.puml
!include ip/message_image.puml
!include ip/message_outline.puml
!include ip/message_plus.puml
!include ip/message_processing.puml
!include ip/message_reply.puml
!include ip/message_reply_text.puml
!include ip/message_settings.puml
!include ip/message_settings_variant.puml
!include ip/message_text.puml
!include ip/message_text_outline.puml
!include ip/message_video.puml
!include ip/meteor.puml
!include ip/metronome.puml
!include ip/metronome_tick.puml
!include ip/micro_sd.puml
!include ip/microphone.puml
!include ip/microphone_off.puml
!include ip/microphone_outline.puml
!include ip/microphone_settings.puml
!include ip/microphone_variant.puml
!include ip/microphone_variant_off.puml
!include ip/microscope.puml
!include ip/microsoft.puml
!include ip/minecraft.puml
!include ip/minus.puml
!include ip/minus_box.puml
!include ip/minus_box_outline.puml
!include ip/minus_circle.puml
!include ip/minus_circle_outline.puml
!include ip/minus_network.puml
!include ip/mixcloud.puml
!include ip/mixer.puml
!include ip/monitor.puml
!include ip/monitor_multiple.puml
!include ip/more.puml
!include ip/mouse.puml
!include ip/mouse_off.puml
!include ip/mouse_variant.puml
!include ip/mouse_variant_off.puml
!include ip/move_resize.puml
!include ip/move_resize_variant.puml
!include ip/movie.puml
!include ip/movie_roll.puml
!include ip/multiplication.puml
!include ip/multiplication_box.puml
!include ip/mushroom.puml
!include ip/mushroom_outline.puml
!include ip/music.puml
!include ip/music_box.puml
!include ip/music_box_outline.puml
!include ip/music_circle.puml
!include ip/music_note.puml
!include ip/music_note_bluetooth.puml
!include ip/music_note_bluetooth_off.puml
!include ip/music_note_eighth.puml
!include ip/music_note_half.puml
!include ip/music_note_off.puml
!include ip/music_note_quarter.puml
!include ip/music_note_sixteenth.puml
!include ip/music_note_whole.puml
!include ip/music_off.puml
!include ip/nature.puml
!include ip/nature_people.puml
!include ip/navigation.puml
!include ip/near_me.puml
!include ip/needle.puml
!include ip/nest_protect.puml
!include ip/nest_thermostat.puml
!include ip/netflix.puml
!include ip/network.puml
!include ip/new_box.puml
!include ip/newspaper.puml
!include ip/nfc.puml
!include ip/nfc_tap.puml
!include ip/nfc_variant.puml
!include ip/ninja.puml
!include ip/nintendo_switch.puml
!include ip/no.puml
!include ip/nodejs.puml
!include ip/not_equal.puml
!include ip/note.puml
!include ip/note_multiple.puml
!include ip/note_multiple_outline.puml
!include ip/note_outline.puml
!include ip/note_plus.puml
!include ip/note_plus_outline.puml
!include ip/note_text.puml
!include ip/notebook.puml
!include ip/notification_clear_all.puml
!include ip/npm.puml
!include ip/nuke.puml
!include ip/null.puml
!include ip/numeric.puml
!include ip/numeric_0_box.puml
!include ip/numeric_0_box_multiple_outline.puml
!include ip/numeric_0_box_outline.puml
!include ip/numeric_1_box.puml
!include ip/numeric_1_box_multiple_outline.puml
!include ip/numeric_1_box_outline.puml
!include ip/numeric_2_box.puml
!include ip/numeric_2_box_multiple_outline.puml
!include ip/numeric_2_box_outline.puml
!include ip/numeric_3_box.puml
!include ip/numeric_3_box_multiple_outline.puml
!include ip/numeric_3_box_outline.puml
!include ip/numeric_4_box.puml
!include ip/numeric_4_box_multiple_outline.puml
!include ip/numeric_4_box_outline.puml
!include ip/numeric_5_box.puml
!include ip/numeric_5_box_multiple_outline.puml
!include ip/numeric_5_box_outline.puml
!include ip/numeric_6_box.puml
!include ip/numeric_6_box_multiple_outline.puml
!include ip/numeric_6_box_outline.puml
!include ip/numeric_7_box.puml
!include ip/numeric_7_box_multiple_outline.puml
!include ip/numeric_7_box_outline.puml
!include ip/numeric_8_box.puml
!include ip/numeric_8_box_multiple_outline.puml
!include ip/numeric_8_box_outline.puml
!include ip/numeric_9_box.puml
!include ip/numeric_9_box_multiple_outline.puml
!include ip/numeric_9_box_outline.puml
!include ip/numeric_9_plus_box.puml
!include ip/numeric_9_plus_box_multiple_outline.puml
!include ip/numeric_9_plus_box_outline.puml
!include ip/nut.puml
!include ip/nutrition.puml
!include ip/oar.puml
!include ip/octagon.puml
!include ip/octagon_outline.puml
!include ip/octagram.puml
!include ip/octagram_outline.puml
!include ip/odnoklassniki.puml
!include ip/office.puml
!include ip/oil.puml
!include ip/oil_temperature.puml
!include ip/omega.puml
!include ip/onedrive.puml
!include ip/onenote.puml
!include ip/opacity.puml
!include ip/open_in_app.puml
!include ip/open_in_new.puml
!include ip/openid.puml
!include ip/opera.puml
!include ip/orbit.puml
!include ip/ornament.puml
!include ip/ornament_variant.puml
!include ip/outbox.puml
!include ip/outdent.puml
!include ip/owl.puml
!include ip/package.puml
!include ip/package_down.puml
!include ip/package_up.puml
!include ip/package_variant.puml
!include ip/package_variant_closed.puml
!include ip/page_first.puml
!include ip/page_last.puml
!include ip/page_layout_body.puml
!include ip/page_layout_footer.puml
!include ip/page_layout_header.puml
!include ip/page_layout_sidebar_left.puml
!include ip/page_layout_sidebar_right.puml
!include ip/palette.puml
!include ip/palette_advanced.puml
!include ip/panda.puml
!include ip/pandora.puml
!include ip/panorama.puml
!include ip/panorama_fisheye.puml
!include ip/panorama_horizontal.puml
!include ip/panorama_vertical.puml
!include ip/panorama_wide_angle.puml
!include ip/paper_cut_vertical.puml
!include ip/paperclip.puml
!include ip/parking.puml
!include ip/passport.puml
!include ip/pause.puml
!include ip/pause_circle.puml
!include ip/pause_circle_outline.puml
!include ip/pause_octagon.puml
!include ip/pause_octagon_outline.puml
!include ip/paw.puml
!include ip/paw_off.puml
!include ip/pen.puml
!include ip/pencil.puml
!include ip/pencil_box.puml
!include ip/pencil_box_outline.puml
!include ip/pencil_circle.puml
!include ip/pencil_circle_outline.puml
!include ip/pencil_lock.puml
!include ip/pencil_off.puml
!include ip/pentagon.puml
!include ip/pentagon_outline.puml
!include ip/people.puml
!include ip/percent.puml
!include ip/periodic_table_co2.puml
!include ip/periscope.puml
!include ip/person_box.puml
!include ip/person_minus.puml
!include ip/person_plus.puml
!include ip/pharmacy.puml
!include ip/phone.puml
!include ip/phone_bluetooth.puml
!include ip/phone_classic.puml
!include ip/phone_forward.puml
!include ip/phone_hangup.puml
!include ip/phone_in_talk.puml
!include ip/phone_incoming.puml
!include ip/phone_locked.puml
!include ip/phone_log.puml
!include ip/phone_minus.puml
!include ip/phone_missed.puml
!include ip/phone_outgoing.puml
!include ip/phone_paused.puml
!include ip/phone_plus.puml
!include ip/phone_return.puml
!include ip/phone_settings.puml
!include ip/phone_voip.puml
!include ip/pi.puml
!include ip/pi_box.puml
!include ip/piano.puml
!include ip/picture.puml
!include ip/pig.puml
!include ip/pill.puml
!include ip/pillar.puml
!include ip/pin.puml
!include ip/pin_off.puml
!include ip/pine_tree.puml
!include ip/pine_tree_box.puml
!include ip/pinterest.puml
!include ip/pinterest_box.puml
!include ip/pipe.puml
!include ip/pipe_disconnected.puml
!include ip/pistol.puml
!include ip/pizza.puml
!include ip/plane.puml
!include ip/plane_shield.puml
!include ip/play.puml
!include ip/play_box_outline.puml
!include ip/play_circle.puml
!include ip/play_circle_outline.puml
!include ip/play_pause.puml
!include ip/play_protected_content.puml
!include ip/playlist_check.puml
!include ip/playlist_minus.puml
!include ip/playlist_play.puml
!include ip/playlist_plus.puml
!include ip/playlist_remove.puml
!include ip/playstation.puml
!include ip/plex.puml
!include ip/plus.puml
!include ip/plus_box.puml
!include ip/plus_box_outline.puml
!include ip/plus_circle.puml
!include ip/plus_circle_multiple_outline.puml
!include ip/plus_circle_outline.puml
!include ip/plus_network.puml
!include ip/plus_one.puml
!include ip/plus_outline.puml
!include ip/pocket.puml
!include ip/pokeball.puml
!include ip/poker_chip.puml
!include ip/polaroid.puml
!include ip/poll.puml
!include ip/poll_box.puml
!include ip/polymer.puml
!include ip/pool.puml
!include ip/popcorn.puml
!include ip/pot.puml
!include ip/pot_mix.puml
!include ip/pound.puml
!include ip/pound_box.puml
!include ip/power.puml
!include ip/power_plug.puml
!include ip/power_plug_off.puml
!include ip/power_settings.puml
!include ip/power_socket.puml
!include ip/power_socket_eu.puml
!include ip/power_socket_uk.puml
!include ip/power_socket_us.puml
!include ip/prescription.puml
!include ip/presentation.puml
!include ip/presentation_play.puml
!include ip/printer.puml
!include ip/printer_3d.puml
!include ip/printer_alert.puml
!include ip/printer_settings.puml
!include ip/priority_high.puml
!include ip/priority_low.puml
!include ip/professional_hexagon.puml
!include ip/projector.puml
!include ip/projector_screen.puml
!include ip/publish.puml
!include ip/pulse.puml
!include ip/puzzle.puml
!include ip/qqchat.puml
!include ip/qrcode.puml
!include ip/qrcode_scan.puml
!include ip/quadcopter.puml
!include ip/quality_high.puml
!include ip/question_mark_circle.puml
!include ip/quick_reply.puml
!include ip/quicktime.puml
!include ip/rabbit.puml
!include ip/radar.puml
!include ip/radiator.puml
!include ip/radio.puml
!include ip/radio_handheld.puml
!include ip/radio_tower.puml
!include ip/radioactive.puml
!include ip/radiobox_blank.puml
!include ip/radiobox_marked.puml
!include ip/raspberrypi.puml
!include ip/ray_end.puml
!include ip/ray_end_arrow.puml
!include ip/ray_start.puml
!include ip/ray_start_arrow.puml
!include ip/ray_start_end.puml
!include ip/ray_vertex.puml
!include ip/rdio.puml
!include ip/react.puml
!include ip/read.puml
!include ip/receipt.puml
!include ip/record.puml
!include ip/record_rec.puml
!include ip/recycle.puml
!include ip/reddit.puml
!include ip/redo.puml
!include ip/redo_variant.puml
!include ip/refresh.puml
!include ip/relative_scale.puml
!include ip/reload.puml
!include ip/remote.puml
!include ip/rename_box.puml
!include ip/reorder_horizontal.puml
!include ip/reorder_vertical.puml
!include ip/repeat.puml
!include ip/repeat_off.puml
!include ip/repeat_once.puml
!include ip/replay.puml
!include ip/reply.puml
!include ip/reply_all.puml
!include ip/reproduction.puml
!include ip/resize_bottom_right.puml
!include ip/responsive.puml
!include ip/restart.puml
!include ip/restore.puml
!include ip/rewind.puml
!include ip/rewind_outline.puml
!include ip/rhombus.puml
!include ip/rhombus_outline.puml
!include ip/ribbon.puml
!include ip/rice.puml
!include ip/ring.puml
!include ip/road.puml
!include ip/road_variant.puml
!include ip/robot.puml
!include ip/rocket.puml
!include ip/roomba.puml
!include ip/rotate_3d.puml
!include ip/rotate_left.puml
!include ip/rotate_left_variant.puml
!include ip/rotate_right.puml
!include ip/rotate_right_variant.puml
!include ip/rounded_corner.puml
!include ip/router_wireless.puml
!include ip/routes.puml
!include ip/rowing.puml
!include ip/rss.puml
!include ip/rss_box.puml
!include ip/ruler.puml
!include ip/run.puml
!include ip/run_fast.puml
!include ip/sale.puml
!include ip/sass.puml
!include ip/satellite.puml
!include ip/satellite_variant.puml
!include ip/saxophone.puml
!include ip/scale.puml
!include ip/scale_balance.puml
!include ip/scale_bathroom.puml
!include ip/scanner.puml
!include ip/school.puml
!include ip/screen_rotation.puml
!include ip/screen_rotation_lock.puml
!include ip/screwdriver.puml
!include ip/script.puml
!include ip/sd.puml
!include ip/seal.puml
!include ip/search_web.puml
!include ip/seat_flat.puml
!include ip/seat_flat_angled.puml
!include ip/seat_individual_suite.puml
!include ip/seat_legroom_extra.puml
!include ip/seat_legroom_normal.puml
!include ip/seat_legroom_reduced.puml
!include ip/seat_recline_extra.puml
!include ip/seat_recline_normal.puml
!include ip/security.puml
!include ip/security_home.puml
!include ip/security_network.puml
!include ip/select.puml
!include ip/select_all.puml
!include ip/select_inverse.puml
!include ip/select_off.puml
!include ip/selection.puml
!include ip/selection_off.puml
!include ip/send.puml
!include ip/send_secure.puml
!include ip/serial_port.puml
!include ip/server.puml
!include ip/server_minus.puml
!include ip/server_network.puml
!include ip/server_network_off.puml
!include ip/server_off.puml
!include ip/server_plus.puml
!include ip/server_remove.puml
!include ip/server_security.puml
!include ip/set_all.puml
!include ip/set_center.puml
!include ip/set_center_right.puml
!include ip/set_left.puml
!include ip/set_left_center.puml
!include ip/set_left_right.puml
!include ip/set_none.puml
!include ip/set_right.puml
!include ip/settings.puml
!include ip/settings_box.puml
!include ip/shape.puml
!include ip/shape_circle_plus.puml
!include ip/shape_outline.puml
!include ip/shape_plus.puml
!include ip/shape_polygon_plus.puml
!include ip/shape_rectangle_plus.puml
!include ip/shape_square_plus.puml
!include ip/share.puml
!include ip/share_variant.puml
!include ip/shield.puml
!include ip/shield_half_full.puml
!include ip/shield_outline.puml
!include ip/ship_wheel.puml
!include ip/shopping.puml
!include ip/shopping_music.puml
!include ip/shovel.puml
!include ip/shovel_off.puml
!include ip/shredder.puml
!include ip/shuffle.puml
!include ip/shuffle_disabled.puml
!include ip/shuffle_variant.puml
!include ip/sigma.puml
!include ip/sigma_lower.puml
!include ip/sign_caution.puml
!include ip/sign_direction.puml
!include ip/sign_text.puml
!include ip/signal.puml
!include ip/signal_2g.puml
!include ip/signal_3g.puml
!include ip/signal_4g.puml
!include ip/signal_hspa.puml
!include ip/signal_hspa_plus.puml
!include ip/signal_off.puml
!include ip/signal_variant.puml
!include ip/silverware.puml
!include ip/silverware_fork.puml
!include ip/silverware_spoon.puml
!include ip/silverware_variant.puml
!include ip/sim.puml
!include ip/sim_alert.puml
!include ip/sim_off.puml
!include ip/sitemap.puml
!include ip/skip_backward.puml
!include ip/skip_forward.puml
!include ip/skip_next.puml
!include ip/skip_next_circle.puml
!include ip/skip_next_circle_outline.puml
!include ip/skip_previous.puml
!include ip/skip_previous_circle.puml
!include ip/skip_previous_circle_outline.puml
!include ip/skull.puml
!include ip/skype.puml
!include ip/skype_business.puml
!include ip/slack.puml
!include ip/sleep.puml
!include ip/sleep_off.puml
!include ip/smoking.puml
!include ip/smoking_off.puml
!include ip/snapchat.puml
!include ip/snowflake.puml
!include ip/snowman.puml
!include ip/soccer.puml
!include ip/soccer_field.puml
!include ip/sofa.puml
!include ip/solid.puml
!include ip/sort.puml
!include ip/sort_alphabetical.puml
!include ip/sort_ascending.puml
!include ip/sort_descending.puml
!include ip/sort_numeric.puml
!include ip/sort_variant.puml
!include ip/soundcloud.puml
!include ip/source_branch.puml
!include ip/source_commit.puml
!include ip/source_commit_end.puml
!include ip/source_commit_end_local.puml
!include ip/source_commit_local.puml
!include ip/source_commit_next_local.puml
!include ip/source_commit_start.puml
!include ip/source_commit_start_next_local.puml
!include ip/source_fork.puml
!include ip/source_merge.puml
!include ip/source_pull.puml
!include ip/soy_sauce.puml
!include ip/speaker.puml
!include ip/speaker_off.puml
!include ip/speaker_wireless.puml
!include ip/speedometer.puml
!include ip/spellcheck.puml
!include ip/spotify.puml
!include ip/spotlight.puml
!include ip/spotlight_beam.puml
!include ip/spray.puml
!include ip/spreadsheet.puml
!include ip/square.puml
!include ip/square_inc.puml
!include ip/square_inc_cash.puml
!include ip/square_outline.puml
!include ip/square_root.puml
!include ip/stackexchange.puml
!include ip/stackoverflow.puml
!include ip/stadium.puml
!include ip/stairs.puml
!include ip/standard_definition.puml
!include ip/star.puml
!include ip/star_circle.puml
!include ip/star_half.puml
!include ip/star_of_david.puml
!include ip/star_off.puml
!include ip/star_outline.puml
!include ip/steam.puml
!include ip/steering.puml
!include ip/step_backward.puml
!include ip/step_backward_2.puml
!include ip/step_forward.puml
!include ip/step_forward_2.puml
!include ip/stethoscope.puml
!include ip/sticker.puml
!include ip/sticker_emoji.puml
!include ip/stocking.puml
!include ip/stop.puml
!include ip/stop_circle.puml
!include ip/stop_circle_outline.puml
!include ip/store.puml
!include ip/store_24_hour.puml
!include ip/stove.puml
!include ip/subdirectory_arrow_left.puml
!include ip/subdirectory_arrow_right.puml
!include ip/subway.puml
!include ip/subway_variant.puml
!include ip/summit.puml
!include ip/sunglasses.puml
!include ip/surround_sound.puml
!include ip/surround_sound_2_0.puml
!include ip/surround_sound_3_1.puml
!include ip/surround_sound_5_1.puml
!include ip/surround_sound_7_1.puml
!include ip/svg.puml
!include ip/swap_horizontal.puml
!include ip/swap_vertical.puml
!include ip/swim.puml
!include ip/switch.puml
!include ip/sword.puml
!include ip/sword_cross.puml
!include ip/sync.puml
!include ip/sync_alert.puml
!include ip/sync_off.puml
!include ip/tab.puml
!include ip/tab_plus.puml
!include ip/tab_unselected.puml
!include ip/table.puml
!include ip/table_column.puml
!include ip/table_column_plus_after.puml
!include ip/table_column_plus_before.puml
!include ip/table_column_remove.puml
!include ip/table_column_width.puml
!include ip/table_edit.puml
!include ip/table_large.puml
!include ip/table_of_contents.puml
!include ip/table_row.puml
!include ip/table_row_height.puml
!include ip/table_row_plus_after.puml
!include ip/table_row_plus_before.puml
!include ip/table_row_remove.puml
!include ip/table_settings.puml
!include ip/tablet.puml
!include ip/tablet_android.puml
!include ip/tablet_ipad.puml
!include ip/taco.puml
!include ip/tag.puml
!include ip/tag_faces.puml
!include ip/tag_heart.puml
!include ip/tag_multiple.puml
!include ip/tag_outline.puml
!include ip/tag_plus.puml
!include ip/tag_remove.puml
!include ip/tag_text_outline.puml
!include ip/target.puml
!include ip/taxi.puml
!include ip/teamviewer.puml
!include ip/telegram.puml
!include ip/television.puml
!include ip/television_box.puml
!include ip/television_classic.puml
!include ip/television_classic_off.puml
!include ip/television_guide.puml
!include ip/television_off.puml
!include ip/temperature_celsius.puml
!include ip/temperature_fahrenheit.puml
!include ip/temperature_kelvin.puml
!include ip/tennis.puml
!include ip/tent.puml
!include ip/terrain.puml
!include ip/test_tube.puml
!include ip/text_shadow.puml
!include ip/text_to_speech.puml
!include ip/text_to_speech_off.puml
!include ip/textbox.puml
!include ip/textbox_password.puml
!include ip/texture.puml
!include ip/theater.puml
!include ip/theme_light_dark.puml
!include ip/thermometer.puml
!include ip/thermometer_lines.puml
!include ip/thought_bubble.puml
!include ip/thought_bubble_outline.puml
!include ip/thumb_down.puml
!include ip/thumb_down_outline.puml
!include ip/thumb_up.puml
!include ip/thumb_up_outline.puml
!include ip/thumbs_up_down.puml
!include ip/ticket.puml
!include ip/ticket_account.puml
!include ip/ticket_confirmation.puml
!include ip/ticket_percent.puml
!include ip/tie.puml
!include ip/tilde.puml
!include ip/timelapse.puml
!include ip/timer.puml
!include ip/timer_10.puml
!include ip/timer_3.puml
!include ip/timer_off.puml
!include ip/timer_sand.puml
!include ip/timer_sand_empty.puml
!include ip/timer_sand_full.puml
!include ip/timetable.puml
!include ip/toggle_switch.puml
!include ip/toggle_switch_off.puml
!include ip/tooltip.puml
!include ip/tooltip_edit.puml
!include ip/tooltip_image.puml
!include ip/tooltip_outline.puml
!include ip/tooltip_outline_plus.puml
!include ip/tooltip_text.puml
!include ip/tooth.puml
!include ip/tor.puml
!include ip/tower_beach.puml
!include ip/tower_fire.puml
!include ip/towing.puml
!include ip/trackpad.puml
!include ip/traffic_light.puml
!include ip/train.puml
!include ip/tram.puml
!include ip/transcribe.puml
!include ip/transcribe_close.puml
!include ip/transfer.puml
!include ip/transit_transfer.puml
!include ip/translate.puml
!include ip/trash.puml
!include ip/treasure_chest.puml
!include ip/tree.puml
!include ip/trello.puml
!include ip/trending_down.puml
!include ip/trending_neutral.puml
!include ip/trending_up.puml
!include ip/triangle.puml
!include ip/triangle_outline.puml
!include ip/trophy_outline.puml
!include ip/trophy_variant_outline.puml
!include ip/truck.puml
!include ip/truck_delivery.puml
!include ip/truck_fast.puml
!include ip/truck_trailer.puml
!include ip/tshirt_crew.puml
!include ip/tshirt_v.puml
!include ip/tumblr.puml
!include ip/tumblr_reblog.puml
!include ip/tune.puml
!include ip/tune_vertical.puml
!include ip/twitch.puml
!include ip/twitter.puml
!include ip/twitter_box.puml
!include ip/twitter_circle.puml
!include ip/twitter_retweet.puml
!include ip/uber.puml
!include ip/ubuntu.puml
!include ip/ultra_high_definition.puml
!include ip/umbraco.puml
!include ip/umbrella.puml
!include ip/umbrella_outline.puml
!include ip/undo.puml
!include ip/undo_variant.puml
!include ip/unfold_less_horizontal.puml
!include ip/unfold_less_vertical.puml
!include ip/unfold_more_horizontal.puml
!include ip/unfold_more_vertical.puml
!include ip/ungroup.puml
!include ip/unity.puml
!include ip/untappd.puml
!include ip/update.puml
!include ip/upload.puml
!include ip/upload_multiple.puml
!include ip/upload_network.puml
!include ip/usb.puml
!include ip/van_passenger.puml
!include ip/van_utility.puml
!include ip/vanish.puml
!include ip/vector_arrange_above.puml
!include ip/vector_arrange_below.puml
!include ip/vector_circle.puml
!include ip/vector_circle_variant.puml
!include ip/vector_combine.puml
!include ip/vector_curve.puml
!include ip/vector_difference.puml
!include ip/vector_difference_ab.puml
!include ip/vector_difference_ba.puml
!include ip/vector_intersection.puml
!include ip/vector_line.puml
!include ip/vector_point.puml
!include ip/vector_polygon.puml
!include ip/vector_polyline.puml
!include ip/vector_radius.puml
!include ip/vector_rectangle.puml
!include ip/vector_selection.puml
!include ip/vector_square.puml
!include ip/vector_triangle.puml
!include ip/vector_union.puml
!include ip/venmo.puml
!include ip/verified.puml
!include ip/vibrate.puml
!include ip/video.puml
!include ip/video_3d.puml
!include ip/video_4k_box.puml
!include ip/video_input_antenna.puml
!include ip/video_input_component.puml
!include ip/video_input_hdmi.puml
!include ip/video_input_svideo.puml
!include ip/video_off.puml
!include ip/video_switch.puml
!include ip/view_agenda.puml
!include ip/view_array.puml
!include ip/view_carousel.puml
!include ip/view_column.puml
!include ip/view_dashboard.puml
!include ip/view_dashboard_variant.puml
!include ip/view_day.puml
!include ip/view_grid.puml
!include ip/view_headline.puml
!include ip/view_list.puml
!include ip/view_module.puml
!include ip/view_parallel.puml
!include ip/view_quilt.puml
!include ip/view_sequential.puml
!include ip/view_stream.puml
!include ip/view_week.puml
!include ip/vimeo.puml
!include ip/vine.puml
!include ip/violin.puml
!include ip/visualstudio.puml
!include ip/vk.puml
!include ip/vk_box.puml
!include ip/vk_circle.puml
!include ip/vlc.puml
!include ip/voice.puml
!include ip/voicemail.puml
!include ip/volume.puml
!include ip/volume_high.puml
!include ip/volume_low.puml
!include ip/volume_medium.puml
!include ip/volume_minus.puml
!include ip/volume_mute.puml
!include ip/volume_off.puml
!include ip/volume_plus.puml
!include ip/vpn.puml
!include ip/vuejs.puml
!include ip/walk.puml
!include ip/wall.puml
!include ip/wallet.puml
!include ip/wallet_giftcard.puml
!include ip/wallet_membership.puml
!include ip/wallet_travel.puml
!include ip/wan.puml
!include ip/washing_machine.puml
!include ip/watch.puml
!include ip/watch_export.puml
!include ip/watch_import.puml
!include ip/watch_vibrate.puml
!include ip/water.puml
!include ip/water_off.puml
!include ip/water_percent.puml
!include ip/water_pump.puml
!include ip/watermark.puml
!include ip/waves.puml
!include ip/weather_cloudy.puml
!include ip/weather_fog.puml
!include ip/weather_hail.puml
!include ip/weather_lightning.puml
!include ip/weather_lightning_rainy.puml
!include ip/weather_night.puml
!include ip/weather_partlycloudy.puml
!include ip/weather_pouring.puml
!include ip/weather_rainy.puml
!include ip/weather_snowy.puml
!include ip/weather_snowy_rainy.puml
!include ip/weather_sunny.puml
!include ip/weather_sunset.puml
!include ip/weather_sunset_down.puml
!include ip/weather_sunset_up.puml
!include ip/weather_windy.puml
!include ip/weather_windy_variant.puml
!include ip/web.puml
!include ip/webcam.puml
!include ip/webhook.puml
!include ip/webpack.puml
!include ip/wechat.puml
!include ip/weight.puml
!include ip/weight_kilogram.puml
!include ip/whatsapp.puml
!include ip/wheelchair_accessibility.puml
!include ip/white_balance_auto.puml
!include ip/white_balance_incandescent.puml
!include ip/white_balance_iridescent.puml
!include ip/white_balance_sunny.puml
!include ip/widgets.puml
!include ip/wifi.puml
!include ip/wifi_off.puml
!include ip/wii.puml
!include ip/wiiu.puml
!include ip/wikipedia.puml
!include ip/window_close.puml
!include ip/window_closed.puml
!include ip/window_maximize.puml
!include ip/window_minimize.puml
!include ip/window_open.puml
!include ip/window_restore.puml
!include ip/windows.puml
!include ip/wordpress.puml
!include ip/worker.puml
!include ip/wrench.puml
!include ip/wunderlist.puml
!include ip/xamarin.puml
!include ip/xamarin_outline.puml
!include ip/xaml.puml
!include ip/xbox.puml
!include ip/xbox_controller.puml
!include ip/xbox_controller_battery_alert.puml
!include ip/xbox_controller_battery_empty.puml
!include ip/xbox_controller_battery_full.puml
!include ip/xbox_controller_battery_low.puml
!include ip/xbox_controller_battery_medium.puml
!include ip/xbox_controller_battery_unknown.puml
!include ip/xbox_controller_off.puml
!include ip/xda.puml
!include ip/xing.puml
!include ip/xing_box.puml
!include ip/xing_circle.puml
!include ip/xml.puml
!include ip/xmpp.puml
!include ip/yammer.puml
!include ip/yeast.puml
!include ip/yelp.puml
!include ip/yin_yang.puml
!include ip/youtube.puml
!include ip/youtube_creator_studio.puml
!include ip/youtube_gaming.puml
!include ip/youtube_play.puml
!include ip/youtube_tv.puml
!include ip/zip_box.puml
listsprites
@enduml
