@startuml Templates For Use In Other Diagrams
title Templates For Use In Other Diagrams

' Use `$rootPath` to define how many directories to traverse up where you'll start including other files.
!$rootPath = ..
!startsub COMMON_INCLUDES
    !includesub $rootPath/utils/common-header.iuml!MAIN
    !includesub $rootPath/utils/functions.iuml!MAIN
!endsub

' Not sending the $rootPath here since it should be defined in the diagram including this one.
!startsub COMMON_PARTICIPANTS
    !if %not(%variable_exists("$NO_ACTORS"))
        !includesub $rootPath/utils/participants.yourDomainHere/common.participants.actors.iuml!MAIN
    !endif
    !if %not(%variable_exists("$NO_INFRA"))
        !includesub $rootPath/utils/participants.yourDomainHere/common.participants.infrastructure.iuml!MAIN
    !endif
    !if %not(%variable_exists("$NO_CLUSTER"))
        !includesub $rootPath/utils/participants.yourDomainHere/common.participants.cluster.iuml!MAIN
    !endif
!endsub

!startsub COMMON_TEST
user -> api: If you can see this, you didn't include ONLY the sub-template.
!endsub
@enduml