@startuml

' Assign a THEME from your PUML file instead of individual styles.
' Options are: [ DEFAULT | NATURAL | NATURAL_DARK | NATURAL_DARK_ALT | LIGHT | DARK | MIDNIGHT ]
!define STYLE_THEME DEFAULT

' Use `$rootPath` to define how many directories to traverse up where you'll start including other files.
!$rootPath = ..

!startsub MAIN
!pragma teoz true
' !pragma layout smetana

autonumber "<color:Gray>[ </color><color:Red> 0 </color><color:Gray> ]</color>"

!include $rootPath/style/stylesheet.iuml

footer Rendered on ""%date("'**'yyyy.MM.dd'**'")"" @ ""%date("'**'HH:mm'**'")""
legend right 
    <#FFFFFF,#FFFFFF>|= |= Participant Type |
    |<back:#ddffdd>     </back>| First Type |
    |<back:#ffdddd>     </back>| Second Type|
    |<back:#Yellow>     </back>| Third Type|
endlegend

!$aiml = $rootPath/sprites/AI_and_Machine_Learning
!$iot = $rootPath/sprites/iot
!$dev = $rootPath/sprites/device

%set_variable_value("$remPuml", "https://raw.githubusercontent.com/plantuml/plantuml-stdlib/refs/heads/master/stdlib/logos")
!include $remPuml/nestjs.puml
!include $remPuml/nvidia.puml
%set_variable_value("$aiPuml", "https://raw.githubusercontent.com/plantuml/plantuml-stdlib/refs/heads/master/stdlib/gcp")
' !include $aiPuml/AutoML_Translation.puml
!include $aiPuml/GCPRaw.puml

!include <logos/react>
!include <office/devices/hard_disk>
!include <logos/graphql>
!include <logos/elasticsearch>
!include <gcp/AI_and_Machine_Learning/AI_Platform_Data_Labeling_Service>
!include <gcp/AI_and_Machine_Learning/AI_Platform>
!include <gcp/AI_and_Machine_Learning/Cloud_Inference_API>
!include <gcp/Networking/Cloud_DNS>
!include <osa/lifecycle/lifecycle>
!include <logos/api-ai>
!include <logos/sqlite>
!include <logos/sqldep>
!include <tupadr3/font-awesome/battery_half>
!include <tupadr3/font-awesome/circle>
!include <tupadr3/font-awesome/file_excel_o>
!include <tupadr3/font-awesome/table>
!include <tupadr3/font-awesome/industry>
!include <tupadr3/font-awesome/info>
!include <tupadr3/font-awesome/question_circle_o>
!include <tupadr3/font-awesome/laptop>
!include <tupadr3/font-awesome-5/portrait>
!include <tupadr3/font-awesome-5/user>
!include <tupadr3/font-awesome-5/user_secret>
!include <tupadr3/font-awesome-5/user_tie>
!include <tupadr3/font-awesome-5/user_ninja>
!include <tupadr3/font-awesome-5/user_astronaut>
!include <tupadr3/font-awesome-5/chart_bar>
!include <tupadr3/font-awesome-5/door_open>
!include <tupadr3/font-awesome-5/door_closed>
!include <tupadr3/font-awesome-5/id_badge>
!include <tupadr3/font-awesome-5/poo>
!include <tupadr3/font-awesome-5/sim_card>
!include <tupadr3/font-awesome-5/sd_card>
!include <tupadr3/font-awesome-5/fast_forward>
!include <tupadr3/font-awesome-5/fast_backward>
!include <tupadr3/font-awesome/floppy_o>
!include <tupadr3/font-awesome/usb>
!include <tupadr3/common>
!include <tupadr3/devicons/compass>
!include <tupadr3/devicons/database>
!include <tupadr3/devicons/python>
!include <tupadr3/devicons/raspberry_pi>
!include <tupadr3/devicons2/mongodb>
!include <tupadr3/devicons2/redis>
!include <tupadr3/devicons2/linux>
' !include <tupadr3/devicons2/tensorflow_line>
!include <tupadr3/material/memory>
!include <logos/campaignmonitor-icon>
!include <tupadr3/devicons/google_analytics>
!include <tupadr3/material/wifi>
!include <tupadr3/devicons/angular>
!include <tupadr3/devicons/nodejs_small>
!include <tupadr3/material/touch_app>
!include <tupadr3/material/record_voice_over>
!include <tupadr3/material/computer>
!include <tupadr3/material/keyboard_voice>
!include <tupadr3/material/photo_camera>
!include <tupadr3/material/developer_mode>
!include <tupadr3/material/folder>
!include <tupadr3/material/power>
!include <tupadr3/material/speaker>
!include <tupadr3/material/check>
!include <tupadr3/material/check_box>
!include <tupadr3/material/check_circle>
!include <tupadr3/material/fingerprint>
!include <tupadr3/material/nfc>
!include <tupadr3/material/person>
!include <material/fast_forward_outline>
!include <material/rewind_outline>
!include <material/led_on>
!include <material/nfc>
!include <material/nfc_tap>
!include $aiml/Cloud_Speech_to_Text.puml
!include $iot/Cloud_IoT_Core.puml
!include $dev/device_lcd_monitor.puml
!include $dev/dock.puml
!include <logos/nvidia>
!include <cloudinsight/left>
!include <cloudinsight/right>
!include <cloudinsight/keycloak>
!endsub

participant a as "Should Not\nSee Me"
participant b as "Me Either"
participant c as "Third Party"
note over a: Go Away.
a -> b: This too.
& c --> b: Inline stuff.
@enduml
