@startuml
!define pc /Volumes/SRC/plantuml-stdlib/tupadr3
!include pc/common.puml
' !define ip /Volumes/SRC/plantuml-stdlib/tupadr3/devicons
' !include ip/android.puml
' !include ip/angular.puml
' !include ip/appcelerator.puml
' !include ip/apple.puml
' !include ip/appstore.puml
' !include ip/aptana.puml
' !include ip/asterisk.puml
' !include ip/atlassian.puml
' !include ip/atom.puml
' !include ip/aws.puml
' !include ip/backbone.puml
' !include ip/bing_small.puml
' !include ip/bintray.puml
' !include ip/bitbucket.puml
' !include ip/blackberry.puml
' !include ip/bootstrap.puml
' !include ip/bower.puml
' !include ip/brackets.puml
' !include ip/bugsense.puml
' !include ip/celluloid.puml
' !include ip/chrome.puml
' !include ip/cisco.puml
' !include ip/clojure.puml
' !include ip/clojure_alt.puml
' !include ip/cloud9.puml
' !include ip/coda.puml
' !include ip/code.puml
' !include ip/code_badge.puml
' !include ip/codeigniter.puml
' !include ip/codepen.puml
' !include ip/codrops.puml
' !include ip/coffeescript.puml
' !include ip/compass.puml
' !include ip/composer.puml
' !include ip/creativecommons.puml
' !include ip/creativecommons_badge.puml
' !include ip/css3.puml
' !include ip/css3_full.puml
' !include ip/css_tricks.puml
' !include ip/cssdeck.puml
' !include ip/dart.puml
' !include ip/database.puml
' !include ip/debian.puml
' !include ip/digital_ocean.puml
' !include ip/django.puml
' !include ip/dlang.puml
' !include ip/docker.puml
' !include ip/doctrine.puml
' !include ip/dojo.puml
' !include ip/dotnet.puml
' !include ip/dreamweaver.puml
' !include ip/dropbox.puml
' !include ip/drupal.puml
' !include ip/eclipse.puml
' !include ip/ember.puml
' !include ip/envato.puml
' !include ip/erlang.puml
' !include ip/extjs.puml
' !include ip/firebase.puml
' !include ip/firefox.puml
' !include ip/fsharp.puml
' !include ip/ghost.puml
' !include ip/ghost_small.puml
' !include ip/git.puml
' !include ip/git_branch.puml
' !include ip/git_commit.puml
' !include ip/git_compare.puml
' !include ip/git_merge.puml
' !include ip/git_pull_request.puml
' !include ip/github.puml
' !include ip/github_alt.puml
' !include ip/github_badge.puml
' !include ip/github_full.puml
' !include ip/gnu.puml
' !include ip/go.puml
' !include ip/google_analytics.puml
' !include ip/google_cloud_platform.puml
' !include ip/google_drive.puml
' !include ip/grails.puml
' !include ip/groovy.puml
' !include ip/grunt.puml
' !include ip/gulp.puml
' !include ip/hackernews.puml
' !include ip/haskell.puml
' !include ip/heroku.puml
' !include ip/html5.puml
' !include ip/html5_3d_effects.puml
' !include ip/html5_connectivity.puml
' !include ip/html5_device_access.puml
' !include ip/html5_multimedia.puml
' !include ip/ie.puml
' !include ip/illustrator.puml
' !include ip/intellij.puml
' !include ip/ionic.puml
' !include ip/java.puml
' !include ip/javascript.puml
' !include ip/javascript_badge.puml
' !include ip/javascript_shield.puml
' !include ip/jekyll_small.puml
' !include ip/jenkins.puml
' !include ip/jira.puml
' !include ip/joomla.puml
' !include ip/jquery.puml
' !include ip/jquery_ui.puml
' !include ip/komodo.puml
' !include ip/krakenjs.puml
' !include ip/krakenjs_badge.puml
' !include ip/laravel.puml
' !include ip/less.puml
' !include ip/linux.puml
' !include ip/magento.puml
' !include ip/mailchimp.puml
' !include ip/markdown.puml
' !include ip/materializecss.puml
' !include ip/meteor.puml
' !include ip/meteorfull.puml
' !include ip/mitlicence.puml
' !include ip/modernizr.puml
' !include ip/mongodb.puml
' !include ip/mootools.puml
' !include ip/mootools_badge.puml
' !include ip/mozilla.puml
' !include ip/msql_server.puml
' !include ip/mysql.puml
' !include ip/nancy.puml
' !include ip/netbeans.puml
' !include ip/netmagazine.puml
' !include ip/nginx.puml
' !include ip/nodejs.puml
' !include ip/nodejs_small.puml
' !include ip/npm.puml
' !include ip/onedrive.puml
' !include ip/openshift.puml
' !include ip/opensource.puml
' !include ip/opera.puml
' !include ip/perl.puml
' !include ip/phonegap.puml
' !include ip/photoshop.puml
' !include ip/php.puml
' !include ip/postgresql.puml
' !include ip/prolog.puml
' !include ip/python.puml
' !include ip/rackspace.puml
' !include ip/raphael.puml
' !include ip/raspberry_pi.puml
' !include ip/react.puml
' !include ip/redhat.puml
' !include ip/redis.puml
' !include ip/requirejs.puml
' !include ip/responsive.puml
' !include ip/ruby.puml
' !include ip/ruby_on_rails.puml
' !include ip/ruby_rough.puml
' !include ip/rust.puml
' !include ip/safari.puml
' !include ip/sass.puml
' !include ip/scala.puml
' !include ip/scriptcs.puml
' !include ip/scrum.puml
' !include ip/senchatouch.puml
' !include ip/sizzlejs.puml
' !include ip/smashing_magazine.puml
' !include ip/snap_svg.puml
' !include ip/sqllite.puml
' !include ip/stackoverflow.puml
' !include ip/streamline.puml
' !include ip/stylus.puml
' !include ip/sublime.puml
' !include ip/swift.puml
' !include ip/symfony.puml
' !include ip/symfony_badge.puml
' !include ip/techcrunch.puml
' !include ip/terminal.puml
' !include ip/terminal_badge.puml
' !include ip/travis.puml
' !include ip/trello.puml
' !include ip/typo3.puml
' !include ip/ubuntu.puml
' !include ip/uikit.puml
' !include ip/unity_small.puml
' !include ip/vim.puml
' !include ip/visualstudio.puml
' !include ip/w3c.puml
' !include ip/webplatform.puml
' !include ip/windows.puml
' !include ip/wordpress.puml
' !include ip/yahoo.puml
' !include ip/yahoo_small.puml
' !include ip/yeoman.puml
' !include ip/yii.puml
' !include ip/zend.puml

listsprites

@enduml
