@startuml
!define pc /Volumes/SRC/plantuml-stdlib/tupadr3
!include pc/common.puml
!define ip /Volumes/SRC/plantuml-stdlib/tupadr3/devicons!include ip/aarch64.puml
!include ip/aftereffects.puml
!include ip/amazonwebservices_original.puml
!include ip/amazonwebservices_wordmark.puml
!include ip/android.puml
!include ip/android_wordmark.puml
!include ip/angularjs.puml
!include ip/angularjs_wordmark.puml
!include ip/apache.puml
!include ip/apache_line.puml
!include ip/apache_line_wordmark.puml
!include ip/apache_wordmark.puml
!include ip/appcelerator_original.puml
!include ip/appcelerator_wordmark.puml
!include ip/apple_original.puml
!include ip/appwrite.puml
!include ip/appwrite_wordmark.puml
!include ip/atom_original.puml
!include ip/atom_original_wordmark.puml
!include ip/babel.puml
!include ip/backbonejs.puml
!include ip/backbonejs_wordmark.puml
!include ip/bash.puml
!include ip/behance.puml
!include ip/behance_wordmark.puml
!include ip/bitbucket_original.puml
!include ip/bitbucket_original_wordmark.puml
!include ip/bootstrap.puml
!include ip/bootstrap_wordmark.puml
!include ip/bower.puml
!include ip/bower_line.puml
!include ip/bower_line_wordmark.puml
!include ip/bower_wordmark.puml
!include ip/bulma.puml
!include ip/c.puml
!include ip/c_line.puml
!include ip/cakephp.puml
!include ip/cakephp_wordmark.puml
!include ip/ceylon.puml
!include ip/chrome.puml
!include ip/chrome_wordmark.puml
!include ip/circleci.puml
!include ip/circleci_wordmark.puml
!include ip/clojure_line.puml
!include ip/clojurescript.puml
!include ip/codecov.puml
!include ip/codeigniter.puml
!include ip/codeigniter_wordmark.puml
!include ip/codepen.puml
!include ip/codepen_original_wordmark.puml
!include ip/coffeescript_original.puml
!include ip/coffeescript_original_wordmark.puml
!include ip/composer_line.puml
!include ip/composer_line_wordmark.puml
!include ip/confluence_original.puml
!include ip/confluence_original_wordmark.puml
!include ip/couchdb.puml
!include ip/couchdb_wordmark.puml
!include ip/cplusplus.puml
!include ip/cplusplus_line.puml
!include ip/crystal_original.puml
!include ip/crystal_original_wordmark.puml
!include ip/csharp.puml
!include ip/csharp_line.puml
!include ip/css3.puml
!include ip/css3_wordmark.puml
!include ip/cucumber.puml
!include ip/cucumber_wordmark.puml
!include ip/d3js.puml
!include ip/d3js_original.puml
!include ip/dart.puml
!include ip/dart_wordmark.puml
!include ip/debian.puml
!include ip/debian_wordmark.puml
!include ip/devicon.puml
!include ip/devicon_wordmark.puml
!include ip/digitalocean.puml
!include ip/digitalocean_wordmark.puml
!include ip/django.puml
!include ip/django_line.puml
!include ip/docker.puml
!include ip/docker_wordmark.puml
!include ip/doctrine.puml
!include ip/doctrine_line.puml
!include ip/doctrine_line_wordmark.puml
!include ip/doctrine_wordmark.puml
!include ip/dot_net.puml
!include ip/dot_net_wordmark.puml
!include ip/dotnetcore.puml
!include ip/drupal.puml
!include ip/drupal_wordmark.puml
!include ip/electron_original.puml
!include ip/electron_original_wordmark.puml
!include ip/eleventy.puml
!include ip/elixir.puml
!include ip/elixir_wordmark.puml
!include ip/elm.puml
!include ip/elm_wordmark.puml
!include ip/embeddedc.puml
!include ip/embeddedc_wordmark.puml
!include ip/ember_original_wordmark.puml
!include ip/erlang.puml
!include ip/erlang_wordmark.puml
!include ip/express_original.puml
!include ip/express_original_wordmark.puml
!include ip/facebook.puml
!include ip/figma.puml
!include ip/firebase.puml
!include ip/firebase_wordmark.puml
!include ip/firefox.puml
!include ip/firefox_wordmark.puml
!include ip/flask_original.puml
!include ip/flask_original_wordmark.puml
!include ip/flutter.puml
!include ip/foundation.puml
!include ip/foundation_wordmark.puml
!include ip/fsharp.puml
!include ip/gatling.puml
!include ip/gatling_wordmark.puml
!include ip/gatsby.puml
!include ip/gatsby_wordmark.puml
!include ip/gimp.puml
!include ip/git.puml
!include ip/git_wordmark.puml
!include ip/github_original.puml
!include ip/github_original_wordmark.puml
!include ip/gitlab.puml
!include ip/gitlab_wordmark.puml
!include ip/gitter.puml
!include ip/gitter_wordmark.puml
!include ip/go.puml
!include ip/go_line.puml
!include ip/godot.puml
!include ip/godot_wordmark.puml
!include ip/google.puml
!include ip/google_wordmark.puml
!include ip/googlecloud.puml
!include ip/googlecloud_wordmark.puml
!include ip/gradle.puml
!include ip/gradle_wordmark.puml
!include ip/grails.puml
!include ip/graphql.puml
!include ip/graphql_wordmark.puml
!include ip/groovy.puml
!include ip/grunt.puml
!include ip/grunt_line.puml
!include ip/grunt_line_wordmark.puml
!include ip/grunt_wordmark.puml
!include ip/gulp.puml
!include ip/handlebars.puml
!include ip/handlebars_wordmark.puml
!include ip/haskell.puml
!include ip/haskell_wordmark.puml
!include ip/haxe.puml
!include ip/heroku.puml
!include ip/heroku_line.puml
!include ip/heroku_line_wordmark.puml
!include ip/heroku_wordmark.puml
!include ip/html5.puml
!include ip/html5_wordmark.puml
!include ip/ie10_original.puml
!include ip/illustrator.puml
!include ip/illustrator_line.puml
!include ip/inkscape.puml
!include ip/inkscape_wordmark.puml
!include ip/intellij.puml
!include ip/intellij_wordmark.puml
!include ip/ionic_original.puml
!include ip/ionic_original_wordmark.puml
!include ip/jasmine.puml
!include ip/jasmine_wordmark.puml
!include ip/java.puml
!include ip/java_wordmark.puml
!include ip/javascript.puml
!include ip/jeet.puml
!include ip/jeet_wordmark.puml
!include ip/jenkins.puml
!include ip/jenkins_line.puml
!include ip/jest.puml
!include ip/jetbrains.puml
!include ip/jquery.puml
!include ip/jquery_wordmark.puml
!include ip/julia.puml
!include ip/julia_wordmark.puml
!include ip/jupyter.puml
!include ip/jupyter_wordmark.puml
!include ip/karma.puml
!include ip/knockout_wordmark.puml
!include ip/kotlin.puml
!include ip/kotlin_wordmark.puml
!include ip/krakenjs.puml
!include ip/krakenjs_wordmark.puml
!include ip/kubernetes.puml
!include ip/kubernetes_wordmark.puml
!include ip/labview.puml
!include ip/labview_wordmark.puml
!include ip/laravel.puml
!include ip/laravel_wordmark.puml
!include ip/less_wordmark.puml
!include ip/linkedin.puml
!include ip/linkedin_wordmark.puml
!include ip/linux.puml
!include ip/lua.puml
!include ip/lua_wordmark.puml
!include ip/magento_line.puml
!include ip/magento_original.puml
!include ip/magento_original_wordmark.puml
!include ip/materialui.puml
!include ip/matlab.puml
!include ip/matlab_line.puml
!include ip/meteor.puml
!include ip/meteor_wordmark.puml
!include ip/microsoftsqlserver.puml
!include ip/microsoftsqlserver_wordmark.puml
!include ip/minitab.puml
!include ip/mocha.puml
!include ip/modx.puml
!include ip/modx_wordmark.puml
!include ip/mongodb.puml
!include ip/mongodb_wordmark.puml
!include ip/moodle.puml
!include ip/moodle_wordmark.puml
!include ip/mysql.puml
!include ip/mysql_wordmark.puml
!include ip/nestjs.puml
!include ip/nestjs_wordmark.puml
!include ip/nextjs_line.puml
!include ip/nextjs_original.puml
!include ip/nextjs_original_wordmark.puml
!include ip/nginx_original.puml
!include ip/nixos.puml
!include ip/nixos_wordmark.puml
!include ip/nodejs.puml
!include ip/nodejs_wordmark.puml
!include ip/nodewebkit.puml
!include ip/nodewebkit_line.puml
!include ip/nodewebkit_line_wordmark.puml
!include ip/nodewebkit_wordmark.puml
!include ip/npm_original_wordmark.puml
!include ip/objectivec.puml
!include ip/ocaml.puml
!include ip/ocaml_wordmark.puml
!include ip/oracle_original.puml
!include ip/perl.puml
!include ip/phalcon.puml
!include ip/phoenix.puml
!include ip/phoenix_wordmark.puml
!include ip/photoshop.puml
!include ip/photoshop_line.puml
!include ip/php.puml
!include ip/phpstorm.puml
!include ip/phpstorm_wordmark.puml
!include ip/postgresql.puml
!include ip/postgresql_wordmark.puml
!include ip/premierepro.puml
!include ip/protractor.puml
!include ip/protractor_wordmark.puml
!include ip/pycharm.puml
!include ip/pycharm_wordmark.puml
!include ip/python.puml
!include ip/python_wordmark.puml
!include ip/r.puml
!include ip/r_original.puml
!include ip/rails.puml
!include ip/rails_wordmark.puml
!include ip/raspberrypi_line.puml
!include ip/raspberrypi_line_wordmark.puml
!include ip/react_original.puml
!include ip/react_original_wordmark.puml
!include ip/redhat.puml
!include ip/redhat_wordmark.puml
!include ip/redis.puml
!include ip/redis_wordmark.puml
!include ip/redux_original.puml
!include ip/rocksdb.puml
!include ip/rstudio.puml
!include ip/ruby.puml
!include ip/ruby_wordmark.puml
!include ip/rubymine.puml
!include ip/rubymine_wordmark.puml
!include ip/rust.puml
!include ip/safari.puml
!include ip/safari_line.puml
!include ip/safari_line_wordmark.puml
!include ip/safari_wordmark.puml
!include ip/salesforce.puml
!include ip/sass_original.puml
!include ip/scala.puml
!include ip/scala_wordmark.puml
!include ip/sequelize.puml
!include ip/sequelize_wordmark.puml
!include ip/shopware_original.puml
!include ip/shopware_original_wordmark.puml
!include ip/sketch_line.puml
!include ip/sketch_line_wordmark.puml
!include ip/slack.puml
!include ip/slack_wordmark.puml
!include ip/sourcetree_original.puml
!include ip/sourcetree_original_wordmark.puml
!include ip/spring.puml
!include ip/spring_wordmark.puml
!include ip/spss.puml
!include ip/sqlalchemy.puml
!include ip/sqlalchemy_original_wordmark.puml
!include ip/ssh_original.puml
!include ip/ssh_original_wordmark.puml
!include ip/stylus_original.puml
!include ip/swift.puml
!include ip/swift_wordmark.puml
!include ip/symfony_original.puml
!include ip/symfony_original_wordmark.puml
!include ip/tailwindcss.puml
!include ip/tailwindcss_original_wordmark.puml
!include ip/tensorflow_line.puml
!include ip/tensorflow_line_wordmark.puml
!include ip/tensorflow_original.puml
!include ip/tensorflow_original_wordmark.puml
!include ip/thealgorithms.puml
!include ip/thealgorithms_wordmark.puml
!include ip/tomcat_line.puml
!include ip/tomcat_line_wordmark.puml
!include ip/travis.puml
!include ip/travis_wordmark.puml
!include ip/trello.puml
!include ip/trello_wordmark.puml
!include ip/twitter_original.puml
!include ip/typescript.puml
!include ip/typo3.puml
!include ip/typo3_wordmark.puml
!include ip/ubuntu.puml
!include ip/ubuntu_wordmark.puml
!include ip/unix_original.puml
!include ip/uwsgi.puml
!include ip/vagrant.puml
!include ip/vagrant_wordmark.puml
!include ip/vim.puml
!include ip/visualstudio.puml
!include ip/visualstudio_wordmark.puml
!include ip/vscode.puml
!include ip/vscode_wordmark.puml
!include ip/vuejs.puml
!include ip/vuejs_line.puml
!include ip/vuejs_line_wordmark.puml
!include ip/vuejs_wordmark.puml
!include ip/vuestorefront.puml
!include ip/weblate.puml
!include ip/weblate_wordmark.puml
!include ip/webpack.puml
!include ip/webpack_wordmark.puml
!include ip/webstorm.puml
!include ip/webstorm_wordmark.puml
!include ip/windows8_original.puml
!include ip/windows8_original_wordmark.puml
!include ip/woocommerce.puml
!include ip/woocommerce_wordmark.puml
!include ip/wordpress.puml
!include ip/wordpress_wordmark.puml
!include ip/xd.puml
!include ip/xd_line.puml
!include ip/yarn.puml
!include ip/yarn_wordmark.puml
!include ip/yii.puml
!include ip/yii_wordmark.puml
!include ip/yunohost.puml
!include ip/zend.puml
!include ip/zend_wordmark.puml
!include ip/zig_original.puml
!include ip/zig_wordmark.puml

listsprites
@enduml
