@startuml
!define pc /Volumes/SRC/plantuml-stdlib/tupadr3
!include pc/common.puml
!define ip /Volumes/SRC/plantuml-stdlib/tupadr3/font-awesome-5
!include ip/500px.puml
!include ip/accessible_icon.puml
!include ip/accusoft.puml
!include ip/acquisitions_incorporated.puml
!include ip/ad.puml
!include ip/address_book.puml
!include ip/address_card.puml
!include ip/adjust.puml
!include ip/adn.puml
!include ip/adversal.puml
!include ip/affiliatetheme.puml
!include ip/air_freshener.puml
!include ip/airbnb.puml
!include ip/algolia.puml
!include ip/align_center.puml
!include ip/align_justify.puml
!include ip/align_left.puml
!include ip/align_right.puml
!include ip/alipay.puml
!include ip/allergies.puml
!include ip/amazon.puml
!include ip/amazon_pay.puml
!include ip/ambulance.puml
!include ip/american_sign_language_interpreting.puml
!include ip/amilia.puml
!include ip/anchor.puml
!include ip/android.puml
!include ip/angellist.puml
!include ip/angle_double_down.puml
!include ip/angle_double_left.puml
!include ip/angle_double_right.puml
!include ip/angle_double_up.puml
!include ip/angle_down.puml
!include ip/angle_left.puml
!include ip/angle_right.puml
!include ip/angle_up.puml
!include ip/angry.puml
!include ip/angrycreative.puml
!include ip/angular.puml
!include ip/ankh.puml
!include ip/app_store.puml
!include ip/app_store_ios.puml
!include ip/apper.puml
!include ip/apple.puml
!include ip/apple_alt.puml
!include ip/apple_pay.puml
!include ip/archive.puml
!include ip/archway.puml
!include ip/arrow_alt_circle_down.puml
!include ip/arrow_alt_circle_left.puml
!include ip/arrow_alt_circle_right.puml
!include ip/arrow_alt_circle_up.puml
!include ip/arrow_circle_down.puml
!include ip/arrow_circle_left.puml
!include ip/arrow_circle_right.puml
!include ip/arrow_circle_up.puml
!include ip/arrow_down.puml
!include ip/arrow_left.puml
!include ip/arrow_right.puml
!include ip/arrow_up.puml
!include ip/arrows_alt.puml
!include ip/arrows_alt_h.puml
!include ip/arrows_alt_v.puml
!include ip/artstation.puml
!include ip/assistive_listening_systems.puml
!include ip/asterisk.puml
!include ip/asymmetrik.puml
!include ip/at.puml
!include ip/atlas.puml
!include ip/atlassian.puml
!include ip/atom.puml
!include ip/audible.puml
!include ip/audio_description.puml
!include ip/autoprefixer.puml
!include ip/avianex.puml
!include ip/aviato.puml
!include ip/award.puml
!include ip/aws.puml
!include ip/baby.puml
!include ip/baby_carriage.puml
!include ip/backspace.puml
!include ip/backward.puml
!include ip/bacon.puml
!include ip/bacteria.puml
!include ip/bacterium.puml
!include ip/bahai.puml
!include ip/balance_scale.puml
!include ip/balance_scale_left.puml
!include ip/balance_scale_right.puml
!include ip/ban.puml
!include ip/band_aid.puml
!include ip/bandcamp.puml
!include ip/barcode.puml
!include ip/bars.puml
!include ip/baseball_ball.puml
!include ip/basketball_ball.puml
!include ip/bath.puml
!include ip/battery_empty.puml
!include ip/battery_full.puml
!include ip/battery_half.puml
!include ip/battery_quarter.puml
!include ip/battery_three_quarters.puml
!include ip/battle_net.puml
!include ip/bed.puml
!include ip/beer.puml
!include ip/behance.puml
!include ip/behance_square.puml
!include ip/bell.puml
!include ip/bell_slash.puml
!include ip/bezier_curve.puml
!include ip/bible.puml
!include ip/bicycle.puml
!include ip/biking.puml
!include ip/bimobject.puml
!include ip/binoculars.puml
!include ip/biohazard.puml
!include ip/birthday_cake.puml
!include ip/bitbucket.puml
!include ip/bitcoin.puml
!include ip/bity.puml
!include ip/black_tie.puml
!include ip/blackberry.puml
!include ip/blender.puml
!include ip/blender_phone.puml
!include ip/blind.puml
!include ip/blog.puml
!include ip/blogger.puml
!include ip/blogger_b.puml
!include ip/bluetooth.puml
!include ip/bluetooth_b.puml
!include ip/bold.puml
!include ip/bolt.puml
!include ip/bomb.puml
!include ip/bone.puml
!include ip/bong.puml
!include ip/book.puml
!include ip/book_dead.puml
!include ip/book_medical.puml
!include ip/book_open.puml
!include ip/book_reader.puml
!include ip/bookmark.puml
!include ip/bootstrap.puml
!include ip/border_all.puml
!include ip/border_none.puml
!include ip/border_style.puml
!include ip/bowling_ball.puml
!include ip/box.puml
!include ip/box_open.puml
!include ip/box_tissue.puml
!include ip/boxes.puml
!include ip/braille.puml
!include ip/brain.puml
!include ip/bread_slice.puml
!include ip/briefcase.puml
!include ip/briefcase_medical.puml
!include ip/broadcast_tower.puml
!include ip/broom.puml
!include ip/brush.puml
!include ip/btc.puml
!include ip/buffer.puml
!include ip/bug.puml
!include ip/building.puml
!include ip/bullhorn.puml
!include ip/bullseye.puml
!include ip/burn.puml
!include ip/buromobelexperte.puml
!include ip/bus.puml
!include ip/bus_alt.puml
!include ip/business_time.puml
!include ip/buy_n_large.puml
!include ip/buysellads.puml
!include ip/calculator.puml
!include ip/calendar.puml
!include ip/calendar_alt.puml
!include ip/calendar_check.puml
!include ip/calendar_day.puml
!include ip/calendar_minus.puml
!include ip/calendar_plus.puml
!include ip/calendar_times.puml
!include ip/calendar_week.puml
!include ip/camera.puml
!include ip/camera_retro.puml
!include ip/campground.puml
!include ip/canadian_maple_leaf.puml
!include ip/candy_cane.puml
!include ip/cannabis.puml
!include ip/capsules.puml
!include ip/car.puml
!include ip/car_alt.puml
!include ip/car_battery.puml
!include ip/car_crash.puml
!include ip/car_side.puml
!include ip/caravan.puml
!include ip/caret_down.puml
!include ip/caret_left.puml
!include ip/caret_right.puml
!include ip/caret_square_down.puml
!include ip/caret_square_left.puml
!include ip/caret_square_right.puml
!include ip/caret_square_up.puml
!include ip/caret_up.puml
!include ip/carrot.puml
!include ip/cart_arrow_down.puml
!include ip/cart_plus.puml
!include ip/cash_register.puml
!include ip/cat.puml
!include ip/cc_amazon_pay.puml
!include ip/cc_amex.puml
!include ip/cc_apple_pay.puml
!include ip/cc_diners_club.puml
!include ip/cc_discover.puml
!include ip/cc_jcb.puml
!include ip/cc_mastercard.puml
!include ip/cc_paypal.puml
!include ip/cc_stripe.puml
!include ip/cc_visa.puml
!include ip/centercode.puml
!include ip/centos.puml
!include ip/certificate.puml
!include ip/chair.puml
!include ip/chalkboard.puml
!include ip/chalkboard_teacher.puml
!include ip/charging_station.puml
!include ip/chart_area.puml
!include ip/chart_bar.puml
!include ip/chart_line.puml
!include ip/chart_pie.puml
!include ip/check.puml
!include ip/check_circle.puml
!include ip/check_double.puml
!include ip/check_square.puml
!include ip/cheese.puml
!include ip/chess.puml
!include ip/chess_bishop.puml
!include ip/chess_board.puml
!include ip/chess_king.puml
!include ip/chess_knight.puml
!include ip/chess_pawn.puml
!include ip/chess_queen.puml
!include ip/chess_rook.puml
!include ip/chevron_circle_down.puml
!include ip/chevron_circle_left.puml
!include ip/chevron_circle_right.puml
!include ip/chevron_circle_up.puml
!include ip/chevron_down.puml
!include ip/chevron_left.puml
!include ip/chevron_right.puml
!include ip/chevron_up.puml
!include ip/child.puml
!include ip/chrome.puml
!include ip/chromecast.puml
!include ip/church.puml
!include ip/circle.puml
!include ip/circle_notch.puml
!include ip/city.puml
!include ip/clinic_medical.puml
!include ip/clipboard.puml
!include ip/clipboard_check.puml
!include ip/clipboard_list.puml
!include ip/clock.puml
!include ip/clone.puml
!include ip/closed_captioning.puml
!include ip/cloud.puml
!include ip/cloud_download_alt.puml
!include ip/cloud_meatball.puml
!include ip/cloud_moon.puml
!include ip/cloud_moon_rain.puml
!include ip/cloud_rain.puml
!include ip/cloud_showers_heavy.puml
!include ip/cloud_sun.puml
!include ip/cloud_sun_rain.puml
!include ip/cloud_upload_alt.puml
!include ip/cloudflare.puml
!include ip/cloudscale.puml
!include ip/cloudsmith.puml
!include ip/cloudversify.puml
!include ip/cocktail.puml
!include ip/code.puml
!include ip/code_branch.puml
!include ip/codepen.puml
!include ip/codiepie.puml
!include ip/coffee.puml
!include ip/cog.puml
!include ip/cogs.puml
!include ip/coins.puml
!include ip/columns.puml
!include ip/comment.puml
!include ip/comment_alt.puml
!include ip/comment_dollar.puml
!include ip/comment_dots.puml
!include ip/comment_medical.puml
!include ip/comment_slash.puml
!include ip/comments.puml
!include ip/comments_dollar.puml
!include ip/compact_disc.puml
!include ip/compass.puml
!include ip/compress.puml
!include ip/compress_alt.puml
!include ip/compress_arrows_alt.puml
!include ip/concierge_bell.puml
!include ip/confluence.puml
!include ip/connectdevelop.puml
!include ip/contao.puml
!include ip/cookie.puml
!include ip/cookie_bite.puml
!include ip/copy.puml
!include ip/copyright.puml
!include ip/cotton_bureau.puml
!include ip/couch.puml
!include ip/cpanel.puml
!include ip/creative_commons.puml
!include ip/creative_commons_by.puml
!include ip/creative_commons_nc.puml
!include ip/creative_commons_nc_eu.puml
!include ip/creative_commons_nc_jp.puml
!include ip/creative_commons_nd.puml
!include ip/creative_commons_pd.puml
!include ip/creative_commons_pd_alt.puml
!include ip/creative_commons_remix.puml
!include ip/creative_commons_sa.puml
!include ip/creative_commons_sampling.puml
!include ip/creative_commons_sampling_plus.puml
!include ip/creative_commons_share.puml
!include ip/creative_commons_zero.puml
!include ip/credit_card.puml
!include ip/critical_role.puml
!include ip/crop.puml
!include ip/crop_alt.puml
!include ip/cross.puml
!include ip/crosshairs.puml
!include ip/crow.puml
!include ip/crown.puml
!include ip/crutch.puml
!include ip/css3.puml
!include ip/css3_alt.puml
!include ip/cube.puml
!include ip/cubes.puml
!include ip/cut.puml
!include ip/cuttlefish.puml
!include ip/d_and_d.puml
!include ip/d_and_d_beyond.puml
!include ip/dailymotion.puml
!include ip/dashcube.puml
!include ip/database.puml
!include ip/deaf.puml
!include ip/deezer.puml
!include ip/delicious.puml
!include ip/democrat.puml
!include ip/deploydog.puml
!include ip/deskpro.puml
!include ip/desktop.puml
!include ip/dev.puml
!include ip/deviantart.puml
!include ip/dharmachakra.puml
!include ip/dhl.puml
!include ip/diagnoses.puml
!include ip/diaspora.puml
!include ip/dice.puml
!include ip/dice_d20.puml
!include ip/dice_d6.puml
!include ip/dice_five.puml
!include ip/dice_four.puml
!include ip/dice_one.puml
!include ip/dice_six.puml
!include ip/dice_three.puml
!include ip/dice_two.puml
!include ip/digg.puml
!include ip/digital_ocean.puml
!include ip/digital_tachograph.puml
!include ip/directions.puml
!include ip/discord.puml
!include ip/discourse.puml
!include ip/disease.puml
!include ip/divide.puml
!include ip/dizzy.puml
!include ip/dna.puml
!include ip/dochub.puml
!include ip/docker.puml
!include ip/dog.puml
!include ip/dollar_sign.puml
!include ip/dolly.puml
!include ip/dolly_flatbed.puml
!include ip/donate.puml
!include ip/door_closed.puml
!include ip/door_open.puml
!include ip/dot_circle.puml
!include ip/dove.puml
!include ip/download.puml
!include ip/draft2digital.puml
!include ip/drafting_compass.puml
!include ip/dragon.puml
!include ip/draw_polygon.puml
!include ip/dribbble.puml
!include ip/dribbble_square.puml
!include ip/dropbox.puml
!include ip/drum.puml
!include ip/drum_steelpan.puml
!include ip/drumstick_bite.puml
!include ip/drupal.puml
!include ip/dumbbell.puml
!include ip/dumpster.puml
!include ip/dumpster_fire.puml
!include ip/dungeon.puml
!include ip/dyalog.puml
!include ip/earlybirds.puml
!include ip/ebay.puml
!include ip/edge.puml
!include ip/edge_legacy.puml
!include ip/edit.puml
!include ip/egg.puml
!include ip/eject.puml
!include ip/elementor.puml
!include ip/ellipsis_h.puml
!include ip/ellipsis_v.puml
!include ip/ello.puml
!include ip/ember.puml
!include ip/empire.puml
!include ip/envelope.puml
!include ip/envelope_open.puml
!include ip/envelope_open_text.puml
!include ip/envelope_square.puml
!include ip/envira.puml
!include ip/equals.puml
!include ip/eraser.puml
!include ip/erlang.puml
!include ip/ethereum.puml
!include ip/ethernet.puml
!include ip/etsy.puml
!include ip/euro_sign.puml
!include ip/evernote.puml
!include ip/exchange_alt.puml
!include ip/exclamation.puml
!include ip/exclamation_circle.puml
!include ip/exclamation_triangle.puml
!include ip/expand.puml
!include ip/expand_alt.puml
!include ip/expand_arrows_alt.puml
!include ip/expeditedssl.puml
!include ip/external_link_alt.puml
!include ip/external_link_square_alt.puml
!include ip/eye.puml
!include ip/eye_dropper.puml
!include ip/eye_slash.puml
!include ip/facebook.puml
!include ip/facebook_f.puml
!include ip/facebook_messenger.puml
!include ip/facebook_square.puml
!include ip/fan.puml
!include ip/fantasy_flight_games.puml
!include ip/fast_backward.puml
!include ip/fast_forward.puml
!include ip/faucet.puml
!include ip/fax.puml
!include ip/feather.puml
!include ip/feather_alt.puml
!include ip/fedex.puml
!include ip/fedora.puml
!include ip/female.puml
!include ip/fighter_jet.puml
!include ip/figma.puml
!include ip/file.puml
!include ip/file_alt.puml
!include ip/file_archive.puml
!include ip/file_audio.puml
!include ip/file_code.puml
!include ip/file_contract.puml
!include ip/file_csv.puml
!include ip/file_download.puml
!include ip/file_excel.puml
!include ip/file_export.puml
!include ip/file_image.puml
!include ip/file_import.puml
!include ip/file_invoice.puml
!include ip/file_invoice_dollar.puml
!include ip/file_medical.puml
!include ip/file_medical_alt.puml
!include ip/file_pdf.puml
!include ip/file_powerpoint.puml
!include ip/file_prescription.puml
!include ip/file_signature.puml
!include ip/file_upload.puml
!include ip/file_video.puml
!include ip/file_word.puml
!include ip/fill.puml
!include ip/fill_drip.puml
!include ip/film.puml
!include ip/filter.puml
!include ip/fingerprint.puml
!include ip/fire.puml
!include ip/fire_alt.puml
!include ip/fire_extinguisher.puml
!include ip/firefox.puml
!include ip/firefox_browser.puml
!include ip/first_aid.puml
!include ip/first_order.puml
!include ip/first_order_alt.puml
!include ip/firstdraft.puml
!include ip/fish.puml
!include ip/fist_raised.puml
!include ip/flag.puml
!include ip/flag_checkered.puml
!include ip/flag_usa.puml
!include ip/flask.puml
!include ip/flickr.puml
!include ip/flipboard.puml
!include ip/flushed.puml
!include ip/fly.puml
!include ip/folder.puml
!include ip/folder_minus.puml
!include ip/folder_open.puml
!include ip/folder_plus.puml
!include ip/font.puml
!include ip/font_awesome.puml
!include ip/font_awesome_alt.puml
!include ip/font_awesome_flag.puml
!include ip/fonticons.puml
!include ip/fonticons_fi.puml
!include ip/football_ball.puml
!include ip/fort_awesome.puml
!include ip/fort_awesome_alt.puml
!include ip/forumbee.puml
!include ip/forward.puml
!include ip/foursquare.puml
!include ip/free_code_camp.puml
!include ip/freebsd.puml
!include ip/frog.puml
!include ip/frown.puml
!include ip/frown_open.puml
!include ip/fulcrum.puml
!include ip/funnel_dollar.puml
!include ip/futbol.puml
!include ip/galactic_republic.puml
!include ip/galactic_senate.puml
!include ip/gamepad.puml
!include ip/gas_pump.puml
!include ip/gavel.puml
!include ip/gem.puml
!include ip/genderless.puml
!include ip/get_pocket.puml
!include ip/gg.puml
!include ip/gg_circle.puml
!include ip/ghost.puml
!include ip/gift.puml
!include ip/gifts.puml
!include ip/git.puml
!include ip/git_alt.puml
!include ip/git_square.puml
!include ip/github.puml
!include ip/github_alt.puml
!include ip/github_square.puml
!include ip/gitkraken.puml
!include ip/gitlab.puml
!include ip/gitter.puml
!include ip/glass_cheers.puml
!include ip/glass_martini.puml
!include ip/glass_martini_alt.puml
!include ip/glass_whiskey.puml
!include ip/glasses.puml
!include ip/glide.puml
!include ip/glide_g.puml
!include ip/globe.puml
!include ip/globe_africa.puml
!include ip/globe_americas.puml
!include ip/globe_asia.puml
!include ip/globe_europe.puml
!include ip/gofore.puml
!include ip/golf_ball.puml
!include ip/goodreads.puml
!include ip/goodreads_g.puml
!include ip/google.puml
!include ip/google_drive.puml
!include ip/google_pay.puml
!include ip/google_play.puml
!include ip/google_plus.puml
!include ip/google_plus_g.puml
!include ip/google_plus_square.puml
!include ip/google_wallet.puml
!include ip/gopuram.puml
!include ip/graduation_cap.puml
!include ip/gratipay.puml
!include ip/grav.puml
!include ip/greater_than.puml
!include ip/greater_than_equal.puml
!include ip/grimace.puml
!include ip/grin.puml
!include ip/grin_alt.puml
!include ip/grin_beam.puml
!include ip/grin_beam_sweat.puml
!include ip/grin_hearts.puml
!include ip/grin_squint.puml
!include ip/grin_squint_tears.puml
!include ip/grin_stars.puml
!include ip/grin_tears.puml
!include ip/grin_tongue.puml
!include ip/grin_tongue_squint.puml
!include ip/grin_tongue_wink.puml
!include ip/grin_wink.puml
!include ip/grip_horizontal.puml
!include ip/grip_lines.puml
!include ip/grip_lines_vertical.puml
!include ip/grip_vertical.puml
!include ip/gripfire.puml
!include ip/grunt.puml
!include ip/guilded.puml
!include ip/guitar.puml
!include ip/gulp.puml
!include ip/h_square.puml
!include ip/hacker_news.puml
!include ip/hacker_news_square.puml
!include ip/hackerrank.puml
!include ip/hamburger.puml
!include ip/hammer.puml
!include ip/hamsa.puml
!include ip/hand_holding.puml
!include ip/hand_holding_heart.puml
!include ip/hand_holding_medical.puml
!include ip/hand_holding_usd.puml
!include ip/hand_holding_water.puml
!include ip/hand_lizard.puml
!include ip/hand_middle_finger.puml
!include ip/hand_paper.puml
!include ip/hand_peace.puml
!include ip/hand_point_down.puml
!include ip/hand_point_left.puml
!include ip/hand_point_right.puml
!include ip/hand_point_up.puml
!include ip/hand_pointer.puml
!include ip/hand_rock.puml
!include ip/hand_scissors.puml
!include ip/hand_sparkles.puml
!include ip/hand_spock.puml
!include ip/hands.puml
!include ip/hands_helping.puml
!include ip/hands_wash.puml
!include ip/handshake.puml
!include ip/handshake_alt_slash.puml
!include ip/handshake_slash.puml
!include ip/hanukiah.puml
!include ip/hard_hat.puml
!include ip/hashtag.puml
!include ip/hat_cowboy.puml
!include ip/hat_cowboy_side.puml
!include ip/hat_wizard.puml
!include ip/hdd.puml
!include ip/head_side_cough.puml
!include ip/head_side_cough_slash.puml
!include ip/head_side_mask.puml
!include ip/head_side_virus.puml
!include ip/heading.puml
!include ip/headphones.puml
!include ip/headphones_alt.puml
!include ip/headset.puml
!include ip/heart.puml
!include ip/heart_broken.puml
!include ip/heartbeat.puml
!include ip/helicopter.puml
!include ip/highlighter.puml
!include ip/hiking.puml
!include ip/hippo.puml
!include ip/hips.puml
!include ip/hire_a_helper.puml
!include ip/history.puml
!include ip/hive.puml
!include ip/hockey_puck.puml
!include ip/holly_berry.puml
!include ip/home.puml
!include ip/hooli.puml
!include ip/hornbill.puml
!include ip/horse.puml
!include ip/horse_head.puml
!include ip/hospital.puml
!include ip/hospital_alt.puml
!include ip/hospital_symbol.puml
!include ip/hospital_user.puml
!include ip/hot_tub.puml
!include ip/hotdog.puml
!include ip/hotel.puml
!include ip/hotjar.puml
!include ip/hourglass.puml
!include ip/hourglass_end.puml
!include ip/hourglass_half.puml
!include ip/hourglass_start.puml
!include ip/house_damage.puml
!include ip/house_user.puml
!include ip/houzz.puml
!include ip/hryvnia.puml
!include ip/html5.puml
!include ip/hubspot.puml
!include ip/i_cursor.puml
!include ip/ice_cream.puml
!include ip/icicles.puml
!include ip/icons.puml
!include ip/id_badge.puml
!include ip/id_card.puml
!include ip/id_card_alt.puml
!include ip/ideal.puml
!include ip/igloo.puml
!include ip/image.puml
!include ip/images.puml
!include ip/imdb.puml
!include ip/inbox.puml
!include ip/indent.puml
!include ip/industry.puml
!include ip/infinity.puml
!include ip/info.puml
!include ip/info_circle.puml
!include ip/innosoft.puml
!include ip/instagram.puml
!include ip/instagram_square.puml
!include ip/instalod.puml
!include ip/intercom.puml
!include ip/internet_explorer.puml
!include ip/invision.puml
!include ip/ioxhost.puml
!include ip/italic.puml
!include ip/itch_io.puml
!include ip/itunes.puml
!include ip/itunes_note.puml
!include ip/java.puml
!include ip/jedi.puml
!include ip/jedi_order.puml
!include ip/jenkins.puml
!include ip/jira.puml
!include ip/joget.puml
!include ip/joint.puml
!include ip/joomla.puml
!include ip/journal_whills.puml
!include ip/js.puml
!include ip/js_square.puml
!include ip/jsfiddle.puml
!include ip/kaaba.puml
!include ip/kaggle.puml
!include ip/key.puml
!include ip/keybase.puml
!include ip/keyboard.puml
!include ip/keycdn.puml
!include ip/khanda.puml
!include ip/kickstarter.puml
!include ip/kickstarter_k.puml
!include ip/kiss.puml
!include ip/kiss_beam.puml
!include ip/kiss_wink_heart.puml
!include ip/kiwi_bird.puml
!include ip/korvue.puml
!include ip/landmark.puml
!include ip/language.puml
!include ip/laptop.puml
!include ip/laptop_code.puml
!include ip/laptop_house.puml
!include ip/laptop_medical.puml
!include ip/laravel.puml
!include ip/lastfm.puml
!include ip/lastfm_square.puml
!include ip/laugh.puml
!include ip/laugh_beam.puml
!include ip/laugh_squint.puml
!include ip/laugh_wink.puml
!include ip/layer_group.puml
!include ip/leaf.puml
!include ip/leanpub.puml
!include ip/lemon.puml
!include ip/less.puml
!include ip/less_than.puml
!include ip/less_than_equal.puml
!include ip/level_down_alt.puml
!include ip/level_up_alt.puml
!include ip/life_ring.puml
!include ip/lightbulb.puml
!include ip/line.puml
!include ip/link.puml
!include ip/linkedin.puml
!include ip/linkedin_in.puml
!include ip/linode.puml
!include ip/linux.puml
!include ip/lira_sign.puml
!include ip/list.puml
!include ip/list_alt.puml
!include ip/list_ol.puml
!include ip/list_ul.puml
!include ip/location_arrow.puml
!include ip/lock.puml
!include ip/lock_open.puml
!include ip/long_arrow_alt_down.puml
!include ip/long_arrow_alt_left.puml
!include ip/long_arrow_alt_right.puml
!include ip/long_arrow_alt_up.puml
!include ip/low_vision.puml
!include ip/luggage_cart.puml
!include ip/lungs.puml
!include ip/lungs_virus.puml
!include ip/lyft.puml
!include ip/magento.puml
!include ip/magic.puml
!include ip/magnet.puml
!include ip/mail_bulk.puml
!include ip/mailchimp.puml
!include ip/male.puml
!include ip/mandalorian.puml
!include ip/map.puml
!include ip/map_marked.puml
!include ip/map_marked_alt.puml
!include ip/map_marker.puml
!include ip/map_marker_alt.puml
!include ip/map_pin.puml
!include ip/map_signs.puml
!include ip/markdown.puml
!include ip/marker.puml
!include ip/mars.puml
!include ip/mars_double.puml
!include ip/mars_stroke.puml
!include ip/mars_stroke_h.puml
!include ip/mars_stroke_v.puml
!include ip/mask.puml
!include ip/mastodon.puml
!include ip/maxcdn.puml
!include ip/mdb.puml
!include ip/medal.puml
!include ip/medapps.puml
!include ip/medium.puml
!include ip/medium_m.puml
!include ip/medkit.puml
!include ip/medrt.puml
!include ip/meetup.puml
!include ip/megaport.puml
!include ip/meh.puml
!include ip/meh_blank.puml
!include ip/meh_rolling_eyes.puml
!include ip/memory.puml
!include ip/mendeley.puml
!include ip/menorah.puml
!include ip/mercury.puml
!include ip/meteor.puml
!include ip/microblog.puml
!include ip/microchip.puml
!include ip/microphone.puml
!include ip/microphone_alt.puml
!include ip/microphone_alt_slash.puml
!include ip/microphone_slash.puml
!include ip/microscope.puml
!include ip/microsoft.puml
!include ip/minus.puml
!include ip/minus_circle.puml
!include ip/minus_square.puml
!include ip/mitten.puml
!include ip/mix.puml
!include ip/mixcloud.puml
!include ip/mixer.puml
!include ip/mizuni.puml
!include ip/mobile.puml
!include ip/mobile_alt.puml
!include ip/modx.puml
!include ip/monero.puml
!include ip/money_bill.puml
!include ip/money_bill_alt.puml
!include ip/money_bill_wave.puml
!include ip/money_bill_wave_alt.puml
!include ip/money_check.puml
!include ip/money_check_alt.puml
!include ip/monument.puml
!include ip/moon.puml
!include ip/mortar_pestle.puml
!include ip/mosque.puml
!include ip/motorcycle.puml
!include ip/mountain.puml
!include ip/mouse.puml
!include ip/mouse_pointer.puml
!include ip/mug_hot.puml
!include ip/music.puml
!include ip/napster.puml
!include ip/neos.puml
!include ip/network_wired.puml
!include ip/neuter.puml
!include ip/newspaper.puml
!include ip/nimblr.puml
!include ip/node.puml
!include ip/node_js.puml
!include ip/not_equal.puml
!include ip/notes_medical.puml
!include ip/npm.puml
!include ip/ns8.puml
!include ip/nutritionix.puml
!include ip/object_group.puml
!include ip/object_ungroup.puml
!include ip/octopus_deploy.puml
!include ip/odnoklassniki.puml
!include ip/odnoklassniki_square.puml
!include ip/oil_can.puml
!include ip/old_republic.puml
!include ip/om.puml
!include ip/opencart.puml
!include ip/openid.puml
!include ip/opera.puml
!include ip/optin_monster.puml
!include ip/orcid.puml
!include ip/osi.puml
!include ip/otter.puml
!include ip/outdent.puml
!include ip/page4.puml
!include ip/pagelines.puml
!include ip/pager.puml
!include ip/paint_brush.puml
!include ip/paint_roller.puml
!include ip/palette.puml
!include ip/palfed.puml
!include ip/pallet.puml
!include ip/paper_plane.puml
!include ip/paperclip.puml
!include ip/parachute_box.puml
!include ip/paragraph.puml
!include ip/parking.puml
!include ip/passport.puml
!include ip/pastafarianism.puml
!include ip/paste.puml
!include ip/patreon.puml
!include ip/pause.puml
!include ip/pause_circle.puml
!include ip/paw.puml
!include ip/paypal.puml
!include ip/peace.puml
!include ip/pen.puml
!include ip/pen_alt.puml
!include ip/pen_fancy.puml
!include ip/pen_nib.puml
!include ip/pen_square.puml
!include ip/pencil_alt.puml
!include ip/pencil_ruler.puml
!include ip/penny_arcade.puml
!include ip/people_arrows.puml
!include ip/people_carry.puml
!include ip/pepper_hot.puml
!include ip/perbyte.puml
!include ip/percent.puml
!include ip/percentage.puml
!include ip/periscope.puml
!include ip/person_booth.puml
!include ip/phabricator.puml
!include ip/phoenix_framework.puml
!include ip/phoenix_squadron.puml
!include ip/phone.puml
!include ip/phone_alt.puml
!include ip/phone_slash.puml
!include ip/phone_square.puml
!include ip/phone_square_alt.puml
!include ip/phone_volume.puml
!include ip/photo_video.puml
!include ip/php.puml
!include ip/pied_piper.puml
!include ip/pied_piper_alt.puml
!include ip/pied_piper_hat.puml
!include ip/pied_piper_pp.puml
!include ip/pied_piper_square.puml
!include ip/piggy_bank.puml
!include ip/pills.puml
!include ip/pinterest.puml
!include ip/pinterest_p.puml
!include ip/pinterest_square.puml
!include ip/pizza_slice.puml
!include ip/place_of_worship.puml
!include ip/plane.puml
!include ip/plane_arrival.puml
!include ip/plane_departure.puml
!include ip/plane_slash.puml
!include ip/play.puml
!include ip/play_circle.puml
!include ip/playstation.puml
!include ip/plug.puml
!include ip/plus.puml
!include ip/plus_circle.puml
!include ip/plus_square.puml
!include ip/podcast.puml
!include ip/poll.puml
!include ip/poll_h.puml
!include ip/poo.puml
!include ip/poo_storm.puml
!include ip/poop.puml
!include ip/portrait.puml
!include ip/pound_sign.puml
!include ip/power_off.puml
!include ip/pray.puml
!include ip/praying_hands.puml
!include ip/prescription.puml
!include ip/prescription_bottle.puml
!include ip/prescription_bottle_alt.puml
!include ip/print.puml
!include ip/procedures.puml
!include ip/product_hunt.puml
!include ip/project_diagram.puml
!include ip/pump_medical.puml
!include ip/pump_soap.puml
!include ip/pushed.puml
!include ip/puzzle_piece.puml
!include ip/python.puml
!include ip/qq.puml
!include ip/qrcode.puml
!include ip/question.puml
!include ip/question_circle.puml
!include ip/quidditch.puml
!include ip/quinscape.puml
!include ip/quora.puml
!include ip/quote_left.puml
!include ip/quote_right.puml
!include ip/quran.puml
!include ip/r_project.puml
!include ip/radiation.puml
!include ip/radiation_alt.puml
!include ip/rainbow.puml
!include ip/random.puml
!include ip/raspberry_pi.puml
!include ip/ravelry.puml
!include ip/react.puml
!include ip/reacteurope.puml
!include ip/readme.puml
!include ip/rebel.puml
!include ip/receipt.puml
!include ip/record_vinyl.puml
!include ip/recycle.puml
!include ip/red_river.puml
!include ip/reddit.puml
!include ip/reddit_alien.puml
!include ip/reddit_square.puml
!include ip/redhat.puml
!include ip/redo.puml
!include ip/redo_alt.puml
!include ip/registered.puml
!include ip/remove_format.puml
!include ip/renren.puml
!include ip/reply.puml
!include ip/reply_all.puml
!include ip/replyd.puml
!include ip/republican.puml
!include ip/researchgate.puml
!include ip/resolving.puml
!include ip/restroom.puml
!include ip/retweet.puml
!include ip/rev.puml
!include ip/ribbon.puml
!include ip/ring.puml
!include ip/road.puml
!include ip/robot.puml
!include ip/rocket.puml
!include ip/rocketchat.puml
!include ip/rockrms.puml
!include ip/route.puml
!include ip/rss.puml
!include ip/rss_square.puml
!include ip/ruble_sign.puml
!include ip/ruler.puml
!include ip/ruler_combined.puml
!include ip/ruler_horizontal.puml
!include ip/ruler_vertical.puml
!include ip/running.puml
!include ip/rupee_sign.puml
!include ip/rust.puml
!include ip/sad_cry.puml
!include ip/sad_tear.puml
!include ip/safari.puml
!include ip/salesforce.puml
!include ip/sass.puml
!include ip/satellite.puml
!include ip/satellite_dish.puml
!include ip/save.puml
!include ip/schlix.puml
!include ip/school.puml
!include ip/screwdriver.puml
!include ip/scribd.puml
!include ip/scroll.puml
!include ip/sd_card.puml
!include ip/search.puml
!include ip/search_dollar.puml
!include ip/search_location.puml
!include ip/search_minus.puml
!include ip/search_plus.puml
!include ip/searchengin.puml
!include ip/seedling.puml
!include ip/sellcast.puml
!include ip/sellsy.puml
!include ip/server.puml
!include ip/servicestack.puml
!include ip/shapes.puml
!include ip/share.puml
!include ip/share_alt.puml
!include ip/share_alt_square.puml
!include ip/share_square.puml
!include ip/shekel_sign.puml
!include ip/shield_alt.puml
!include ip/shield_virus.puml
!include ip/ship.puml
!include ip/shipping_fast.puml
!include ip/shirtsinbulk.puml
!include ip/shoe_prints.puml
!include ip/shopify.puml
!include ip/shopping_bag.puml
!include ip/shopping_basket.puml
!include ip/shopping_cart.puml
!include ip/shopware.puml
!include ip/shower.puml
!include ip/shuttle_van.puml
!include ip/sign.puml
!include ip/sign_in_alt.puml
!include ip/sign_language.puml
!include ip/sign_out_alt.puml
!include ip/signal.puml
!include ip/signature.puml
!include ip/sim_card.puml
!include ip/simplybuilt.puml
!include ip/sink.puml
!include ip/sistrix.puml
!include ip/sitemap.puml
!include ip/sith.puml
!include ip/skating.puml
!include ip/sketch.puml
!include ip/skiing.puml
!include ip/skiing_nordic.puml
!include ip/skull.puml
!include ip/skull_crossbones.puml
!include ip/skyatlas.puml
!include ip/skype.puml
!include ip/slack.puml
!include ip/slack_hash.puml
!include ip/slash.puml
!include ip/sleigh.puml
!include ip/sliders_h.puml
!include ip/slideshare.puml
!include ip/smile.puml
!include ip/smile_beam.puml
!include ip/smile_wink.puml
!include ip/smog.puml
!include ip/smoking.puml
!include ip/smoking_ban.puml
!include ip/sms.puml
!include ip/snapchat.puml
!include ip/snapchat_ghost.puml
!include ip/snapchat_square.puml
!include ip/snowboarding.puml
!include ip/snowflake.puml
!include ip/snowman.puml
!include ip/snowplow.puml
!include ip/soap.puml
!include ip/socks.puml
!include ip/solar_panel.puml
!include ip/sort.puml
!include ip/sort_alpha_down.puml
!include ip/sort_alpha_down_alt.puml
!include ip/sort_alpha_up.puml
!include ip/sort_alpha_up_alt.puml
!include ip/sort_amount_down.puml
!include ip/sort_amount_down_alt.puml
!include ip/sort_amount_up.puml
!include ip/sort_amount_up_alt.puml
!include ip/sort_down.puml
!include ip/sort_numeric_down.puml
!include ip/sort_numeric_down_alt.puml
!include ip/sort_numeric_up.puml
!include ip/sort_numeric_up_alt.puml
!include ip/sort_up.puml
!include ip/soundcloud.puml
!include ip/sourcetree.puml
!include ip/spa.puml
!include ip/space_shuttle.puml
!include ip/speakap.puml
!include ip/speaker_deck.puml
!include ip/spell_check.puml
!include ip/spider.puml
!include ip/spinner.puml
!include ip/splotch.puml
!include ip/spotify.puml
!include ip/spray_can.puml
!include ip/square.puml
!include ip/square_full.puml
!include ip/square_root_alt.puml
!include ip/squarespace.puml
!include ip/stack_exchange.puml
!include ip/stack_overflow.puml
!include ip/stackpath.puml
!include ip/stamp.puml
!include ip/star.puml
!include ip/star_and_crescent.puml
!include ip/star_half.puml
!include ip/star_half_alt.puml
!include ip/star_of_david.puml
!include ip/star_of_life.puml
!include ip/staylinked.puml
!include ip/steam.puml
!include ip/steam_square.puml
!include ip/steam_symbol.puml
!include ip/step_backward.puml
!include ip/step_forward.puml
!include ip/stethoscope.puml
!include ip/sticker_mule.puml
!include ip/sticky_note.puml
!include ip/stop.puml
!include ip/stop_circle.puml
!include ip/stopwatch.puml
!include ip/stopwatch_20.puml
!include ip/store.puml
!include ip/store_alt.puml
!include ip/store_alt_slash.puml
!include ip/store_slash.puml
!include ip/strava.puml
!include ip/stream.puml
!include ip/street_view.puml
!include ip/strikethrough.puml
!include ip/stripe.puml
!include ip/stripe_s.puml
!include ip/stroopwafel.puml
!include ip/studiovinari.puml
!include ip/stumbleupon.puml
!include ip/stumbleupon_circle.puml
!include ip/subscript.puml
!include ip/subway.puml
!include ip/suitcase.puml
!include ip/suitcase_rolling.puml
!include ip/sun.puml
!include ip/superpowers.puml
!include ip/superscript.puml
!include ip/supple.puml
!include ip/surprise.puml
!include ip/suse.puml
!include ip/swatchbook.puml
!include ip/swift.puml
!include ip/swimmer.puml
!include ip/swimming_pool.puml
!include ip/symfony.puml
!include ip/synagogue.puml
!include ip/sync.puml
!include ip/sync_alt.puml
!include ip/syringe.puml
!include ip/table.puml
!include ip/table_tennis.puml
!include ip/tablet.puml
!include ip/tablet_alt.puml
!include ip/tablets.puml
!include ip/tachometer_alt.puml
!include ip/tag.puml
!include ip/tags.puml
!include ip/tape.puml
!include ip/tasks.puml
!include ip/taxi.puml
!include ip/teamspeak.puml
!include ip/teeth.puml
!include ip/teeth_open.puml
!include ip/telegram.puml
!include ip/telegram_plane.puml
!include ip/temperature_high.puml
!include ip/temperature_low.puml
!include ip/tencent_weibo.puml
!include ip/tenge.puml
!include ip/terminal.puml
!include ip/text_height.puml
!include ip/text_width.puml
!include ip/th.puml
!include ip/th_large.puml
!include ip/th_list.puml
!include ip/the_red_yeti.puml
!include ip/theater_masks.puml
!include ip/themeco.puml
!include ip/themeisle.puml
!include ip/thermometer.puml
!include ip/thermometer_empty.puml
!include ip/thermometer_full.puml
!include ip/thermometer_half.puml
!include ip/thermometer_quarter.puml
!include ip/thermometer_three_quarters.puml
!include ip/think_peaks.puml
!include ip/thumbs_down.puml
!include ip/thumbs_up.puml
!include ip/thumbtack.puml
!include ip/ticket_alt.puml
!include ip/tiktok.puml
!include ip/times.puml
!include ip/times_circle.puml
!include ip/tint.puml
!include ip/tint_slash.puml
!include ip/tired.puml
!include ip/toggle_off.puml
!include ip/toggle_on.puml
!include ip/toilet.puml
!include ip/toilet_paper.puml
!include ip/toilet_paper_slash.puml
!include ip/toolbox.puml
!include ip/tools.puml
!include ip/tooth.puml
!include ip/torah.puml
!include ip/torii_gate.puml
!include ip/tractor.puml
!include ip/trade_federation.puml
!include ip/trademark.puml
!include ip/traffic_light.puml
!include ip/trailer.puml
!include ip/train.puml
!include ip/tram.puml
!include ip/transgender.puml
!include ip/transgender_alt.puml
!include ip/trash.puml
!include ip/trash_alt.puml
!include ip/trash_restore.puml
!include ip/trash_restore_alt.puml
!include ip/tree.puml
!include ip/trello.puml
!include ip/tripadvisor.puml
!include ip/trophy.puml
!include ip/truck.puml
!include ip/truck_loading.puml
!include ip/truck_monster.puml
!include ip/truck_moving.puml
!include ip/truck_pickup.puml
!include ip/tshirt.puml
!include ip/tty.puml
!include ip/tumblr.puml
!include ip/tumblr_square.puml
!include ip/tv.puml
!include ip/twitch.puml
!include ip/twitter.puml
!include ip/twitter_square.puml
!include ip/typo3.puml
!include ip/uber.puml
!include ip/ubuntu.puml
!include ip/uikit.puml
!include ip/umbraco.puml
!include ip/umbrella.puml
!include ip/umbrella_beach.puml
!include ip/uncharted.puml
!include ip/underline.puml
!include ip/undo.puml
!include ip/undo_alt.puml
!include ip/uniregistry.puml
!include ip/unity.puml
!include ip/universal_access.puml
!include ip/university.puml
!include ip/unlink.puml
!include ip/unlock.puml
!include ip/unlock_alt.puml
!include ip/unsplash.puml
!include ip/untappd.puml
!include ip/upload.puml
!include ip/ups.puml
!include ip/usb.puml
!include ip/user.puml
!include ip/user_alt.puml
!include ip/user_alt_slash.puml
!include ip/user_astronaut.puml
!include ip/user_check.puml
!include ip/user_circle.puml
!include ip/user_clock.puml
!include ip/user_cog.puml
!include ip/user_edit.puml
!include ip/user_friends.puml
!include ip/user_graduate.puml
!include ip/user_injured.puml
!include ip/user_lock.puml
!include ip/user_md.puml
!include ip/user_minus.puml
!include ip/user_ninja.puml
!include ip/user_nurse.puml
!include ip/user_plus.puml
!include ip/user_secret.puml
!include ip/user_shield.puml
!include ip/user_slash.puml
!include ip/user_tag.puml
!include ip/user_tie.puml
!include ip/user_times.puml
!include ip/users.puml
!include ip/users_cog.puml
!include ip/users_slash.puml
!include ip/usps.puml
!include ip/ussunnah.puml
!include ip/utensil_spoon.puml
!include ip/utensils.puml
!include ip/vaadin.puml
!include ip/vector_square.puml
!include ip/venus.puml
!include ip/venus_double.puml
!include ip/venus_mars.puml
!include ip/vest.puml
!include ip/vest_patches.puml
!include ip/viacoin.puml
!include ip/viadeo.puml
!include ip/viadeo_square.puml
!include ip/vial.puml
!include ip/vials.puml
!include ip/viber.puml
!include ip/video.puml
!include ip/video_slash.puml
!include ip/vihara.puml
!include ip/vimeo.puml
!include ip/vimeo_square.puml
!include ip/vimeo_v.puml
!include ip/vine.puml
!include ip/virus.puml
!include ip/virus_slash.puml
!include ip/viruses.puml
!include ip/vk.puml
!include ip/vnv.puml
!include ip/voicemail.puml
!include ip/volleyball_ball.puml
!include ip/volume_down.puml
!include ip/volume_mute.puml
!include ip/volume_off.puml
!include ip/volume_up.puml
!include ip/vote_yea.puml
!include ip/vr_cardboard.puml
!include ip/vuejs.puml
!include ip/walking.puml
!include ip/wallet.puml
!include ip/warehouse.puml
!include ip/watchman_monitoring.puml
!include ip/water.puml
!include ip/wave_square.puml
!include ip/waze.puml
!include ip/weebly.puml
!include ip/weibo.puml
!include ip/weight.puml
!include ip/weight_hanging.puml
!include ip/weixin.puml
!include ip/whatsapp.puml
!include ip/whatsapp_square.puml
!include ip/wheelchair.puml
!include ip/whmcs.puml
!include ip/wifi.puml
!include ip/wikipedia_w.puml
!include ip/wind.puml
!include ip/window_close.puml
!include ip/window_maximize.puml
!include ip/window_minimize.puml
!include ip/window_restore.puml
!include ip/windows.puml
!include ip/wine_bottle.puml
!include ip/wine_glass.puml
!include ip/wine_glass_alt.puml
!include ip/wix.puml
!include ip/wizards_of_the_coast.puml
!include ip/wodu.puml
!include ip/wolf_pack_battalion.puml
!include ip/won_sign.puml
!include ip/wordpress.puml
!include ip/wordpress_simple.puml
!include ip/wpbeginner.puml
!include ip/wpexplorer.puml
!include ip/wpforms.puml
!include ip/wpressr.puml
!include ip/wrench.puml
!include ip/x_ray.puml
!include ip/xbox.puml
!include ip/xing.puml
!include ip/xing_square.puml
!include ip/y_combinator.puml
!include ip/yahoo.puml
!include ip/yammer.puml
!include ip/yandex.puml
!include ip/yandex_international.puml
!include ip/yarn.puml
!include ip/yelp.puml
!include ip/yen_sign.puml
!include ip/yin_yang.puml
!include ip/yoast.puml
!include ip/youtube.puml
!include ip/youtube_square.puml
!include ip/zhihu.puml

listsprites
@enduml
