@startuml
!define pc /Volumes/SRC/plantuml-stdlib/tupadr3
!include pc/common.puml
!define ip /Volumes/SRC/plantuml-stdlib/tupadr3/font-awesome

!include ip/500px.puml
!include ip/address_book.puml
!include ip/address_book_o.puml
!include ip/address_card.puml
!include ip/address_card_o.puml
!include ip/adjust.puml
!include ip/adn.puml
!include ip/align_center.puml
!include ip/align_justify.puml
!include ip/align_left.puml
!include ip/align_right.puml
!include ip/amazon.puml
!include ip/ambulance.puml
!include ip/american_sign_language_interpreting.puml
!include ip/anchor.puml
!include ip/android.puml
!include ip/angellist.puml
!include ip/angle_double_down.puml
!include ip/angle_double_left.puml
!include ip/angle_double_right.puml
!include ip/angle_double_up.puml
!include ip/angle_down.puml
!include ip/angle_left.puml
!include ip/angle_right.puml
!include ip/angle_up.puml
!include ip/apple.puml
!include ip/archive.puml
!include ip/area_chart.puml
!include ip/arrow_circle_down.puml
!include ip/arrow_circle_left.puml
!include ip/arrow_circle_o_down.puml
!include ip/arrow_circle_o_left.puml
!include ip/arrow_circle_o_right.puml
!include ip/arrow_circle_o_up.puml
!include ip/arrow_circle_right.puml
!include ip/arrow_circle_up.puml
!include ip/arrow_down.puml
!include ip/arrow_left.puml
!include ip/arrow_right.puml
!include ip/arrow_up.puml
!include ip/arrows.puml
!include ip/arrows_alt.puml
!include ip/arrows_h.puml
!include ip/arrows_v.puml
!include ip/asl_interpreting.puml
!include ip/assistive_listening_systems.puml
!include ip/asterisk.puml
!include ip/at.puml
!include ip/audio_description.puml
!include ip/automobile.puml
!include ip/backward.puml
!include ip/balance_scale.puml
!include ip/ban.puml
!include ip/bandcamp.puml
!include ip/bank.puml
!include ip/bar_chart.puml
!include ip/bar_chart_o.puml
!include ip/barcode.puml
!include ip/bars.puml
!include ip/bath.puml
!include ip/bathtub.puml
!include ip/battery.puml
!include ip/battery_0.puml
!include ip/battery_1.puml
!include ip/battery_2.puml
!include ip/battery_3.puml
!include ip/battery_4.puml
!include ip/battery_empty.puml
!include ip/battery_full.puml
!include ip/battery_half.puml
!include ip/battery_quarter.puml
!include ip/battery_three_quarters.puml
!include ip/bed.puml
!include ip/beer.puml
!include ip/behance.puml
!include ip/behance_square.puml
!include ip/bell.puml
!include ip/bell_o.puml
!include ip/bell_slash.puml
!include ip/bell_slash_o.puml
!include ip/bicycle.puml
!include ip/binoculars.puml
!include ip/birthday_cake.puml
!include ip/bitbucket.puml
!include ip/bitbucket_square.puml
!include ip/bitcoin.puml
!include ip/black_tie.puml
!include ip/blind.puml
!include ip/bluetooth.puml
!include ip/bluetooth_b.puml
!include ip/bold.puml
!include ip/bolt.puml
!include ip/bomb.puml
!include ip/book.puml
!include ip/bookmark.puml
!include ip/bookmark_o.puml
!include ip/braille.puml
!include ip/briefcase.puml
!include ip/btc.puml
!include ip/bug.puml
!include ip/building.puml
!include ip/building_o.puml
!include ip/bullhorn.puml
!include ip/bullseye.puml
!include ip/bus.puml
!include ip/buysellads.puml
!include ip/cab.puml
!include ip/calculator.puml
!include ip/calendar.puml
!include ip/calendar_check_o.puml
!include ip/calendar_minus_o.puml
!include ip/calendar_o.puml
!include ip/calendar_plus_o.puml
!include ip/calendar_times_o.puml
!include ip/camera.puml
!include ip/camera_retro.puml
!include ip/car.puml
!include ip/caret_down.puml
!include ip/caret_left.puml
!include ip/caret_right.puml
!include ip/caret_square_o_down.puml
!include ip/caret_square_o_left.puml
!include ip/caret_square_o_right.puml
!include ip/caret_square_o_up.puml
!include ip/caret_up.puml
!include ip/cart_arrow_down.puml
!include ip/cart_plus.puml
!include ip/cc.puml
!include ip/cc_amex.puml
!include ip/cc_diners_club.puml
!include ip/cc_discover.puml
!include ip/cc_jcb.puml
!include ip/cc_mastercard.puml
!include ip/cc_paypal.puml
!include ip/cc_stripe.puml
!include ip/cc_visa.puml
!include ip/certificate.puml
!include ip/chain.puml
!include ip/chain_broken.puml
!include ip/check.puml
!include ip/check_circle.puml
!include ip/check_circle_o.puml
!include ip/check_square.puml
!include ip/check_square_o.puml
!include ip/chevron_circle_down.puml
!include ip/chevron_circle_left.puml
!include ip/chevron_circle_right.puml
!include ip/chevron_circle_up.puml
!include ip/chevron_down.puml
!include ip/chevron_left.puml
!include ip/chevron_right.puml
!include ip/chevron_up.puml
!include ip/child.puml
!include ip/chrome.puml
!include ip/circle.puml
!include ip/circle_o.puml
!include ip/circle_o_notch.puml
!include ip/circle_thin.puml
!include ip/clipboard.puml
!include ip/clock_o.puml
!include ip/clone.puml
!include ip/close.puml
!include ip/cloud.puml
!include ip/cloud_download.puml
!include ip/cloud_upload.puml
!include ip/cny.puml
!include ip/code.puml
!include ip/code_fork.puml
!include ip/codepen.puml
!include ip/codiepie.puml
!include ip/coffee.puml
!include ip/cog.puml
!include ip/cogs.puml
!include ip/columns.puml
!include ip/comment.puml
!include ip/comment_o.puml
!include ip/commenting.puml
!include ip/commenting_o.puml
!include ip/comments.puml
!include ip/comments_o.puml
!include ip/compass.puml
!include ip/compress.puml
!include ip/connectdevelop.puml
!include ip/contao.puml
!include ip/copy.puml
!include ip/copyright.puml
!include ip/creative_commons.puml
!include ip/credit_card.puml
!include ip/credit_card_alt.puml
!include ip/crop.puml
!include ip/crosshairs.puml
!include ip/css3.puml
!include ip/cube.puml
!include ip/cubes.puml
!include ip/cut.puml
!include ip/cutlery.puml
!include ip/dashboard.puml
!include ip/dashcube.puml
!include ip/database.puml
!include ip/deaf.puml
!include ip/deafness.puml
!include ip/dedent.puml
!include ip/delicious.puml
!include ip/desktop.puml
!include ip/deviantart.puml
!include ip/diamond.puml
!include ip/digg.puml
!include ip/dollar.puml
!include ip/dot_circle_o.puml
!include ip/download.puml
!include ip/dribbble.puml
!include ip/drivers_license.puml
!include ip/drivers_license_o.puml
!include ip/dropbox.puml
!include ip/drupal.puml
!include ip/edge.puml
!include ip/edit.puml
!include ip/eercast.puml
!include ip/eject.puml
!include ip/ellipsis_h.puml
!include ip/ellipsis_v.puml
!include ip/empire.puml
!include ip/envelope.puml
!include ip/envelope_o.puml
!include ip/envelope_open.puml
!include ip/envelope_open_o.puml
!include ip/envelope_square.puml
!include ip/envira.puml
!include ip/eraser.puml
!include ip/etsy.puml
!include ip/eur.puml
!include ip/euro.puml
!include ip/exchange.puml
!include ip/exclamation.puml
!include ip/exclamation_circle.puml
!include ip/exclamation_triangle.puml
!include ip/expand.puml
!include ip/expeditedssl.puml
!include ip/external_link.puml
!include ip/external_link_square.puml
!include ip/eye.puml
!include ip/eye_slash.puml
!include ip/eyedropper.puml
!include ip/fa.puml
!include ip/facebook.puml
!include ip/facebook_f.puml
!include ip/facebook_official.puml
!include ip/facebook_square.puml
!include ip/fast_backward.puml
!include ip/fast_forward.puml
!include ip/fax.puml
!include ip/feed.puml
!include ip/female.puml
!include ip/fighter_jet.puml
!include ip/file.puml
!include ip/file_archive_o.puml
!include ip/file_audio_o.puml
!include ip/file_code_o.puml
!include ip/file_excel_o.puml
!include ip/file_image_o.puml
!include ip/file_movie_o.puml
!include ip/file_o.puml
!include ip/file_pdf_o.puml
!include ip/file_photo_o.puml
!include ip/file_picture_o.puml
!include ip/file_powerpoint_o.puml
!include ip/file_sound_o.puml
!include ip/file_text.puml
!include ip/file_text_o.puml
!include ip/file_video_o.puml
!include ip/file_word_o.puml
!include ip/file_zip_o.puml
!include ip/files_o.puml
!include ip/film.puml
!include ip/filter.puml
!include ip/fire.puml
!include ip/fire_extinguisher.puml
!include ip/firefox.puml
!include ip/first_order.puml
!include ip/flag.puml
!include ip/flag_checkered.puml
!include ip/flag_o.puml
!include ip/flash.puml
!include ip/flask.puml
!include ip/flickr.puml
!include ip/floppy_o.puml
!include ip/folder.puml
!include ip/folder_o.puml
!include ip/folder_open.puml
!include ip/folder_open_o.puml
!include ip/font.puml
!include ip/font_awesome.puml
!include ip/fonticons.puml
!include ip/fort_awesome.puml
!include ip/forumbee.puml
!include ip/forward.puml
!include ip/foursquare.puml
!include ip/free_code_camp.puml
!include ip/frown_o.puml
!include ip/futbol_o.puml
!include ip/gamepad.puml
!include ip/gavel.puml
!include ip/gbp.puml
!include ip/ge.puml
!include ip/gear.puml
!include ip/gears.puml
!include ip/genderless.puml
!include ip/get_pocket.puml
!include ip/gg.puml
!include ip/gg_circle.puml
!include ip/gift.puml
!include ip/git.puml
!include ip/git_square.puml
!include ip/github.puml
!include ip/github_alt.puml
!include ip/github_square.puml
!include ip/gitlab.puml
!include ip/gittip.puml
!include ip/glass.puml
!include ip/glide.puml
!include ip/glide_g.puml
!include ip/globe.puml
!include ip/google.puml
!include ip/google_plus.puml
!include ip/google_plus_circle.puml
!include ip/google_plus_official.puml
!include ip/google_plus_square.puml
!include ip/google_wallet.puml
!include ip/graduation_cap.puml
!include ip/gratipay.puml
!include ip/grav.puml
!include ip/group.puml
!include ip/h_square.puml
!include ip/hacker_news.puml
!include ip/hand_grab_o.puml
!include ip/hand_lizard_o.puml
!include ip/hand_o_down.puml
!include ip/hand_o_left.puml
!include ip/hand_o_right.puml
!include ip/hand_o_up.puml
!include ip/hand_paper_o.puml
!include ip/hand_peace_o.puml
!include ip/hand_pointer_o.puml
!include ip/hand_rock_o.puml
!include ip/hand_scissors_o.puml
!include ip/hand_spock_o.puml
!include ip/hand_stop_o.puml
!include ip/handshake_o.puml
!include ip/hard_of_hearing.puml
!include ip/hashtag.puml
!include ip/hdd_o.puml
!include ip/header.puml
!include ip/headphones.puml
!include ip/heart.puml
!include ip/heart_o.puml
!include ip/heartbeat.puml
!include ip/history.puml
!include ip/home.puml
!include ip/hospital_o.puml
!include ip/hotel.puml
!include ip/hourglass.puml
!include ip/hourglass_1.puml
!include ip/hourglass_2.puml
!include ip/hourglass_3.puml
!include ip/hourglass_end.puml
!include ip/hourglass_half.puml
!include ip/hourglass_o.puml
!include ip/hourglass_start.puml
!include ip/houzz.puml
!include ip/html5.puml
!include ip/i_cursor.puml
!include ip/id_badge.puml
!include ip/id_card.puml
!include ip/id_card_o.puml
!include ip/ils.puml
!include ip/image.puml
!include ip/imdb.puml
!include ip/inbox.puml
!include ip/indent.puml
!include ip/industry.puml
!include ip/info.puml
!include ip/info_circle.puml
!include ip/inr.puml
!include ip/instagram.puml
!include ip/institution.puml
!include ip/internet_explorer.puml
!include ip/intersex.puml
!include ip/ioxhost.puml
!include ip/italic.puml
!include ip/joomla.puml
!include ip/jpy.puml
!include ip/jsfiddle.puml
!include ip/key.puml
!include ip/keyboard_o.puml
!include ip/krw.puml
!include ip/language.puml
!include ip/laptop.puml
!include ip/lastfm.puml
!include ip/lastfm_square.puml
!include ip/leaf.puml
!include ip/leanpub.puml
!include ip/legal.puml
!include ip/lemon_o.puml
!include ip/level_down.puml
!include ip/level_up.puml
!include ip/life_bouy.puml
!include ip/life_buoy.puml
!include ip/life_ring.puml
!include ip/life_saver.puml
!include ip/lightbulb_o.puml
!include ip/line_chart.puml
!include ip/link.puml
!include ip/linkedin.puml
!include ip/linkedin_square.puml
!include ip/linode.puml
!include ip/linux.puml
!include ip/list.puml
!include ip/list_alt.puml
!include ip/list_ol.puml
!include ip/list_ul.puml
!include ip/location_arrow.puml
!include ip/lock.puml
!include ip/long_arrow_down.puml
!include ip/long_arrow_left.puml
!include ip/long_arrow_right.puml
!include ip/long_arrow_up.puml
!include ip/low_vision.puml
!include ip/magic.puml
!include ip/magnet.puml
!include ip/mail_forward.puml
!include ip/mail_reply.puml
!include ip/mail_reply_all.puml
!include ip/male.puml
!include ip/map.puml
!include ip/map_marker.puml
!include ip/map_o.puml
!include ip/map_pin.puml
!include ip/map_signs.puml
!include ip/mars.puml
!include ip/mars_double.puml
!include ip/mars_stroke.puml
!include ip/mars_stroke_h.puml
!include ip/mars_stroke_v.puml
!include ip/maxcdn.puml
!include ip/meanpath.puml
!include ip/medium.puml
!include ip/medkit.puml
!include ip/meetup.puml
!include ip/meh_o.puml
!include ip/mercury.puml
!include ip/microchip.puml
!include ip/microphone.puml
!include ip/microphone_slash.puml
!include ip/minus.puml
!include ip/minus_circle.puml
!include ip/minus_square.puml
!include ip/minus_square_o.puml
!include ip/mixcloud.puml
!include ip/mobile.puml
!include ip/mobile_phone.puml
!include ip/modx.puml
!include ip/money.puml
!include ip/moon_o.puml
!include ip/mortar_board.puml
!include ip/motorcycle.puml
!include ip/mouse_pointer.puml
!include ip/music.puml
!include ip/navicon.puml
!include ip/neuter.puml
!include ip/newspaper_o.puml
!include ip/object_group.puml
!include ip/object_ungroup.puml
!include ip/odnoklassniki.puml
!include ip/odnoklassniki_square.puml
!include ip/opencart.puml
!include ip/openid.puml
!include ip/opera.puml
!include ip/optin_monster.puml
!include ip/outdent.puml
!include ip/pagelines.puml
!include ip/paint_brush.puml
!include ip/paper_plane.puml
!include ip/paper_plane_o.puml
!include ip/paperclip.puml
!include ip/paragraph.puml
!include ip/paste.puml
!include ip/pause.puml
!include ip/pause_circle.puml
!include ip/pause_circle_o.puml
!include ip/paw.puml
!include ip/paypal.puml
!include ip/pencil.puml
!include ip/pencil_square.puml
!include ip/pencil_square_o.puml
!include ip/percent.puml
!include ip/phone.puml
!include ip/phone_square.puml
!include ip/photo.puml
!include ip/picture_o.puml
!include ip/pie_chart.puml
!include ip/pied_piper.puml
!include ip/pied_piper_alt.puml
!include ip/pied_piper_pp.puml
!include ip/pinterest.puml
!include ip/pinterest_p.puml
!include ip/pinterest_square.puml
!include ip/plane.puml
!include ip/play.puml
!include ip/play_circle.puml
!include ip/play_circle_o.puml
!include ip/plug.puml
!include ip/plus.puml
!include ip/plus_circle.puml
!include ip/plus_square.puml
!include ip/plus_square_o.puml
!include ip/podcast.puml
!include ip/power_off.puml
!include ip/print.puml
!include ip/product_hunt.puml
!include ip/puzzle_piece.puml
!include ip/qq.puml
!include ip/qrcode.puml
!include ip/question.puml
!include ip/question_circle.puml
!include ip/question_circle_o.puml
!include ip/quora.puml
!include ip/quote_left.puml
!include ip/quote_right.puml
!include ip/ra.puml
!include ip/random.puml
!include ip/ravelry.puml
!include ip/rebel.puml
!include ip/recycle.puml
!include ip/reddit.puml
!include ip/reddit_alien.puml
!include ip/reddit_square.puml
!include ip/refresh.puml
!include ip/registered.puml
!include ip/remove.puml
!include ip/renren.puml
!include ip/reorder.puml
!include ip/repeat.puml
!include ip/reply.puml
!include ip/reply_all.puml
!include ip/resistance.puml
!include ip/retweet.puml
!include ip/rmb.puml
!include ip/road.puml
!include ip/rocket.puml
!include ip/rotate_left.puml
!include ip/rotate_right.puml
!include ip/rouble.puml
!include ip/rss.puml
!include ip/rss_square.puml
!include ip/rub.puml
!include ip/ruble.puml
!include ip/rupee.puml
!include ip/s15.puml
!include ip/safari.puml
!include ip/save.puml
!include ip/scissors.puml
!include ip/scribd.puml
!include ip/search.puml
!include ip/search_minus.puml
!include ip/search_plus.puml
!include ip/sellsy.puml
!include ip/send.puml
!include ip/send_o.puml
!include ip/server.puml
!include ip/share.puml
!include ip/share_alt.puml
!include ip/share_alt_square.puml
!include ip/share_square.puml
!include ip/share_square_o.puml
!include ip/shekel.puml
!include ip/sheqel.puml
!include ip/shield.puml
!include ip/ship.puml
!include ip/shirtsinbulk.puml
!include ip/shopping_bag.puml
!include ip/shopping_basket.puml
!include ip/shopping_cart.puml
!include ip/shower.puml
!include ip/sign_in.puml
!include ip/sign_language.puml
!include ip/sign_out.puml
!include ip/signal.puml
!include ip/signing.puml
!include ip/simplybuilt.puml
!include ip/sitemap.puml
!include ip/skyatlas.puml
!include ip/skype.puml
!include ip/slack.puml
!include ip/sliders.puml
!include ip/slideshare.puml
!include ip/smile_o.puml
!include ip/snapchat.puml
!include ip/snapchat_ghost.puml
!include ip/snapchat_square.puml
!include ip/snowflake_o.puml
!include ip/soccer_ball_o.puml
!include ip/sort.puml
!include ip/sort_alpha_asc.puml
!include ip/sort_alpha_desc.puml
!include ip/sort_amount_asc.puml
!include ip/sort_amount_desc.puml
!include ip/sort_asc.puml
!include ip/sort_desc.puml
!include ip/sort_down.puml
!include ip/sort_numeric_asc.puml
!include ip/sort_numeric_desc.puml
!include ip/sort_up.puml
!include ip/soundcloud.puml
!include ip/space_shuttle.puml
!include ip/spinner.puml
!include ip/spoon.puml
!include ip/spotify.puml
!include ip/square.puml
!include ip/square_o.puml
!include ip/stack_exchange.puml
!include ip/stack_overflow.puml
!include ip/star.puml
!include ip/star_half.puml
!include ip/star_half_empty.puml
!include ip/star_half_full.puml
!include ip/star_half_o.puml
!include ip/star_o.puml
!include ip/steam.puml
!include ip/steam_square.puml
!include ip/step_backward.puml
!include ip/step_forward.puml
!include ip/stethoscope.puml
!include ip/sticky_note.puml
!include ip/sticky_note_o.puml
!include ip/stop.puml
!include ip/stop_circle.puml
!include ip/stop_circle_o.puml
!include ip/street_view.puml
!include ip/strikethrough.puml
!include ip/stumbleupon.puml
!include ip/stumbleupon_circle.puml
!include ip/subscript.puml
!include ip/subway.puml
!include ip/suitcase.puml
!include ip/sun_o.puml
!include ip/superpowers.puml
!include ip/superscript.puml
!include ip/support.puml
!include ip/table.puml
!include ip/tablet.puml
!include ip/tachometer.puml
!include ip/tag.puml
!include ip/tags.puml
!include ip/tasks.puml
!include ip/taxi.puml
!include ip/telegram.puml
!include ip/television.puml
!include ip/tencent_weibo.puml
!include ip/terminal.puml
!include ip/text_height.puml
!include ip/text_width.puml
!include ip/th.puml
!include ip/th_large.puml
!include ip/th_list.puml
!include ip/themeisle.puml
!include ip/thermometer.puml
!include ip/thermometer_0.puml
!include ip/thermometer_1.puml
!include ip/thermometer_2.puml
!include ip/thermometer_3.puml
!include ip/thermometer_4.puml
!include ip/thermometer_empty.puml
!include ip/thermometer_full.puml
!include ip/thermometer_half.puml
!include ip/thermometer_quarter.puml
!include ip/thermometer_three_quarters.puml
!include ip/thumb_tack.puml
!include ip/thumbs_down.puml
!include ip/thumbs_o_down.puml
!include ip/thumbs_o_up.puml
!include ip/thumbs_up.puml
!include ip/ticket.puml
!include ip/times.puml
!include ip/times_circle.puml
!include ip/times_circle_o.puml
!include ip/times_rectangle.puml
!include ip/times_rectangle_o.puml
!include ip/tint.puml
!include ip/toggle_down.puml
!include ip/toggle_left.puml
!include ip/toggle_off.puml
!include ip/toggle_on.puml
!include ip/toggle_right.puml
!include ip/toggle_up.puml
!include ip/trademark.puml
!include ip/train.puml
!include ip/transgender.puml
!include ip/transgender_alt.puml
!include ip/trash.puml
!include ip/trash_o.puml
!include ip/tree.puml
!include ip/trello.puml
!include ip/tripadvisor.puml
!include ip/trophy.puml
!include ip/truck.puml
!include ip/try.puml
!include ip/tty.puml
!include ip/tumblr.puml
!include ip/tumblr_square.puml
!include ip/turkish_lira.puml
!include ip/tv.puml
!include ip/twitch.puml
!include ip/twitter.puml
!include ip/twitter_square.puml
!include ip/umbrella.puml
!include ip/underline.puml
!include ip/undo.puml
!include ip/universal_access.puml
!include ip/university.puml
!include ip/unlink.puml
!include ip/unlock.puml
!include ip/unlock_alt.puml
!include ip/unsorted.puml
!include ip/upload.puml
!include ip/usb.puml
!include ip/usd.puml
!include ip/user.puml
!include ip/user_circle.puml
!include ip/user_circle_o.puml
!include ip/user_md.puml
!include ip/user_o.puml
!include ip/user_plus.puml
!include ip/user_secret.puml
!include ip/user_times.puml
!include ip/users.puml
!include ip/vcard.puml
!include ip/vcard_o.puml
!include ip/venus.puml
!include ip/venus_double.puml
!include ip/venus_mars.puml
!include ip/viacoin.puml
!include ip/viadeo.puml
!include ip/viadeo_square.puml
!include ip/video_camera.puml
!include ip/vimeo.puml
!include ip/vimeo_square.puml
!include ip/vine.puml
!include ip/vk.puml
!include ip/volume_control_phone.puml
!include ip/volume_down.puml
!include ip/volume_off.puml
!include ip/volume_up.puml
!include ip/warning.puml
!include ip/wechat.puml
!include ip/weibo.puml
!include ip/weixin.puml
!include ip/whatsapp.puml
!include ip/wheelchair.puml
!include ip/wheelchair_alt.puml
!include ip/wifi.puml
!include ip/wikipedia_w.puml
!include ip/window_close.puml
!include ip/window_close_o.puml
!include ip/window_maximize.puml
!include ip/window_minimize.puml
!include ip/window_restore.puml
!include ip/windows.puml
!include ip/won.puml
!include ip/wordpress.puml
!include ip/wpbeginner.puml
!include ip/wpexplorer.puml
!include ip/wpforms.puml
!include ip/wrench.puml
!include ip/xing.puml
!include ip/xing_square.puml
!include ip/y_combinator.puml
!include ip/y_combinator_square.puml
!include ip/yahoo.puml
!include ip/yc.puml
!include ip/yc_square.puml
!include ip/yelp.puml
!include ip/yen.puml
!include ip/yoast.puml
!include ip/youtube.puml
!include ip/youtube_play.puml
!include ip/youtube_square.puml

listsprites
@enduml
