@startuml
!define pc /Volumes/SRC/plantuml-stdlib/tupadr3
!include pc/common.puml
!define ip /Volumes/SRC/plantuml-stdlib/tupadr3/govicons
!include ip/18F_logo.puml
!include ip/540_fedapi.puml
!include ip/540_logo.puml
!include ip/airplane.puml
!include ip/ambulance.puml
!include ip/ammo.puml
!include ip/balance.puml
!include ip/bar_chart.puml
!include ip/barcode.puml
!include ip/biohazard.puml
!include ip/book.puml
!include ip/briefcase.puml
!include ip/building.puml
!include ip/bus_front.puml
!include ip/capitol.puml
!include ip/check.puml
!include ip/check_square_o.puml
!include ip/clock_o.puml
!include ip/cloud.puml
!include ip/cloud_o.puml
!include ip/code.puml
!include ip/cog.puml
!include ip/cogs.puml
!include ip/comment.puml
!include ip/comments.puml
!include ip/construction.puml
!include ip/database.puml
!include ip/dc_flag.puml
!include ip/dc_map.puml
!include ip/desktop.puml
!include ip/dna.puml
!include ip/dogtags.puml
!include ip/donkey.puml
!include ip/drone.puml
!include ip/elephant.puml
!include ip/factory.puml
!include ip/file.puml
!include ip/file_contract_o.puml
!include ip/file_excel.puml
!include ip/file_excel_o.puml
!include ip/file_o.puml
!include ip/file_text.puml
!include ip/file_text_o.puml
!include ip/file_word.puml
!include ip/file_word_o.puml
!include ip/fingerprint.puml
!include ip/folder.puml
!include ip/folder_misc.puml
!include ip/gavel.puml
!include ip/gun.puml
!include ip/handshake.puml
!include ip/hard_hat.puml
!include ip/heartbeat.puml
!include ip/helicopter.puml
!include ip/id_card.puml
!include ip/id_card_o.puml
!include ip/jefferson_memorial.puml
!include ip/jet.puml
!include ip/key.puml
!include ip/leaf.puml
!include ip/liberty_bell.puml
!include ip/lightbulb.puml
!include ip/lincoln_memorial.puml
!include ip/line_chart.puml
!include ip/lock.puml
!include ip/medal_circle.puml
!include ip/medal_star.puml
!include ip/medkit.puml
!include ip/metro_front.puml
!include ip/microscope.puml
!include ip/missile.puml
!include ip/mobile.puml
!include ip/money.puml
!include ip/nuclear_plant.puml
!include ip/pallet.puml
!include ip/pentagon.puml
!include ip/pie_chart.puml
!include ip/poison.puml
!include ip/poison_bottle.puml
!include ip/presenter.puml
!include ip/radar.puml
!include ip/radioactive.puml
!include ip/recycle.puml
!include ip/reticle_crosshair.puml
!include ip/reticle_dot.puml
!include ip/ribbon.puml
!include ip/road.puml
!include ip/road_barricade.puml
!include ip/road_sign.puml
!include ip/ruler.puml
!include ip/satellite.puml
!include ip/script.puml
!include ip/search.puml
!include ip/security_camera.puml
!include ip/shield.puml
!include ip/shield_o.puml
!include ip/ship_front.puml
!include ip/statue_of_liberty.puml
!include ip/stethoscope.puml
!include ip/submarine.puml
!include ip/table.puml
!include ip/tables.puml
!include ip/tablet.puml
!include ip/tank.puml
!include ip/textile.puml
!include ip/times.puml
!include ip/tools.puml
!include ip/train_front.puml
!include ip/truck.puml
!include ip/truck_front.puml
!include ip/unlock.puml
!include ip/us_flag_straight.puml
!include ip/us_flag_wavy.puml
!include ip/us_map.puml
!include ip/us_shield.puml
!include ip/us_tophat.puml
!include ip/usd.puml
!include ip/user.puml
!include ip/user_graduate.puml
!include ip/user_military.puml
!include ip/user_politician.puml
!include ip/user_suit.puml
!include ip/users.puml
!include ip/vote.puml
!include ip/warning.puml
!include ip/washington_monument.puml
!include ip/wheel_barrow.puml
!include ip/white_house.puml
!include ip/world.puml
listsprites
@enduml
