@startuml
!define pc /Volumes/SRC/plantuml-stdlib/tupadr3
!include pc/common.puml
!define ip /Volumes/SRC/plantuml-stdlib/tupadr3/material

!include ip/3d_rotation.puml
!include ip/ac_unit.puml
!include ip/access_alarm.puml
!include ip/access_alarms.puml
!include ip/access_time.puml
!include ip/accessibility.puml
!include ip/accessible.puml
!include ip/account_balance.puml
!include ip/account_balance_wallet.puml
!include ip/account_box.puml
!include ip/account_circle.puml
!include ip/adb.puml
!include ip/add.puml
!include ip/add_a_photo.puml
!include ip/add_alarm.puml
!include ip/add_alert.puml
!include ip/add_box.puml
!include ip/add_circle.puml
!include ip/add_circle_outline.puml
!include ip/add_location.puml
!include ip/add_shopping_cart.puml
!include ip/add_to_photos.puml
!include ip/add_to_queue.puml
!include ip/adjust.puml
!include ip/airline_seat_flat.puml
!include ip/airline_seat_flat_angled.puml
!include ip/airline_seat_individual_suite.puml
!include ip/airline_seat_legroom_extra.puml
!include ip/airline_seat_legroom_normal.puml
!include ip/airline_seat_legroom_reduced.puml
!include ip/airline_seat_recline_extra.puml
!include ip/airline_seat_recline_normal.puml
!include ip/airplanemode_active.puml
!include ip/airplanemode_inactive.puml
!include ip/airplay.puml
!include ip/airport_shuttle.puml
!include ip/alarm.puml
!include ip/alarm_add.puml
!include ip/alarm_off.puml
!include ip/alarm_on.puml
!include ip/album.puml
!include ip/all_inclusive.puml
!include ip/all_out.puml
!include ip/android.puml
!include ip/announcement.puml
!include ip/apps.puml
!include ip/archive.puml
!include ip/arrow_back.puml
!include ip/arrow_downward.puml
!include ip/arrow_drop_down.puml
!include ip/arrow_drop_down_circle.puml
!include ip/arrow_drop_up.puml
!include ip/arrow_forward.puml
!include ip/arrow_upward.puml
!include ip/art_track.puml
!include ip/aspect_ratio.puml
!include ip/assessment.puml
!include ip/assignment.puml
!include ip/assignment_ind.puml
!include ip/assignment_late.puml
!include ip/assignment_return.puml
!include ip/assignment_returned.puml
!include ip/assignment_turned_in.puml
!include ip/assistant.puml
!include ip/assistant_photo.puml
!include ip/attach_file.puml
!include ip/attach_money.puml
!include ip/attachment.puml
!include ip/audiotrack.puml
!include ip/autorenew.puml
!include ip/av_timer.puml
!include ip/backspace.puml
!include ip/backup.puml
!include ip/battery_alert.puml
!include ip/battery_charging_full.puml
!include ip/battery_full.puml
!include ip/battery_std.puml
!include ip/battery_unknown.puml
!include ip/beach_access.puml
!include ip/beenhere.puml
!include ip/block.puml
!include ip/bluetooth.puml
!include ip/bluetooth_audio.puml
!include ip/bluetooth_connected.puml
!include ip/bluetooth_disabled.puml
!include ip/bluetooth_searching.puml
!include ip/blur_circular.puml
!include ip/blur_linear.puml
!include ip/blur_off.puml
!include ip/blur_on.puml
!include ip/book.puml
!include ip/bookmark.puml
!include ip/bookmark_border.puml
!include ip/border_all.puml
!include ip/border_bottom.puml
!include ip/border_clear.puml
!include ip/border_color.puml
!include ip/border_horizontal.puml
!include ip/border_inner.puml
!include ip/border_left.puml
!include ip/border_outer.puml
!include ip/border_right.puml
!include ip/border_style.puml
!include ip/border_top.puml
!include ip/border_vertical.puml
!include ip/branding_watermark.puml
!include ip/brightness_1.puml
!include ip/brightness_2.puml
!include ip/brightness_3.puml
!include ip/brightness_4.puml
!include ip/brightness_5.puml
!include ip/brightness_6.puml
!include ip/brightness_7.puml
!include ip/brightness_auto.puml
!include ip/brightness_high.puml
!include ip/brightness_low.puml
!include ip/brightness_medium.puml
!include ip/broken_image.puml
!include ip/brush.puml
!include ip/bubble_chart.puml
!include ip/bug_report.puml
!include ip/build.puml
!include ip/burst_mode.puml
!include ip/business.puml
!include ip/business_center.puml
!include ip/cached.puml
!include ip/cake.puml
!include ip/call.puml
!include ip/call_end.puml
!include ip/call_made.puml
!include ip/call_merge.puml
!include ip/call_missed.puml
!include ip/call_missed_outgoing.puml
!include ip/call_received.puml
!include ip/call_split.puml
!include ip/call_to_action.puml
!include ip/camera.puml
!include ip/camera_alt.puml
!include ip/camera_enhance.puml
!include ip/camera_front.puml
!include ip/camera_rear.puml
!include ip/camera_roll.puml
!include ip/cancel.puml
!include ip/card_giftcard.puml
!include ip/card_membership.puml
!include ip/card_travel.puml
!include ip/casino.puml
!include ip/cast.puml
!include ip/cast_connected.puml
!include ip/center_focus_strong.puml
!include ip/center_focus_weak.puml
!include ip/change_history.puml
!include ip/chat.puml
!include ip/chat_bubble.puml
!include ip/chat_bubble_outline.puml
!include ip/check.puml
!include ip/check_box.puml
!include ip/check_box_outline_blank.puml
!include ip/check_circle.puml
!include ip/chevron_left.puml
!include ip/chevron_right.puml
!include ip/child_care.puml
!include ip/child_friendly.puml
!include ip/chrome_reader_mode.puml
!include ip/class.puml
!include ip/clear.puml
!include ip/clear_all.puml
!include ip/close.puml
!include ip/closed_caption.puml
!include ip/cloud.puml
!include ip/cloud_circle.puml
!include ip/cloud_done.puml
!include ip/cloud_download.puml
!include ip/cloud_off.puml
!include ip/cloud_queue.puml
!include ip/cloud_upload.puml
!include ip/code.puml
!include ip/collections.puml
!include ip/collections_bookmark.puml
!include ip/color_lens.puml
!include ip/colorize.puml
!include ip/comment.puml
!include ip/compare.puml
!include ip/compare_arrows.puml
!include ip/computer.puml
!include ip/confirmation_number.puml
!include ip/contact_mail.puml
!include ip/contact_phone.puml
!include ip/contacts.puml
!include ip/content_copy.puml
!include ip/content_cut.puml
!include ip/content_paste.puml
!include ip/control_point.puml
!include ip/control_point_duplicate.puml
!include ip/copyright.puml
!include ip/create.puml
!include ip/create_new_folder.puml
!include ip/credit_card.puml
!include ip/crop.puml
!include ip/crop_16_9.puml
!include ip/crop_3_2.puml
!include ip/crop_5_4.puml
!include ip/crop_7_5.puml
!include ip/crop_din.puml
!include ip/crop_free.puml
!include ip/crop_landscape.puml
!include ip/crop_original.puml
!include ip/crop_portrait.puml
!include ip/crop_rotate.puml
!include ip/crop_square.puml
!include ip/dashboard.puml
!include ip/data_usage.puml
!include ip/date_range.puml
!include ip/dehaze.puml
!include ip/delete.puml
!include ip/delete_forever.puml
!include ip/delete_sweep.puml
!include ip/description.puml
!include ip/desktop_mac.puml
!include ip/desktop_windows.puml
!include ip/details.puml
!include ip/developer_board.puml
!include ip/developer_mode.puml
!include ip/device_hub.puml
!include ip/devices.puml
!include ip/devices_other.puml
!include ip/dialer_sip.puml
!include ip/dialpad.puml
!include ip/directions.puml
!include ip/directions_bike.puml
!include ip/directions_boat.puml
!include ip/directions_bus.puml
!include ip/directions_car.puml
!include ip/directions_railway.puml
!include ip/directions_run.puml
!include ip/directions_subway.puml
!include ip/directions_transit.puml
!include ip/directions_walk.puml
!include ip/disc_full.puml
!include ip/dns.puml
!include ip/do_not_disturb.puml
!include ip/do_not_disturb_alt.puml
!include ip/do_not_disturb_off.puml
!include ip/do_not_disturb_on.puml
!include ip/dock.puml
!include ip/domain.puml
!include ip/done.puml
!include ip/done_all.puml
!include ip/donut_large.puml
!include ip/donut_small.puml
!include ip/drafts.puml
!include ip/drag_handle.puml
!include ip/drive_eta.puml
!include ip/dvr.puml
!include ip/edit.puml
!include ip/edit_location.puml
!include ip/eject.puml
!include ip/email.puml
!include ip/enhanced_encryption.puml
!include ip/equalizer.puml
!include ip/error.puml
!include ip/error_outline.puml
!include ip/euro_symbol.puml
!include ip/ev_station.puml
!include ip/event.puml
!include ip/event_available.puml
!include ip/event_busy.puml
!include ip/event_note.puml
!include ip/event_seat.puml
!include ip/exit_to_app.puml
!include ip/expand_less.puml
!include ip/expand_more.puml
!include ip/explicit.puml
!include ip/explore.puml
!include ip/exposure.puml
!include ip/exposure_neg_1.puml
!include ip/exposure_neg_2.puml
!include ip/exposure_plus_1.puml
!include ip/exposure_plus_2.puml
!include ip/exposure_zero.puml
!include ip/extension.puml
!include ip/face.puml
!include ip/fast_forward.puml
!include ip/fast_rewind.puml
!include ip/favorite.puml
!include ip/favorite_border.puml
!include ip/featured_play_list.puml
!include ip/featured_video.puml
!include ip/feedback.puml
!include ip/fiber_dvr.puml
!include ip/fiber_manual_record.puml
!include ip/fiber_new.puml
!include ip/fiber_pin.puml
!include ip/fiber_smart_record.puml
!include ip/file_download.puml
!include ip/file_upload.puml
!include ip/filter.puml
!include ip/filter_1.puml
!include ip/filter_2.puml
!include ip/filter_3.puml
!include ip/filter_4.puml
!include ip/filter_5.puml
!include ip/filter_6.puml
!include ip/filter_7.puml
!include ip/filter_8.puml
!include ip/filter_9.puml
!include ip/filter_9_plus.puml
!include ip/filter_b_and_w.puml
!include ip/filter_center_focus.puml
!include ip/filter_drama.puml
!include ip/filter_frames.puml
!include ip/filter_hdr.puml
!include ip/filter_list.puml
!include ip/filter_none.puml
!include ip/filter_tilt_shift.puml
!include ip/filter_vintage.puml
!include ip/find_in_page.puml
!include ip/find_replace.puml
!include ip/fingerprint.puml
!include ip/first_page.puml
!include ip/fitness_center.puml
!include ip/flag.puml
!include ip/flare.puml
!include ip/flash_auto.puml
!include ip/flash_off.puml
!include ip/flash_on.puml
!include ip/flight.puml
!include ip/flight_land.puml
!include ip/flight_takeoff.puml
!include ip/flip.puml
!include ip/flip_to_back.puml
!include ip/flip_to_front.puml
!include ip/folder.puml
!include ip/folder_open.puml
!include ip/folder_shared.puml
!include ip/folder_special.puml
!include ip/font_download.puml
!include ip/format_align_center.puml
!include ip/format_align_justify.puml
!include ip/format_align_left.puml
!include ip/format_align_right.puml
!include ip/format_bold.puml
!include ip/format_clear.puml
!include ip/format_color_fill.puml
!include ip/format_color_reset.puml
!include ip/format_color_text.puml
!include ip/format_indent_decrease.puml
!include ip/format_indent_increase.puml
!include ip/format_italic.puml
!include ip/format_line_spacing.puml
!include ip/format_list_bulleted.puml
!include ip/format_list_numbered.puml
!include ip/format_paint.puml
!include ip/format_quote.puml
!include ip/format_shapes.puml
!include ip/format_size.puml
!include ip/format_strikethrough.puml
!include ip/format_textdirection_l_to_r.puml
!include ip/format_textdirection_r_to_l.puml
!include ip/format_underlined.puml
!include ip/forum.puml
!include ip/forward.puml
!include ip/forward_10.puml
!include ip/forward_30.puml
!include ip/forward_5.puml
!include ip/free_breakfast.puml
!include ip/fullscreen.puml
!include ip/fullscreen_exit.puml
!include ip/functions.puml
!include ip/g_translate.puml
!include ip/gamepad.puml
!include ip/games.puml
!include ip/gavel.puml
!include ip/gesture.puml
!include ip/get_app.puml
!include ip/gif.puml
!include ip/goat.puml
!include ip/golf_course.puml
!include ip/gps_fixed.puml
!include ip/gps_not_fixed.puml
!include ip/gps_off.puml
!include ip/grade.puml
!include ip/gradient.puml
!include ip/grain.puml
!include ip/graphic_eq.puml
!include ip/grid_off.puml
!include ip/grid_on.puml
!include ip/group.puml
!include ip/group_add.puml
!include ip/group_work.puml
!include ip/hd.puml
!include ip/hdr_off.puml
!include ip/hdr_on.puml
!include ip/hdr_strong.puml
!include ip/hdr_weak.puml
!include ip/headset.puml
!include ip/headset_mic.puml
!include ip/healing.puml
!include ip/hearing.puml
!include ip/help.puml
!include ip/help_outline.puml
!include ip/high_quality.puml
!include ip/highlight.puml
!include ip/highlight_off.puml
!include ip/history.puml
!include ip/home.puml
!include ip/hot_tub.puml
!include ip/hotel.puml
!include ip/hourglass_empty.puml
!include ip/hourglass_full.puml
!include ip/http.puml
!include ip/https.puml
!include ip/image.puml
!include ip/image_aspect_ratio.puml
!include ip/import_contacts.puml
!include ip/import_export.puml
!include ip/important_devices.puml
!include ip/inbox.puml
!include ip/indeterminate_check_box.puml
!include ip/info.puml
!include ip/info_outline.puml
!include ip/input.puml
!include ip/insert_chart.puml
!include ip/insert_comment.puml
!include ip/insert_drive_file.puml
!include ip/insert_emoticon.puml
!include ip/insert_invitation.puml
!include ip/insert_link.puml
!include ip/insert_photo.puml
!include ip/invert_colors.puml
!include ip/invert_colors_off.puml
!include ip/iso.puml
!include ip/keyboard.puml
!include ip/keyboard_arrow_down.puml
!include ip/keyboard_arrow_left.puml
!include ip/keyboard_arrow_right.puml
!include ip/keyboard_arrow_up.puml
!include ip/keyboard_backspace.puml
!include ip/keyboard_capslock.puml
!include ip/keyboard_hide.puml
!include ip/keyboard_return.puml
!include ip/keyboard_tab.puml
!include ip/keyboard_voice.puml
!include ip/kitchen.puml
!include ip/label.puml
!include ip/label_outline.puml
!include ip/landscape.puml
!include ip/language.puml
!include ip/laptop.puml
!include ip/laptop_chromebook.puml
!include ip/laptop_mac.puml
!include ip/laptop_windows.puml
!include ip/last_page.puml
!include ip/launch.puml
!include ip/layers.puml
!include ip/layers_clear.puml
!include ip/leak_add.puml
!include ip/leak_remove.puml
!include ip/lens.puml
!include ip/library_add.puml
!include ip/library_books.puml
!include ip/library_music.puml
!include ip/lightbulb_outline.puml
!include ip/line_style.puml
!include ip/line_weight.puml
!include ip/linear_scale.puml
!include ip/link.puml
!include ip/linked_camera.puml
!include ip/list.puml
!include ip/live_help.puml
!include ip/live_tv.puml
!include ip/local_activity.puml
!include ip/local_airport.puml
!include ip/local_atm.puml
!include ip/local_bar.puml
!include ip/local_cafe.puml
!include ip/local_car_wash.puml
!include ip/local_convenience_store.puml
!include ip/local_dining.puml
!include ip/local_drink.puml
!include ip/local_florist.puml
!include ip/local_gas_station.puml
!include ip/local_grocery_store.puml
!include ip/local_hospital.puml
!include ip/local_hotel.puml
!include ip/local_laundry_service.puml
!include ip/local_library.puml
!include ip/local_mall.puml
!include ip/local_movies.puml
!include ip/local_offer.puml
!include ip/local_parking.puml
!include ip/local_pharmacy.puml
!include ip/local_phone.puml
!include ip/local_pizza.puml
!include ip/local_play.puml
!include ip/local_post_office.puml
!include ip/local_printshop.puml
!include ip/local_see.puml
!include ip/local_shipping.puml
!include ip/local_taxi.puml
!include ip/location_city.puml
!include ip/location_disabled.puml
!include ip/location_off.puml
!include ip/location_on.puml
!include ip/location_searching.puml
!include ip/lock.puml
!include ip/lock_open.puml
!include ip/lock_outline.puml
!include ip/looks.puml
!include ip/looks_3.puml
!include ip/looks_4.puml
!include ip/looks_5.puml
!include ip/looks_6.puml
!include ip/looks_one.puml
!include ip/looks_two.puml
!include ip/loop.puml
!include ip/loupe.puml
!include ip/low_priority.puml
!include ip/loyalty.puml
!include ip/mail.puml
!include ip/mail_outline.puml
!include ip/map.puml
!include ip/markunread.puml
!include ip/markunread_mailbox.puml
!include ip/memory.puml
!include ip/menu.puml
!include ip/merge_type.puml
!include ip/message.puml
!include ip/mic.puml
!include ip/mic_none.puml
!include ip/mic_off.puml
!include ip/mms.puml
!include ip/mode_comment.puml
!include ip/mode_edit.puml
!include ip/monetization_on.puml
!include ip/money_off.puml
!include ip/monochrome_photos.puml
!include ip/mood.puml
!include ip/mood_bad.puml
!include ip/more.puml
!include ip/more_horiz.puml
!include ip/more_vert.puml
!include ip/motorcycle.puml
!include ip/mouse.puml
!include ip/move_to_inbox.puml
!include ip/movie.puml
!include ip/movie_creation.puml
!include ip/movie_filter.puml
!include ip/multiline_chart.puml
!include ip/music_note.puml
!include ip/music_video.puml
!include ip/my_location.puml
!include ip/nature.puml
!include ip/nature_people.puml
!include ip/navigate_before.puml
!include ip/navigate_next.puml
!include ip/navigation.puml
!include ip/near_me.puml
!include ip/network_cell.puml
!include ip/network_check.puml
!include ip/network_locked.puml
!include ip/network_wifi.puml
!include ip/new_releases.puml
!include ip/next_week.puml
!include ip/nfc.puml
!include ip/no_encryption.puml
!include ip/no_sim.puml
!include ip/not_interested.puml
!include ip/note.puml
!include ip/note_add.puml
!include ip/notifications.puml
!include ip/notifications_active.puml
!include ip/notifications_none.puml
!include ip/notifications_off.puml
!include ip/notifications_paused.puml
!include ip/offline_pin.puml
!include ip/ondemand_video.puml
!include ip/opacity.puml
!include ip/open_in_browser.puml
!include ip/open_in_new.puml
!include ip/open_with.puml
!include ip/pages.puml
!include ip/pageview.puml
!include ip/palette.puml
!include ip/pan_tool.puml
!include ip/panorama.puml
!include ip/panorama_fish_eye.puml
!include ip/panorama_horizontal.puml
!include ip/panorama_vertical.puml
!include ip/panorama_wide_angle.puml
!include ip/party_mode.puml
!include ip/pause.puml
!include ip/pause_circle_filled.puml
!include ip/pause_circle_outline.puml
!include ip/payment.puml
!include ip/people.puml
!include ip/people_outline.puml
!include ip/perm_camera_mic.puml
!include ip/perm_contact_calendar.puml
!include ip/perm_data_setting.puml
!include ip/perm_device_information.puml
!include ip/perm_identity.puml
!include ip/perm_media.puml
!include ip/perm_phone_msg.puml
!include ip/perm_scan_wifi.puml
!include ip/person.puml
!include ip/person_add.puml
!include ip/person_outline.puml
!include ip/person_pin.puml
!include ip/person_pin_circle.puml
!include ip/personal_video.puml
!include ip/pets.puml
!include ip/phone.puml
!include ip/phone_android.puml
!include ip/phone_bluetooth_speaker.puml
!include ip/phone_forwarded.puml
!include ip/phone_in_talk.puml
!include ip/phone_iphone.puml
!include ip/phone_locked.puml
!include ip/phone_missed.puml
!include ip/phone_paused.puml
!include ip/phonelink.puml
!include ip/phonelink_erase.puml
!include ip/phonelink_lock.puml
!include ip/phonelink_off.puml
!include ip/phonelink_ring.puml
!include ip/phonelink_setup.puml
!include ip/photo.puml
!include ip/photo_album.puml
!include ip/photo_camera.puml
!include ip/photo_filter.puml
!include ip/photo_library.puml
!include ip/photo_size_select_actual.puml
!include ip/photo_size_select_large.puml
!include ip/photo_size_select_small.puml
!include ip/picture_as_pdf.puml
!include ip/picture_in_picture.puml
!include ip/picture_in_picture_alt.puml
!include ip/pie_chart.puml
!include ip/pie_chart_outlined.puml
!include ip/pin_drop.puml
!include ip/place.puml
!include ip/play_arrow.puml
!include ip/play_circle_filled.puml
!include ip/play_circle_outline.puml
!include ip/play_for_work.puml
!include ip/playlist_add.puml
!include ip/playlist_add_check.puml
!include ip/playlist_play.puml
!include ip/plus_one.puml
!include ip/poll.puml
!include ip/polymer.puml
!include ip/pool.puml
!include ip/portable_wifi_off.puml
!include ip/portrait.puml
!include ip/power.puml
!include ip/power_input.puml
!include ip/power_settings_new.puml
!include ip/pregnant_woman.puml
!include ip/present_to_all.puml
!include ip/print.puml
!include ip/priority_high.puml
!include ip/public.puml
!include ip/publish.puml
!include ip/query_builder.puml
!include ip/question_answer.puml
!include ip/queue.puml
!include ip/queue_music.puml
!include ip/queue_play_next.puml
!include ip/radio.puml
!include ip/radio_button_checked.puml
!include ip/radio_button_unchecked.puml
!include ip/rate_review.puml
!include ip/receipt.puml
!include ip/recent_actors.puml
!include ip/record_voice_over.puml
!include ip/redeem.puml
!include ip/redo.puml
!include ip/refresh.puml
!include ip/remove.puml
!include ip/remove_circle.puml
!include ip/remove_circle_outline.puml
!include ip/remove_from_queue.puml
!include ip/remove_red_eye.puml
!include ip/remove_shopping_cart.puml
!include ip/reorder.puml
!include ip/repeat.puml
!include ip/repeat_one.puml
!include ip/replay.puml
!include ip/replay_10.puml
!include ip/replay_30.puml
!include ip/replay_5.puml
!include ip/reply.puml
!include ip/reply_all.puml
!include ip/report.puml
!include ip/report_problem.puml
!include ip/restaurant.puml
!include ip/restaurant_menu.puml
!include ip/restore.puml
!include ip/restore_page.puml
!include ip/ring_volume.puml
!include ip/room.puml
!include ip/room_service.puml
!include ip/rotate_90_degrees_ccw.puml
!include ip/rotate_left.puml
!include ip/rotate_right.puml
!include ip/rounded_corner.puml
!include ip/router.puml
!include ip/rowing.puml
!include ip/rss_feed.puml
!include ip/rv_hookup.puml
!include ip/satellite.puml
!include ip/save.puml
!include ip/scanner.puml
!include ip/schedule.puml
!include ip/school.puml
!include ip/screen_lock_landscape.puml
!include ip/screen_lock_portrait.puml
!include ip/screen_lock_rotation.puml
!include ip/screen_rotation.puml
!include ip/screen_share.puml
!include ip/sd_card.puml
!include ip/sd_storage.puml
!include ip/search.puml
!include ip/security.puml
!include ip/select_all.puml
!include ip/send.puml
!include ip/sentiment_dissatisfied.puml
!include ip/sentiment_neutral.puml
!include ip/sentiment_satisfied.puml
!include ip/sentiment_very_dissatisfied.puml
!include ip/sentiment_very_satisfied.puml
!include ip/settings.puml
!include ip/settings_applications.puml
!include ip/settings_backup_restore.puml
!include ip/settings_bluetooth.puml
!include ip/settings_brightness.puml
!include ip/settings_cell.puml
!include ip/settings_ethernet.puml
!include ip/settings_input_antenna.puml
!include ip/settings_input_component.puml
!include ip/settings_input_composite.puml
!include ip/settings_input_hdmi.puml
!include ip/settings_input_svideo.puml
!include ip/settings_overscan.puml
!include ip/settings_phone.puml
!include ip/settings_power.puml
!include ip/settings_remote.puml
!include ip/settings_system_daydream.puml
!include ip/settings_voice.puml
!include ip/share.puml
!include ip/shop.puml
!include ip/shop_two.puml
!include ip/shopping_basket.puml
!include ip/shopping_cart.puml
!include ip/short_text.puml
!include ip/show_chart.puml
!include ip/shuffle.puml
!include ip/signal_cellular_4_bar.puml
!include ip/signal_cellular_connected_no_internet_4_bar.puml
!include ip/signal_cellular_no_sim.puml
!include ip/signal_cellular_null.puml
!include ip/signal_cellular_off.puml
!include ip/signal_wifi_4_bar.puml
!include ip/signal_wifi_4_bar_lock.puml
!include ip/signal_wifi_off.puml
!include ip/sim_card.puml
!include ip/sim_card_alert.puml
!include ip/skip_next.puml
!include ip/skip_previous.puml
!include ip/slideshow.puml
!include ip/slow_motion_video.puml
!include ip/smartphone.puml
!include ip/smoke_free.puml
!include ip/smoking_rooms.puml
!include ip/sms.puml
!include ip/sms_failed.puml
!include ip/snooze.puml
!include ip/sort.puml
!include ip/sort_by_alpha.puml
!include ip/spa.puml
!include ip/space_bar.puml
!include ip/speaker.puml
!include ip/speaker_group.puml
!include ip/speaker_notes.puml
!include ip/speaker_notes_off.puml
!include ip/speaker_phone.puml
!include ip/spellcheck.puml
!include ip/star.puml
!include ip/star_border.puml
!include ip/star_half.puml
!include ip/stars.puml
!include ip/stay_current_landscape.puml
!include ip/stay_current_portrait.puml
!include ip/stay_primary_landscape.puml
!include ip/stay_primary_portrait.puml
!include ip/stop.puml
!include ip/stop_screen_share.puml
!include ip/storage.puml
!include ip/store.puml
!include ip/store_mall_directory.puml
!include ip/straighten.puml
!include ip/streetview.puml
!include ip/strikethrough_s.puml
!include ip/style.puml
!include ip/subdirectory_arrow_left.puml
!include ip/subdirectory_arrow_right.puml
!include ip/subject.puml
!include ip/subscriptions.puml
!include ip/subtitles.puml
!include ip/subway.puml
!include ip/supervisor_account.puml
!include ip/surround_sound.puml
!include ip/swap_calls.puml
!include ip/swap_horiz.puml
!include ip/swap_vert.puml
!include ip/swap_vertical_circle.puml
!include ip/switch_camera.puml
!include ip/switch_video.puml
!include ip/sync.puml
!include ip/sync_disabled.puml
!include ip/sync_problem.puml
!include ip/system_update.puml
!include ip/system_update_alt.puml
!include ip/tab.puml
!include ip/tab_unselected.puml
!include ip/tablet.puml
!include ip/tablet_android.puml
!include ip/tablet_mac.puml
!include ip/tag_faces.puml
!include ip/tap_and_play.puml
!include ip/terrain.puml
!include ip/text_fields.puml
!include ip/text_format.puml
!include ip/textsms.puml
!include ip/texture.puml
!include ip/theaters.puml
!include ip/thumb_down.puml
!include ip/thumb_up.puml
!include ip/thumbs_up_down.puml
!include ip/time_to_leave.puml
!include ip/timelapse.puml
!include ip/timeline.puml
!include ip/timer.puml
!include ip/timer_10.puml
!include ip/timer_3.puml
!include ip/timer_off.puml
!include ip/title.puml
!include ip/toc.puml
!include ip/today.puml
!include ip/toll.puml
!include ip/tonality.puml
!include ip/touch_app.puml
!include ip/toys.puml
!include ip/track_changes.puml
!include ip/traffic.puml
!include ip/train.puml
!include ip/tram.puml
!include ip/transfer_within_a_station.puml
!include ip/transform.puml
!include ip/translate.puml
!include ip/trending_down.puml
!include ip/trending_flat.puml
!include ip/trending_up.puml
!include ip/tune.puml
!include ip/turned_in.puml
!include ip/turned_in_not.puml
!include ip/tv.puml
!include ip/unarchive.puml
!include ip/undo.puml
!include ip/unfold_less.puml
!include ip/unfold_more.puml
!include ip/update.puml
!include ip/usb.puml
!include ip/verified_user.puml
!include ip/vertical_align_bottom.puml
!include ip/vertical_align_center.puml
!include ip/vertical_align_top.puml
!include ip/vibration.puml
!include ip/video_call.puml
!include ip/video_label.puml
!include ip/video_library.puml
!include ip/videocam.puml
!include ip/videocam_off.puml
!include ip/videogame_asset.puml
!include ip/view_agenda.puml
!include ip/view_array.puml
!include ip/view_carousel.puml
!include ip/view_column.puml
!include ip/view_comfy.puml
!include ip/view_compact.puml
!include ip/view_day.puml
!include ip/view_headline.puml
!include ip/view_list.puml
!include ip/view_module.puml
!include ip/view_quilt.puml
!include ip/view_stream.puml
!include ip/view_week.puml
!include ip/vignette.puml
!include ip/visibility.puml
!include ip/visibility_off.puml
!include ip/voice_chat.puml
!include ip/voicemail.puml
!include ip/volume_down.puml
!include ip/volume_mute.puml
!include ip/volume_off.puml
!include ip/volume_up.puml
!include ip/vpn_key.puml
!include ip/vpn_lock.puml
!include ip/wallpaper.puml
!include ip/warning.puml
!include ip/watch.puml
!include ip/watch_later.puml
!include ip/wb_auto.puml
!include ip/wb_cloudy.puml
!include ip/wb_incandescent.puml
!include ip/wb_iridescent.puml
!include ip/wb_sunny.puml
!include ip/wc.puml
!include ip/web.puml
!include ip/web_asset.puml
!include ip/weekend.puml
!include ip/whatshot.puml
!include ip/widgets.puml
!include ip/wifi.puml
!include ip/wifi_lock.puml
!include ip/wifi_tethering.puml
!include ip/work.puml
!include ip/wrap_text.puml
!include ip/youtube_searched_for.puml
!include ip/zoom_in.puml
!include ip/zoom_out.puml
!include ip/zoom_out_map.puml
@enduml
