# Sequence Diagram Example
@startuml
    'General Defaults
    !define BASEPATH ../../_puml-includes
    !include BASEPATH/stylesheet.iuml
    !include BASEPATH/functions.iuml

    skinparam {
        NoteBorderColor #999
        NoteBackgroundColor #ffcc00
    }
    ' Using a custom function defined in "functions.iuml"
    tmNoteOver("A,B","here is some stuff")

    'Actor Definitions
    participant A as "Actor A"

    ' Enable Auto-numbering
    autonumber 1 "0:"
    title Sequence Diagram

    A -> B: Perform Action
    B -[#Red]-> A: (Response)
    note over A,B
        Hello there.
    end note

@enduml