@startuml

' Assign colors from a STYLE_THEME.
' Options are: [ DEFAULT | LIGHT | DARK | MIDNIGHT ]
!define STYLE_THEME MIDNIGHT
'!define STYLE_THEME LIGHT
'!define STYLE_THEME DEFAULT
'!define STYLE_THEME DARK

' Color Definitions
'  - Choose the individual color you want by applying them here.
'  - You can define these values in prior to your "!import"
'    statements. Otherwise, a default value is used.
'  - If these values are defined, they override the "STYLE_THEME" settings.
'  - Options are [ STYLE_ACCENT, STYLE_BGC, STYLE_FGC, STYLE_LINE ]
!define STYLE_ACCENT #00ff00
!define STYLE_BGC #9900FF
!define STYLE_FGC #FFCC00
!define STYLE_LINE #0fd000

' Load preset styles.

'!define TEST_CONCAT "HELLO CONCAT!"

!ifdef TEST_CONCAT
    !define TEST_TITLE %get_variable_value("TEST_CONCAT")
!else
    !define TEST_TITLE "This is a default."
!endif

' You can still override individual styles, if need be.
skinparam {
    DPI 100
    SequenceGroupBodyBackgroundColor #Turquoise
    NoteBorderColor #999
    NoteBackgroundColor #Gray
}

' Using a custom function defined in "functions.iuml"
tmNoteOver("A,B","<color:#fff>here is some stuff")

'Actor Definitions
participant A as "Actor A"

' Enable Auto-numbering
autonumber 1 "0:"

title %get_variable_value("TEST_TITLE")
group Some Group
    A -> B: Perform Action
    B --> A: (Response)
end group
note over A,B
    Hello there.
end note


@enduml