@startuml

' help skinparam

' Load preset styles.
!define BASEPATH ../../_puml-includes
!include BASEPATH/style-presets.iuml

' Color Definition
' Choose the style you want by applying them here.

!define STYLE_ACCENT STYLE_DEFAULT_ACCENT
!define STYLE_BGC STYLE_DEFAULT_BGC
!define STYLE_FGC STYLE_DEFAULT_FGC

skinparam {
    ActivityBackgroundColor STYLE_BGC
    ActivityBarColor STYLE_ACCENT
    ActivityBorderColor STYLE_ACCENT
    ' ActivityBorderThickness
    ActivityDiamondBackgroundColor STYLE_BGC
    ActivityDiamondBorderColor STYLE_ACCENT
    ActivityDiamondFontColor STYLE_ACCENT
    ' ActivityDiamondFontName
    ' ActivityDiamondFontSize
    ' ActivityDiamondFontStyle
    ActivityEndColor STYLE_ACCENT
    ActivityFontColor STYLE_ACCENT
    ' ActivityFontName
    ' ActivityFontSize
    ' ActivityFontStyle
    ActivityStartColor STYLE_ACCENT
    ActorBackgroundColor STYLE_BGC
    ActorBorderColor STYLE_ACCENT
    ActorFontColor STYLE_ACCENT
    ' ActorFontName
    ' ActorFontSize
    ' ActorFontStyle
    ActorStereotypeFontColor STYLE_ACCENT
    ' ActorStereotypeFontName
    ' ActorStereotypeFontSize
    ' ActorStereotypeFontStyle
    AgentBackgroundColor STYLE_BGC
    AgentBorderColor STYLE_ACCENT
    ' AgentBorderThickness
    AgentFontColor STYLE_ACCENT
    ' AgentFontName
    ' AgentFontSize
    ' AgentFontStyle
    AgentStereotypeFontColor STYLE_ACCENT
    ' AgentStereotypeFontName
    ' AgentStereotypeFontSize
    ' AgentStereotypeFontStyle
    ArchimateBackgroundColor STYLE_BGC
    ArchimateBorderColor STYLE_ACCENT
    ' ArchimateBorderThickness
    ArchimateFontColor STYLE_ACCENT
    ' ArchimateFontName
    ' ArchimateFontSize
    ' ArchimateFontStyle
    ArchimateStereotypeFontColor STYLE_ACCENT
    ' ArchimateStereotypeFontName
    ' ArchimateStereotypeFontSize
    ' ArchimateStereotypeFontStyle
    ArrowColor STYLE_ACCENT
    ArrowFontColor STYLE_ACCENT
    ' ArrowFontName
    ' ArrowFontSize
    ' ArrowFontStyle
    ArrowHeadColor STYLE_ACCENT
    ArrowLollipopColor STYLE_ACCENT
    ' ArrowMessageAlignment
    ' ArrowThickness
    ArtifactBackgroundColor STYLE_BGC
    ArtifactBorderColor STYLE_ACCENT
    ArtifactFontColor STYLE_ACCENT
    ' ArtifactFontName
    ' ArtifactFontSize
    ' ArtifactFontStyle
    ArtifactStereotypeFontColor STYLE_ACCENT
    ' ArtifactStereotypeFontName
    ' ArtifactStereotypeFontSize
    ' ArtifactStereotypeFontStyle
    BackgroundColor STYLE_ACCENT
    BiddableBackgroundColor STYLE_BGC
    BiddableBorderColor STYLE_ACCENT
    BoundaryBackgroundColor STYLE_BGC
    BoundaryBorderColor STYLE_ACCENT
    BoundaryFontColor STYLE_ACCENT
    ' BoundaryFontName
    ' BoundaryFontSize
    ' BoundaryFontStyle
    BoundaryStereotypeFontColor STYLE_ACCENT
    ' BoundaryStereotypeFontName
    ' BoundaryStereotypeFontSize
    ' BoundaryStereotypeFontStyle
    ' BoxPadding
    CaptionFontColor STYLE_ACCENT
    ' CaptionFontName
    ' CaptionFontSize
    ' CaptionFontStyle
    CardBackgroundColor STYLE_BGC
    CardBorderColor STYLE_ACCENT
    ' CardBorderThickness
    CardFontColor STYLE_ACCENT
    ' CardFontName
    ' CardFontSize
    ' CardFontStyle
    CardStereotypeFontColor STYLE_ACCENT
    ' CardStereotypeFontName
    ' CardStereotypeFontSize
    ' CardStereotypeFontStyle
    CircledCharacterFontColor STYLE_ACCENT
    ' CircledCharacterFontName
    ' CircledCharacterFontSize
    ' CircledCharacterFontStyle
    ' CircledCharacterRadius
    ClassAttributeFontColor STYLE_ACCENT
    ' ClassAttributeFontName
    ' ClassAttributeFontSize
    ' ClassAttributeFontStyle
    ' ClassAttributeIconSize
    ClassBackgroundColor STYLE_BGC
    ClassBorderColor STYLE_ACCENT
    ' ClassBorderThickness
    ClassFontColor STYLE_ACCENT
    ' ClassFontName
    ' ClassFontSize
    ' ClassFontStyle
    ClassHeaderBackgroundColor STYLE_BGC
    ClassStereotypeFontColor STYLE_ACCENT
    ' ClassStereotypeFontName
    ' ClassStereotypeFontSize
    ' ClassStereotypeFontStyle
    CloudBackgroundColor STYLE_BGC
    CloudBorderColor STYLE_ACCENT
    CloudFontColor STYLE_ACCENT
    ' CloudFontName
    ' CloudFontSize
    ' CloudFontStyle
    CloudStereotypeFontColor STYLE_ACCENT
    ' CloudStereotypeFontName
    ' CloudStereotypeFontSize
    ' CloudStereotypeFontStyle
    CollectionsBackgroundColor STYLE_BGC
    CollectionsBorderColor STYLE_ACCENT
    ' ColorArrowSeparationSpace
    ComponentBackgroundColor STYLE_BGC
    ComponentBorderColor STYLE_ACCENT
    ' ComponentBorderThickness
    ComponentFontColor STYLE_ACCENT
    ' ComponentFontName
    ' ComponentFontSize
    ' ComponentFontStyle
    ComponentStereotypeFontColor STYLE_ACCENT
    ' ComponentStereotypeFontName
    ' ComponentStereotypeFontSize
    ' ComponentStereotypeFontStyle
    ' ComponentStyle
    ' ConditionEndStyle
    ' ConditionStyle
    ControlBackgroundColor STYLE_BGC
    ControlBorderColor STYLE_ACCENT
    ControlFontColor STYLE_ACCENT
    ' ControlFontName
    ' ControlFontSize
    ' ControlFontStyle
    ControlStereotypeFontColor STYLE_ACCENT
    ' ControlStereotypeFontName
    ' ControlStereotypeFontSize
    ' ControlStereotypeFontStyle
    DatabaseBackgroundColor STYLE_BGC
    DatabaseBorderColor STYLE_ACCENT
    DatabaseFontColor STYLE_ACCENT
    ' DatabaseFontName
    ' DatabaseFontSize
    ' DatabaseFontStyle
    DatabaseStereotypeFontColor STYLE_ACCENT
    ' DatabaseStereotypeFontName
    ' DatabaseStereotypeFontSize
    ' DatabaseStereotypeFontStyle
    DefaultFontColor STYLE_ACCENT
    ' DefaultFontName
    ' DefaultFontSize
    ' DefaultFontStyle
    ' DefaultMonospacedFontName
    ' DefaultTextAlignment
    DesignedBackgroundColor STYLE_BGC
    DesignedBorderColor STYLE_ACCENT
    ' DesignedDomainBorderThickness
    DesignedDomainFontColor STYLE_ACCENT
    ' DesignedDomainFontName
    ' DesignedDomainFontSize
    ' DesignedDomainFontStyle
    DesignedDomainStereotypeFontColor STYLE_ACCENT
    ' DesignedDomainStereotypeFontName
    ' DesignedDomainStereotypeFontSize
    ' DesignedDomainStereotypeFontStyle
    DiagramBorderColor STYLE_ACCENT
    ' DiagramBorderThickness
    DomainBackgroundColor STYLE_BGC
    DomainBorderColor STYLE_ACCENT
    ' DomainBorderThickness
    DomainFontColor STYLE_ACCENT
    ' DomainFontName
    ' DomainFontSize
    ' DomainFontStyle
    DomainStereotypeFontColor STYLE_ACCENT
    ' DomainStereotypeFontName
    ' DomainStereotypeFontSize
    ' DomainStereotypeFontStyle
    ' Dpi
    EntityBackgroundColor STYLE_BGC
    EntityBorderColor STYLE_ACCENT
    EntityFontColor STYLE_ACCENT
    ' EntityFontName
    ' EntityFontSize
    ' EntityFontStyle
    EntityStereotypeFontColor STYLE_ACCENT
    ' EntityStereotypeFontName
    ' EntityStereotypeFontSize
    ' EntityStereotypeFontStyle
    EnumBackgroundColor STYLE_BGC
    FileBackgroundColor STYLE_BGC
    FileBorderColor STYLE_ACCENT
    FileFontColor STYLE_ACCENT
    ' FileFontName
    ' FileFontSize
    ' FileFontStyle
    FileStereotypeFontColor STYLE_ACCENT
    ' FileStereotypeFontName
    ' FileStereotypeFontSize
    ' FileStereotypeFontStyle
    ' FixCircleLabelOverlapping
    FolderBackgroundColor STYLE_BGC
    FolderBorderColor STYLE_ACCENT
    FolderFontColor STYLE_ACCENT
    ' FolderFontName
    ' FolderFontSize
    ' FolderFontStyle
    FolderStereotypeFontColor STYLE_ACCENT
    ' FolderStereotypeFontName
    ' FolderStereotypeFontSize
    ' FolderStereotypeFontStyle
    FooterFontColor STYLE_ACCENT
    ' FooterFontName
    ' FooterFontSize
    ' FooterFontStyle
    FrameBackgroundColor STYLE_BGC
    FrameBorderColor STYLE_ACCENT
    FrameFontColor STYLE_ACCENT
    ' FrameFontName
    ' FrameFontSize
    ' FrameFontStyle
    FrameStereotypeFontColor STYLE_ACCENT
    ' FrameStereotypeFontName
    ' FrameStereotypeFontSize
    ' FrameStereotypeFontStyle
    ' GenericDisplay
    ' Guillemet
    ' Handwritten
    HeaderFontColor STYLE_ACCENT
    ' HeaderFontName
    ' HeaderFontSize
    ' HeaderFontStyle
    HyperlinkColor STYLE_ACCENT
    ' HyperlinkUnderline
    IconIEMandatoryColor STYLE_ACCENT
    IconPackageBackgroundColor STYLE_BGC
    IconPackageColor STYLE_ACCENT
    IconPrivateBackgroundColor STYLE_BGC
    IconPrivateColor STYLE_ACCENT
    IconProtectedBackgroundColor STYLE_BGC
    IconProtectedColor STYLE_ACCENT
    IconPublicBackgroundColor STYLE_BGC
    IconPublicColor STYLE_ACCENT
    InterfaceBackgroundColor STYLE_BGC
    InterfaceBorderColor STYLE_ACCENT
    InterfaceFontColor STYLE_ACCENT
    ' InterfaceFontName
    ' InterfaceFontSize
    ' InterfaceFontStyle
    InterfaceStereotypeFontColor STYLE_ACCENT
    ' InterfaceStereotypeFontName
    ' InterfaceStereotypeFontSize
    ' InterfaceStereotypeFontStyle
    LegendBackgroundColor STYLE_BGC
    LegendBorderColor STYLE_ACCENT
    ' LegendBorderThickness
    LegendFontColor STYLE_ACCENT
    ' LegendFontName
    ' LegendFontSize
    ' LegendFontStyle
    LexicalBackgroundColor STYLE_BGC
    LexicalBorderColor STYLE_ACCENT
    ' LifelineStrategy
    ' Linetype
    MachineBackgroundColor STYLE_BGC
    MachineBorderColor STYLE_ACCENT
    ' MachineBorderThickness
    MachineFontColor STYLE_ACCENT
    ' MachineFontName
    ' MachineFontSize
    ' MachineFontStyle
    MachineStereotypeFontColor STYLE_ACCENT
    ' MachineStereotypeFontName
    ' MachineStereotypeFontSize
    ' MachineStereotypeFontStyle
    ' MaxAsciiMessageLength
    ' MaxMessageSize
    ' MinClassWidth
    ' Monochrome
    NodeBackgroundColor STYLE_BGC
    NodeBorderColor STYLE_ACCENT
    NodeFontColor STYLE_ACCENT
    ' NodeFontName
    ' NodeFontSize
    ' NodeFontStyle
    NodeStereotypeFontColor STYLE_ACCENT
    ' NodeStereotypeFontName
    ' NodeStereotypeFontSize
    ' NodeStereotypeFontStyle
    ' Nodesep
    NoteBackgroundColor STYLE_BGC
    NoteBorderColor STYLE_ACCENT
    ' NoteBorderThickness
    NoteFontColor STYLE_ACCENT
    ' NoteFontName
    ' NoteFontSize
    ' NoteFontStyle
    ' NoteShadowing
    ' NoteTextAlignment
    ObjectAttributeFontColor STYLE_ACCENT
    ' ObjectAttributeFontName
    ' ObjectAttributeFontSize
    ' ObjectAttributeFontStyle
    ObjectBackgroundColor STYLE_BGC
    ObjectBorderColor STYLE_ACCENT
    ' ObjectBorderThickness
    ObjectFontColor STYLE_ACCENT
    ' ObjectFontName
    ' ObjectFontSize
    ' ObjectFontStyle
    ObjectStereotypeFontColor STYLE_ACCENT
    ' ObjectStereotypeFontName
    ' ObjectStereotypeFontSize
    ' ObjectStereotypeFontStyle
    PackageBackgroundColor STYLE_BGC
    PackageBorderColor STYLE_ACCENT
    ' PackageBorderThickness
    PackageFontColor STYLE_ACCENT
    ' PackageFontName
    ' PackageFontSize
    ' PackageFontStyle
    PackageStereotypeFontColor STYLE_ACCENT
    ' PackageStereotypeFontName
    ' PackageStereotypeFontSize
    ' PackageStereotypeFontStyle
    ' PackageStyle
    ' PackageTitleAlignment
    ' Padding
    PageBorderColor STYLE_ACCENT
    PageExternalColor STYLE_ACCENT
    ' PageMargin
    ParticipantBackgroundColor STYLE_BGC
    ParticipantBorderColor STYLE_ACCENT
    ParticipantFontColor STYLE_ACCENT
    ' ParticipantFontName
    ' ParticipantFontSize
    ' ParticipantFontStyle
    ' ParticipantPadding
    ParticipantStereotypeFontColor STYLE_ACCENT
    ' ParticipantStereotypeFontName
    ' ParticipantStereotypeFontSize
    ' ParticipantStereotypeFontStyle
    PartitionBackgroundColor STYLE_BGC
    PartitionBorderColor STYLE_ACCENT
    ' PartitionBorderThickness
    PartitionFontColor STYLE_ACCENT
    ' PartitionFontName
    ' PartitionFontSize
    ' PartitionFontStyle
    PathHoverColor STYLE_ACCENT
    QueueBackgroundColor STYLE_BGC
    QueueBorderColor STYLE_ACCENT
    ' QueueBorderThickness
    QueueFontColor STYLE_ACCENT
    ' QueueFontName
    ' QueueFontSize
    ' QueueFontStyle
    QueueStereotypeFontColor STYLE_ACCENT
    ' QueueStereotypeFontName
    ' QueueStereotypeFontSize
    ' QueueStereotypeFontStyle
    ' Ranksep
    RectangleBackgroundColor STYLE_BGC
    RectangleBorderColor STYLE_ACCENT
    ' RectangleBorderThickness
    RectangleFontColor STYLE_ACCENT
    ' RectangleFontName
    ' RectangleFontSize
    ' RectangleFontStyle
    RectangleStereotypeFontColor STYLE_ACCENT
    ' RectangleStereotypeFontName
    ' RectangleStereotypeFontSize
    ' RectangleStereotypeFontStyle
    RequirementBackgroundColor STYLE_BGC
    RequirementBorderColor STYLE_ACCENT
    ' RequirementBorderThickness
    RequirementFontColor STYLE_ACCENT
    ' RequirementFontName
    ' RequirementFontSize
    ' RequirementFontStyle
    RequirementStereotypeFontColor STYLE_ACCENT
    ' RequirementStereotypeFontName
    ' RequirementStereotypeFontSize
    ' RequirementStereotypeFontStyle
    ' ResponseMessageBelowArrow
    ' RoundCorner
    ' SameClassWidth
    ' SequenceActorBorderThickness
    ' SequenceArrowThickness
    SequenceBoxBackgroundColor STYLE_BGC
    SequenceBoxBorderColor STYLE_ACCENT
    SequenceBoxFontColor STYLE_ACCENT
    ' SequenceBoxFontName
    ' SequenceBoxFontSize
    ' SequenceBoxFontStyle
    SequenceDelayFontColor STYLE_ACCENT
    ' SequenceDelayFontName
    ' SequenceDelayFontSize
    ' SequenceDelayFontStyle
    SequenceDividerBackgroundColor STYLE_BGC
    SequenceDividerBorderColor STYLE_ACCENT
    ' SequenceDividerBorderThickness
    SequenceDividerFontColor STYLE_ACCENT
    ' SequenceDividerFontName
    ' SequenceDividerFontSize
    ' SequenceDividerFontStyle
    SequenceGroupBackgroundColor STYLE_BGC
    SequenceGroupBodyBackgroundColor STYLE_BGC
    SequenceGroupBorderColor STYLE_ACCENT
    ' SequenceGroupBorderThickness
    SequenceGroupFontColor STYLE_ACCENT
    ' SequenceGroupFontName
    ' SequenceGroupFontSize
    ' SequenceGroupFontStyle
    SequenceGroupHeaderFontColor STYLE_ACCENT
    ' SequenceGroupHeaderFontName
    ' SequenceGroupHeaderFontSize
    ' SequenceGroupHeaderFontStyle
    SequenceLifeLineBackgroundColor STYLE_BGC
    SequenceLifeLineBorderColor STYLE_ACCENT
    ' SequenceLifeLineBorderThickness
    ' SequenceMessageAlignment
    ' SequenceMessageTextAlignment
    SequenceNewpageSeparatorColor STYLE_ACCENT
    ' SequenceParticipant
    ' SequenceParticipantBorderThickness
    ' SequenceReferenceAlignment
    SequenceReferenceBackgroundColor STYLE_BGC
    SequenceReferenceBorderColor STYLE_ACCENT
    ' SequenceReferenceBorderThickness
    SequenceReferenceFontColor STYLE_ACCENT
    ' SequenceReferenceFontName
    ' SequenceReferenceFontSize
    ' SequenceReferenceFontStyle
    SequenceReferenceHeaderBackgroundColor STYLE_BGC
    SequenceStereotypeFontColor STYLE_ACCENT
    ' SequenceStereotypeFontName
    ' SequenceStereotypeFontSize
    ' SequenceStereotypeFontStyle
    ' Shadowing
    StackBackgroundColor STYLE_BGC
    StackBorderColor STYLE_ACCENT
    StackFontColor STYLE_ACCENT
    ' StackFontName
    ' StackFontSize
    ' StackFontStyle
    StackStereotypeFontColor STYLE_ACCENT
    ' StackStereotypeFontName
    ' StackStereotypeFontSize
    ' StackStereotypeFontStyle
    StateAttributeFontColor STYLE_ACCENT
    ' StateAttributeFontName
    ' StateAttributeFontSize
    ' StateAttributeFontStyle
    StateBackgroundColor STYLE_BGC
    StateBorderColor STYLE_ACCENT
    StateEndColor STYLE_ACCENT
    StateFontColor STYLE_ACCENT
    ' StateFontName
    ' StateFontSize
    ' StateFontStyle
    ' StateMessageAlignment
    StateStartColor STYLE_ACCENT
    StereotypeABackgroundColor STYLE_BGC
    StereotypeABorderColor STYLE_ACCENT
    StereotypeCBackgroundColor STYLE_BGC
    StereotypeCBorderColor STYLE_ACCENT
    StereotypeEBackgroundColor STYLE_BGC
    StereotypeEBorderColor STYLE_ACCENT
    StereotypeIBackgroundColor STYLE_BGC
    StereotypeIBorderColor STYLE_ACCENT
    StereotypeNBackgroundColor STYLE_BGC
    StereotypeNBorderColor STYLE_ACCENT
    ' StereotypePosition
    StorageBackgroundColor STYLE_BGC
    StorageBorderColor STYLE_ACCENT
    StorageFontColor STYLE_ACCENT
    ' StorageFontName
    ' StorageFontSize
    ' StorageFontStyle
    StorageStereotypeFontColor STYLE_ACCENT
    ' StorageStereotypeFontName
    ' StorageStereotypeFontSize
    ' StorageStereotypeFontStyle
    ' Style
    ' SvglinkTarget
    SwimlaneBorderColor STYLE_ACCENT
    ' SwimlaneBorderThickness
    SwimlaneTitleBackgroundColor STYLE_BGC
    SwimlaneTitleFontColor STYLE_ACCENT
    ' SwimlaneTitleFontName
    ' SwimlaneTitleFontSize
    ' SwimlaneTitleFontStyle
    ' SwimlaneWidth
    ' SwimlaneWrapTitleWidth
    ' TabSize
    TimingFontColor STYLE_ACCENT
    ' TimingFontName
    ' TimingFontSize
    ' TimingFontStyle
    TitleBackgroundColor STYLE_BGC
    TitleBorderColor STYLE_ACCENT
    ' TitleBorderRoundCorner
    ' TitleBorderThickness
    TitleFontColor STYLE_ACCENT
    ' TitleFontName
    ' TitleFontSize
    ' TitleFontStyle
    UsecaseBackgroundColor STYLE_BGC
    UsecaseBorderColor STYLE_ACCENT
    ' UsecaseBorderThickness
    UsecaseFontColor STYLE_ACCENT
    ' UsecaseFontName
    ' UsecaseFontSize
    ' UsecaseFontStyle
    UsecaseStereotypeFontColor STYLE_ACCENT
    ' UsecaseStereotypeFontName
    ' UsecaseStereotypeFontSize
    ' UsecaseStereotypeFontStyle
    ' WrapWidth
}

    autonumber 1 "0:"
    title Sequence Diagram

    A -> B: Perform Action
    B --> A: (Response)
    note over A,B
        Hello there.
    end note
@enduml