@startuml Templates For Use In Other Diagrams - title
title Participants For Use In _index.puml

!startsub COMMON_PARTICIPANTS

' Don't forget to add your Exclusion Flags for anything you do not need. (try the shortcut `puml-xf`)

' Demo: defining the variable ensures a participant is excluded.
!$NO_SEEME=""

!includesub common.participants.iuml!COMMON_INCLUDES
!includesub common.participants.iuml!COMMON_PARTICIPANTS

!endsub
@enduml